# Generated by Django 3.0 on 2020-02-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_autorizador_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='autorizador',
        ),
        migrations.AddField(
            model_name='user',
            name='autorizador',
            field=models.ManyToManyField(blank=True, null=True, to='usuarios.Autorizador'),
        ),
    ]
