# Generated by Django 3.0 on 2020-02-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200221_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizador',
            name='status',
            field=models.BooleanField(blank=True, default=1),
        ),
    ]
