# Generated by Django 3.0 on 2020-02-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_autorizador_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizador',
            name='status',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
    ]
