# Generated by Django 3.0 on 2020-03-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20200224_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=250, null=True)),
                ('op_codifica_activo', models.BooleanField(blank=True, null=True)),
                ('op_activa_activo', models.BooleanField(blank=True, null=True)),
                ('op_1', models.BooleanField(blank=True, null=True)),
                ('op_2', models.BooleanField(blank=True, null=True)),
                ('op_3', models.BooleanField(blank=True, null=True)),
                ('op_4', models.BooleanField(blank=True, null=True)),
                ('op_5', models.BooleanField(blank=True, null=True)),
                ('op_6', models.BooleanField(blank=True, null=True)),
                ('op_7', models.BooleanField(blank=True, null=True)),
                ('op_8', models.BooleanField(blank=True, null=True)),
                ('op_9', models.BooleanField(blank=True, null=True)),
                ('op_10', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
