# Generated by Django 3.0 on 2020-03-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Secundario'), (1, 'Principal')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='autorizador',
            field=models.ManyToManyField(blank=True, to='usuarios.Autorizador'),
        ),
    ]
