# Generated by Django 3.1.2 on 2020-10-04 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20200611_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubica_nombre', models.CharField(max_length=50, null=True)),
                ('ubica_estado', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['ubica_nombre'],
            },
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Secundario'), (1, 'Principal')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_nombre', models.CharField(max_length=50, null=True)),
                ('dep_estado', models.IntegerField(blank=True)),
                ('dep_ubica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ubicacion')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['dep_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_nombre', models.CharField(max_length=50, null=True)),
                ('area_estado', models.IntegerField(blank=True)),
                ('area_departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.departamento')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['area_nombre'],
            },
        ),
    ]
