# Generated by Django 3.0.7 on 2020-10-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20201008_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='soporte',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Secundario'), (1, 'Principal')], null=True),
        ),
    ]
