# Generated by Django 3.0.7 on 2021-01-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_auto_20201019_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='autoriza_salida',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Autorizador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Secundario'), (1, 'Principal')], null=True),
        ),
    ]
