# Generated by Django 3.0.7 on 2021-01-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_auto_20210128_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizador',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Principal'), (2, 'Secundario')], null=True),
        ),
    ]
