# Generated by Django 3.0.7 on 2021-05-10 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_auto_20210326_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mantenimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revisa_mantenimiento', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Secundario'), (3, 'Salida Activos'), (1, 'Principal')], null=True),
        ),
    ]
