# Generated by Django 3.0.7 on 2021-05-10 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_auto_20210510_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Principal'), (2, 'Secundario'), (3, 'Salida Activos')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revisa_mantenimiento', to=settings.AUTH_USER_MODEL),
        ),
    ]
