# Generated by Django 3.0.7 on 2021-05-13 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_auto_20210510_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revisa_supervisor1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Secundario'), (1, 'Principal'), (3, 'Salida Activos')], null=True),
        ),
    ]
