# Generated by Django 3.0.7 on 2021-05-28 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_auto_20210513_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revisa_supervisor2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Principal'), (3, 'Salida Activos'), (2, 'Secundario')], null=True),
        ),
    ]
