# Generated by Django 3.0.8 on 2022-02-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_auto_20220210_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'permissions': (('procesos', 'Procesos'), ('desecho', 'Desecho'), ('ingresa_solicitud_desecho', 'Ingresa Solicitudes Desecho'), ('autoriza_1n_desecho', 'Autoriza Solicitudes Desecho'), ('autoriza_1n_donacion', 'Autoriza Solicitudes Donaciones'), ('autoriza_2n_desecho', 'Autoriza Seguridad Solicitudes Desecho'), ('salida_desecho_guardias', 'Salida Desecho Guardias'))},
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Principal'), (3, 'Salida Activos'), (2, 'Secundario')], null=True),
        ),
    ]
