# Generated by Django 3.0.8 on 2022-03-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_auto_20220323_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'permissions': (('procesos', 'Procesos'), ('desecho', 'Desecho'), ('ingresa_solicitud_desecho', 'Ingresa Solicitudes Desecho'), ('autoriza_1n_desecho', 'Autoriza Solicitudes Desecho'), ('autoriza_1n_donacion', 'Autoriza Solicitudes Donaciones'), ('autoriza_2n_desecho', 'Autoriza Seguridad Solicitudes Desecho'), ('salida_desecho_guardias', 'Salida Desecho Guardias'), ('reporte_general_desecho', 'Reporte General Desecho'), ('materia_prima', 'Materia Prima'), ('inspeccion_materia_prima', 'Inspección Materia Prima'))},
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Salida Activos'), (2, 'Secundario'), (1, 'Principal')], null=True),
        ),
    ]
