# Generated by Django 3.0.8 on 2022-04-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_auto_20220328_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='generador_int',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='generador_int', to='usuarios.Generador'),
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Secundario'), (3, 'Salida Activos'), (1, 'Principal')], null=True),
        ),
    ]
