# Generated by Django 3.0.3 on 2022-05-03 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0040_auto_20220426_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='autoriza_oti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aoti', to='usuarios.Autorizador'),
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Principal'), (2, 'Secundario'), (3, 'Salida Activos')], null=True),
        ),
    ]
