# Generated by Django 3.0.3 on 2022-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0041_auto_20220503_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Salida Activos'), (1, 'Principal'), (2, 'Secundario')], null=True),
        ),
    ]
