# Generated by Django 3.0.8 on 2022-06-16 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0043_auto_20220519_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consulta_experta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='experto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Principal'), (2, 'Secundario'), (3, 'Salida Activos')], null=True),
        ),
    ]
