# Generated by Django 3.0.8 on 2022-06-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0044_auto_20220616_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Principal'), (3, 'Salida Activos'), (2, 'Secundario')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='consulta_experta',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
