# Generated by Django 3.0.8 on 2022-06-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0045_auto_20220616_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genera_consultas_a_expertos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Salida Activos'), (1, 'Principal'), (2, 'Secundario')], null=True),
        ),
    ]
