# Generated by Django 3.0.8 on 2022-10-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0049_auto_20220801_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Salida Activos'), (2, 'Secundario'), (1, 'Principal')], null=True),
        ),
    ]
