# Generated by Django 3.0.8 on 2022-10-28 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0050_auto_20221019_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('cod', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Activo'), (0, 'Inactivo')], null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Secundario'), (1, 'Principal'), (3, 'Salida Activos')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Roles'),
        ),
    ]
