# Generated by Django 3.0 on 2020-02-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20200221_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='calificacion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
