# Generated by Django 3.0 on 2020-03-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_auto_20200227_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor_det',
            name='empresa_tipo',
            field=models.CharField(blank=True, choices=[('Persona Jurídica', 'Persona Jurídica'), ('Persona Natural', 'Persona Natural')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='giro_negocio_igual',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tipo_instalaciones',
            field=models.CharField(blank=True, choices=[('Compartida por varias empresas', 'Compartida por varias empresas'), ('Trabaja en residencia', 'Trabaja en residencia'), ('Propias', 'Propias')], max_length=50, null=True),
        ),
    ]
