# Generated by Django 3.0 on 2020-03-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_auto_20200303_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor_det',
            name='sugerencia_proceso_pago',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='sugerencia_proceso_recepcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=50, null=True),
        ),
    ]
