# Generated by Django 3.0 on 2020-08-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0042_auto_20200805_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga_respuestas',
            name='p003',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carga_respuestas',
            name='p037',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(blank=True, choices=[('INACTIVO', 'INACTIVO'), ('ACTIVO', 'ACTIVO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='respondio_encuesta',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='empresa_tipo',
            field=models.CharField(blank=True, choices=[('Persona Jurídica', 'Persona Jurídica'), ('Persona Natural', 'Persona Natural')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='es_proveedor_maquinaria_o_equipo',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Maquinaria y/o equipos', 'Maquinaria y/o equipos'), ('Repuestos de maquinaria y/o equipos', 'Repuestos de maquinaria y/o equipos'), ('Servicio de mantenimiento de maquinaria y/o equipos', 'Servicio de mantenimiento de maquinaria y/o equipos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_fertilizantes_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(6, 'Conocer el orígen de las materias primas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (5, 'Los ingredientes activos vigentes en las legislaciones de USA, Japón, Europa'), (4, 'Certificado de que esta libre de noni fenol y cloruro de benzalconio'), (7, 'No soy proveedor de fertilizantes'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (3, 'Análisis de metales pesados')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_foliares_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(4, 'Conocer el orígen de las materias primas'), (5, 'No soy proveedor de FOLIARES'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (1, 'Registro de los productos en Agrocalidad o MAGAP')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_materia_organica_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis físico-químico y microbiológico de la M.O. (vigencia 1 año)'), (4, 'Conocer el orígen de las materias primas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (5, 'No soy proveedor de MATERIA ORGANICA'), (1, 'Registro de los productos en Agrocalidad o MAGAP')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_pesticidas_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(4, 'Los ingredientes activos deben estar vigentes en las legislaciones de USA,Japón y Europa'), (5, 'No soy proveedor de pesticidas'), (1, 'Registro de los productos en Agrocalidad o Magar'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleado'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_biodegradabilidad',
            field=models.CharField(blank=True, choices=[('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_determinar_concentracion_quimico',
            field=models.CharField(blank=True, choices=[('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_copia_hoja_seguridad_datos_msds',
            field=models.CharField(blank=True, choices=[('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_fichas_tecnicas_y_registros_sanitarios',
            field=models.CharField(blank=True, choices=[('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_formato_informacion_contacto_emergencia',
            field=models.CharField(blank=True, choices=[('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_ingredientes_activos_aprobados',
            field=models.CharField(blank=True, choices=[('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_encuesta',
            name='seccion',
            field=models.CharField(blank=True, choices=[(3, 'Licitud de Fondos'), (10, 'Fundas/Rollos'), (26, 'Korex - Sleep Shipt'), (9, 'Información de la relacion comercial con Ecofroz'), (11, 'Control de Plagas'), (8, 'Requisitos Persona Juridica'), (34, 'Retroalimentacion Ecofroz'), (29, 'Buenas practicas de seguridad'), (25, 'Transporte maritimo (navieras)'), (18, 'Materiales de laboratorio (insumos)'), (5, 'Información General'), (28, 'Buenas practicas de calidad'), (14, 'Quimicos de limpieza (Desinfectantes)'), (30, 'Buenas practicas ambientales'), (7, 'Requisitos persona Natural'), (16, 'Catering'), (22, 'Quimicos para el caldero'), (12, 'Centros de acopio'), (31, 'Buenas prracticas de  responsabilidad social'), (17, 'Laboratorios de Analisis'), (21, 'Materia Prima'), (23, 'Grados de grado alimenticio'), (4, 'Veracidad de las respuestas'), (6, 'Existencia y Legalidad'), (27, 'Transporte'), (20, 'Gestores ambientales de desechos'), (24, 'Transporte de contenedores'), (13, 'Quimicos de limpieza (Detergentes)'), (32, 'Buenas practicas laborales'), (2, 'Codigo de Etica'), (19, 'Laboratorios de calibracion'), (15, 'Cajas'), (33, 'Buenas practicas con proveedores y clientes'), (1, 'Fecha de elaboración')], max_length=200, null=True),
        ),
    ]
