# Generated by Django 3.0 on 2020-08-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0048_auto_20200805_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga_respuestas',
            name='p049',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p050',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p051',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p052',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p053',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p054',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p055',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p056',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p057',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p058',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p059',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p060',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p061',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p062',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p063',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p064',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p065',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p066',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p067',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p068',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p069',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p070',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p071',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p072',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p073',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p074',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p075',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p076',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p077',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p078',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p079',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p080',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p081',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p082',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p083',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p084',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p085',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p086',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p087',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p088',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p089',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p090',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p091',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p092',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p093',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p094',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p095',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p096',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p097',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p098',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p099',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p100',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p101',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p102',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p103',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p104',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p105',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p106',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p107',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p108',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p109',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p110',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p111',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p112',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p113',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p114',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p115',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p116',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p117',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p118',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p119',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p120',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p121',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p122',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p123',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p124',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p125',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p126',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p127',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p128',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p129',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p130',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p131',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p132',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p133',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p134',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p135',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p136',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p137',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p138',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p139',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p140',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p141',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p142',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p143',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p144',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p145',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p146',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p147',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p148',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p149',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p150',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p151',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p152',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p153',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p154',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p155',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p156',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p157',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p158',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p159',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p160',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p161',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p162',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p163',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p164',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p165',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p166',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p167',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p168',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p169',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p170',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p171',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p172',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p173',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p174',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p175',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p176',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p177',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p178',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p179',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p180',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p181',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p182',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p183',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p184',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p185',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p186',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p187',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p188',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p189',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p190',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p191',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p192',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p193',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p194',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p195',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p196',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p197',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p198',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p199',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p200',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p201',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p202',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p203',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p204',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p205',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p206',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p207',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p208',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p209',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p210',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p211',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p212',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p213',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p214',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p215',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p216',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p217',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p218',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas',
            name='p219',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='antecedentes_verificados_rep_legal',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='capacita_usuarios_prevencion_accidentes',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='conoce_proceso_pago',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='conoce_proceso_recepcion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='contrato_vigente_ecofroz',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='cumple_procedimiento_compra',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='cumple_procedimiento_entrega',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='cumple_procedimiento_facturacion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='cumplimiento_proceso_pago',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='ecofroz_explico_proceso_compra',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='empresa_tipo',
            field=models.CharField(blank=True, choices=[('Persona Jurídica', 'Persona Jurídica'), ('Persona Natural', 'Persona Natural')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='es_atendido_bien',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='es_proveedor_maquinaria_o_equipo',
            field=models.CharField(blank=True, choices=[('Repuestos de maquinaria y/o equipos', 'Repuestos de maquinaria y/o equipos'), ('Servicio de mantenimiento de maquinaria y/o equipos', 'Servicio de mantenimiento de maquinaria y/o equipos'), ('No', 'No'), ('Maquinaria y/o equipos', 'Maquinaria y/o equipos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='especificaciones_oportunas_claras',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='giro_negocio_igual',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='hace_mantenimiento_preventivo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='hace_respaldos_periodicos_informacion_empresa',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='optimiza_uso_recursos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='prioriza_contratacion_personal_zona',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proceso_compra_agil',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_fertilizantes_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(5, 'Los ingredientes activos vigentes en las legislaciones de USA, Japón, Europa'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (4, 'Certificado de que esta libre de noni fenol y cloruro de benzalconio'), (7, 'No soy proveedor de fertilizantes'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (3, 'Análisis de metales pesados'), (6, 'Conocer el orígen de las materias primas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_foliares_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(1, 'Registro de los productos en Agrocalidad o MAGAP'), (4, 'Conocer el orígen de las materias primas'), (5, 'No soy proveedor de FOLIARES'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_materia_organica_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(1, 'Registro de los productos en Agrocalidad o MAGAP'), (4, 'Conocer el orígen de las materias primas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (3, 'Análisis físico-químico y microbiológico de la M.O. (vigencia 1 año)'), (5, 'No soy proveedor de MATERIA ORGANICA')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_pesticidas_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(2, 'Fichas técnicas y hojas de seguridad de los productos empleado'), (5, 'No soy proveedor de pesticidas'), (4, 'Los ingredientes activos deben estar vigentes en las legislaciones de USA,Japón y Europa'), (1, 'Registro de los productos en Agrocalidad o Magar'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='realiza_simulacro_emergencia',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='requiere_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='subcontrata',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_activos_asegurados',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_afiliacion_empleados_iess',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_analisis_composicion_concentraciones',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_analisis_cumplimiento_fda_173310',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_aprobaciones_contacto_alimentos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_carta_garantia',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificacion_basc',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificacion_gfsi_o_bpm',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_aecpu',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_arcsa',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_auditoria_ecofroz_por_no_gfsi',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_biodegradabilidad',
            field=models.CharField(blank=True, choices=[('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_buenas_practicas_manufactura',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_calidad_por_lote',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_calidad_producto',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_destruccion_material_x_carga',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_determinar_concentracion_quimico',
            field=models.CharField(blank=True, choices=[('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_fabricacion_libre_alergenicos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_insumos_aoac',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_iso_17025',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_iso_21469',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_logistica_producto',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_migracion_fundas',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_mip_personal',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_nfs_h1_h2',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_npma',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_patrones_trazables_baja_incertidumbre',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_tiempo_analisis',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_transporte_exclusivo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_transporte_sellado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_validaciones_reduccion_logaritmica',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_cobertura_seguro_ocupantes_vehiculos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_cobertura_seguro_vehiculos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_codigo_conducta',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_copia_hoja_seguridad_datos_msds',
            field=models.CharField(blank=True, choices=[('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_documento_aceptacion_especificaciones_ecofroz',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_documentos_habilitantes_vehiculos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_especificacion_material_empaque',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_especificaciones_fichas_tecnicas',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_ficha_tecnica_hoja_seguridad_registro_sanitario',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_fichas_tecnicas_y_registros_sanitarios',
            field=models.CharField(blank=True, choices=[('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_formato_informacion_contacto_emergencia',
            field=models.CharField(blank=True, choices=[('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_formato_seleccion_materia_prima',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_homologacion_auditoria_basc_ecofroz',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_homologacion_gfsi',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_ingredientes_activos_aprobados',
            field=models.CharField(blank=True, choices=[('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_licencia_unica_funcionamiento_luae',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_lista_choferes_autorizados',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_matricula_vehiculo_actualizada',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_mecanismo_discrimen',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_mecanismo_satisfaccion_cliente',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_permiso_funcionamiento',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_permiso_operacion_transporte',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_plan_continuidad_negocio',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_plan_respuesta_riesgos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_politica_inclusion_social',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_politica_prevencion_actos_acoso',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_politica_prevencion_actos_corrupcion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_politica_proteccion_ambiente',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_politica_responsabilidad_social',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_poliza_responsabilidad_civil',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_practicas_no_discriminacion_laboral',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_procedimientos_ventas_no_conformes',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_procesos_mejora_continua',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_programa_auditoria_interna',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_programa_manejo_desechos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_reglamento_interno_seguridad_salud_laboral',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_reglamento_interno_trabajo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_reporte_inspeccion_permiso_funcionamiento',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_seguimiento_medico_trabajadores',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_seguro_ocupantes_vehiculo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_sistema_calidad_iso9001',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_sistema_comunicacion_transmision_datos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_sistema_evaluacion_seleccion_proveedores',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_sistema_seguridad_logistica_transporte',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tieneweb',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tipo_instalaciones',
            field=models.CharField(blank=True, choices=[('Compartida por varias empresas', 'Compartida por varias empresas'), ('Propias', 'Propias'), ('Trabaja en residencia', 'Trabaja en residencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='trabajadores_menores_16anios',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='utiliza_transporte_propio',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='vehiculos_estan_asegurados',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_encuesta',
            name='seccion',
            field=models.CharField(blank=True, choices=[(9, 'Información de la relacion comercial con Ecofroz'), (11, 'Control de Plagas'), (18, 'Materiales de laboratorio (insumos)'), (27, 'Transporte'), (33, 'Buenas practicas con proveedores y clientes'), (25, 'Transporte maritimo (navieras)'), (15, 'Cajas'), (28, 'Buenas practicas de calidad'), (29, 'Buenas practicas de seguridad'), (2, 'Codigo de Etica'), (34, 'Retroalimentacion Ecofroz'), (16, 'Catering'), (30, 'Buenas practicas ambientales'), (32, 'Buenas practicas laborales'), (8, 'Requisitos Persona Juridica'), (4, 'Veracidad de las respuestas'), (17, 'Laboratorios de Analisis'), (1, 'Fecha de elaboración'), (24, 'Transporte de contenedores'), (5, 'Información General'), (12, 'Centros de acopio'), (19, 'Laboratorios de calibracion'), (14, 'Quimicos de limpieza (Desinfectantes)'), (13, 'Quimicos de limpieza (Detergentes)'), (20, 'Gestores ambientales de desechos'), (7, 'Requisitos persona Natural'), (3, 'Licitud de Fondos'), (22, 'Quimicos para el caldero'), (10, 'Fundas/Rollos'), (6, 'Existencia y Legalidad'), (23, 'Grados de grado alimenticio'), (26, 'Korex - Sleep Shipt'), (21, 'Materia Prima'), (31, 'Buenas prracticas de  responsabilidad social')], max_length=200, null=True),
        ),
    ]
