# Generated by Django 3.0.7 on 2020-08-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0054_auto_20200824_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': True, 'ordering': ['-fecha_modifica'], 'permissions': (('acceso_proveedores', 'Acceso Menu Proveedores'), ('acceso_provisional', 'Acceso Provicional Proveedores'))},
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='es_proveedor_maquinaria_o_equipo',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Servicio de mantenimiento de maquinaria y/o equipos', 'Servicio de mantenimiento de maquinaria y/o equipos'), ('Repuestos de maquinaria y/o equipos', 'Repuestos de maquinaria y/o equipos'), ('Maquinaria y/o equipos', 'Maquinaria y/o equipos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_fertilizantes_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(6, 'Conocer el orígen de las materias primas'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (7, 'No soy proveedor de fertilizantes'), (5, 'Los ingredientes activos vigentes en las legislaciones de USA, Japón, Europa'), (3, 'Análisis de metales pesados'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (4, 'Certificado de que esta libre de noni fenol y cloruro de benzalconio')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_foliares_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(1, 'Registro de los productos en Agrocalidad o MAGAP'), (5, 'No soy proveedor de FOLIARES'), (4, 'Conocer el orígen de las materias primas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_materia_organica_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(1, 'Registro de los productos en Agrocalidad o MAGAP'), (5, 'No soy proveedor de MATERIA ORGANICA'), (4, 'Conocer el orígen de las materias primas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (3, 'Análisis físico-químico y microbiológico de la M.O. (vigencia 1 año)')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_pesticidas_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(1, 'Registro de los productos en Agrocalidad o Magar'), (4, 'Los ingredientes activos deben estar vigentes en las legislaciones de USA,Japón y Europa'), (5, 'No soy proveedor de pesticidas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleado'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('Por correo electrónico', 'Por correo electrónico'), ('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_biodegradabilidad',
            field=models.CharField(blank=True, choices=[('Por correo electrónico', 'Por correo electrónico'), ('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_determinar_concentracion_quimico',
            field=models.CharField(blank=True, choices=[('Por correo electrónico', 'Por correo electrónico'), ('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_copia_hoja_seguridad_datos_msds',
            field=models.CharField(blank=True, choices=[('Por correo electrónico', 'Por correo electrónico'), ('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_fichas_tecnicas_y_registros_sanitarios',
            field=models.CharField(blank=True, choices=[('Por correo electrónico', 'Por correo electrónico'), ('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_formato_informacion_contacto_emergencia',
            field=models.CharField(blank=True, choices=[('Por correo electrónico', 'Por correo electrónico'), ('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_ingredientes_activos_aprobados',
            field=models.CharField(blank=True, choices=[('Por correo electrónico', 'Por correo electrónico'), ('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tipo_instalaciones',
            field=models.CharField(blank=True, choices=[('Compartida por varias empresas', 'Compartida por varias empresas'), ('Trabaja en residencia', 'Trabaja en residencia'), ('Propias', 'Propias')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_encuesta',
            name='seccion',
            field=models.CharField(blank=True, choices=[(27, 'Transporte'), (2, 'Codigo de Etica'), (13, 'Quimicos de limpieza (Detergentes)'), (15, 'Cajas'), (12, 'Centros de acopio'), (25, 'Transporte maritimo (navieras)'), (4, 'Veracidad de las respuestas'), (14, 'Quimicos de limpieza (Desinfectantes)'), (16, 'Catering'), (32, 'Buenas practicas laborales'), (23, 'Grados de grado alimenticio'), (24, 'Transporte de contenedores'), (28, 'Buenas practicas de calidad'), (10, 'Fundas/Rollos'), (3, 'Licitud de Fondos'), (5, 'Información General'), (30, 'Buenas practicas ambientales'), (29, 'Buenas practicas de seguridad'), (33, 'Buenas practicas con proveedores y clientes'), (20, 'Gestores ambientales de desechos'), (17, 'Laboratorios de Analisis'), (8, 'Requisitos Persona Juridica'), (34, 'Retroalimentacion Ecofroz'), (26, 'Korex - Sleep Shipt'), (9, 'Información de la relacion comercial con Ecofroz'), (18, 'Materiales de laboratorio (insumos)'), (22, 'Quimicos para el caldero'), (6, 'Existencia y Legalidad'), (11, 'Control de Plagas'), (31, 'Buenas prracticas de  responsabilidad social'), (7, 'Requisitos persona Natural'), (1, 'Fecha de elaboración'), (21, 'Materia Prima'), (19, 'Laboratorios de calibracion')], max_length=200, null=True),
        ),
    ]
