# Generated by Django 3.0.8 on 2020-09-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0060_auto_20200925_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor_det',
            name='es_proveedor_maquinaria_o_equipo',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Repuestos de maquinaria y/o equipos', 'Repuestos de maquinaria y/o equipos'), ('Servicio de mantenimiento de maquinaria y/o equipos', 'Servicio de mantenimiento de maquinaria y/o equipos'), ('Maquinaria y/o equipos', 'Maquinaria y/o equipos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_fertilizantes_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(7, 'No soy proveedor de fertilizantes'), (3, 'Análisis de metales pesados'), (6, 'Conocer el orígen de las materias primas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (4, 'Certificado de que esta libre de noni fenol y cloruro de benzalconio'), (5, 'Los ingredientes activos vigentes en las legislaciones de USA, Japón, Europa')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_foliares_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (5, 'No soy proveedor de FOLIARES'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (4, 'Conocer el orígen de las materias primas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_materia_organica_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (5, 'No soy proveedor de MATERIA ORGANICA'), (3, 'Análisis físico-químico y microbiológico de la M.O. (vigencia 1 año)'), (4, 'Conocer el orígen de las materias primas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_pesticidas_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (1, 'Registro de los productos en Agrocalidad o Magar'), (4, 'Los ingredientes activos deben estar vigentes en las legislaciones de USA,Japón y Europa'), (5, 'No soy proveedor de pesticidas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleado')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Documento Físico', 'Documento Físico')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_biodegradabilidad',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_determinar_concentracion_quimico',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_copia_hoja_seguridad_datos_msds',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_fichas_tecnicas_y_registros_sanitarios',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_formato_informacion_contacto_emergencia',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_ingredientes_activos_aprobados',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tipo_instalaciones',
            field=models.CharField(blank=True, choices=[('Compartida por varias empresas', 'Compartida por varias empresas'), ('Propias', 'Propias'), ('Trabaja en residencia', 'Trabaja en residencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_encuesta',
            name='puntaje_pregunta_especifica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_encuesta',
            name='seccion',
            field=models.CharField(blank=True, choices=[(15, 'Cajas'), (27, 'Transporte'), (17, 'Laboratorios de Analisis'), (13, 'Quimicos de limpieza (Detergentes)'), (28, 'Buenas practicas de calidad'), (33, 'Buenas practicas con proveedores y clientes'), (11, 'Control de Plagas'), (16, 'Catering'), (26, 'Korex - Sleep Shipt'), (25, 'Transporte maritimo (navieras)'), (9, 'Información de la relacion comercial con Ecofroz'), (32, 'Buenas practicas laborales'), (4, 'Veracidad de las respuestas'), (5, 'Información General'), (29, 'Buenas practicas de seguridad'), (31, 'Buenas prracticas de  responsabilidad social'), (8, 'Requisitos Persona Juridica'), (23, 'Grados de grado alimenticio'), (30, 'Buenas practicas ambientales'), (1, 'Fecha de elaboración'), (34, 'Retroalimentacion Ecofroz'), (14, 'Quimicos de limpieza (Desinfectantes)'), (24, 'Transporte de contenedores'), (7, 'Requisitos persona Natural'), (3, 'Licitud de Fondos'), (12, 'Centros de acopio'), (19, 'Laboratorios de calibracion'), (21, 'Materia Prima'), (10, 'Fundas/Rollos'), (18, 'Materiales de laboratorio (insumos)'), (2, 'Codigo de Etica'), (20, 'Gestores ambientales de desechos'), (6, 'Existencia y Legalidad'), (22, 'Quimicos para el caldero')], max_length=200, null=True),
        ),
    ]
