# Generated by Django 3.0 on 2020-11-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0065_auto_20201130_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproveedor',
            name='estado',
            field=models.CharField(blank=True, choices=[('INACTIVO', 'INACTIVO'), ('ACTIVO', 'ACTIVO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='respondio_encuesta',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='es_proveedor_maquinaria_o_equipo',
            field=models.CharField(blank=True, choices=[('Repuestos de maquinaria y/o equipos', 'Repuestos de maquinaria y/o equipos'), ('No', 'No'), ('Maquinaria y/o equipos', 'Maquinaria y/o equipos'), ('Servicio de mantenimiento de maquinaria y/o equipos', 'Servicio de mantenimiento de maquinaria y/o equipos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='numero_de_fichas',
            field=models.IntegerField(blank=True, choices=[(1, 1), (13, 13), (3, 3), (15, 15), (10, 10), (5, 5), (17, 17), (12, 12), (19, 19), (14, 14), (2, 2), (4, 4), (6, 6), (7, 7), (8, 8), (9, 9), (16, 16), (11, 11), (18, 18), (20, 20)], null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_fertilizantes_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(6, 'Conocer el orígen de las materias primas'), (5, 'Los ingredientes activos vigentes en las legislaciones de USA, Japón, Europa'), (3, 'Análisis de metales pesados'), (4, 'Certificado de que esta libre de noni fenol y cloruro de benzalconio'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (7, 'No soy proveedor de fertilizantes')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_foliares_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (5, 'No soy proveedor de FOLIARES'), (4, 'Conocer el orígen de las materias primas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (1, 'Registro de los productos en Agrocalidad o MAGAP')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_materia_organica_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(5, 'No soy proveedor de MATERIA ORGANICA'), (4, 'Conocer el orígen de las materias primas'), (3, 'Análisis físico-químico y microbiológico de la M.O. (vigencia 1 año)'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (1, 'Registro de los productos en Agrocalidad o MAGAP')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_pesticidas_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (1, 'Registro de los productos en Agrocalidad o Magar'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleado'), (4, 'Los ingredientes activos deben estar vigentes en las legislaciones de USA,Japón y Europa'), (5, 'No soy proveedor de pesticidas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_biodegradabilidad',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_determinar_concentracion_quimico',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_copia_hoja_seguridad_datos_msds',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_fichas',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_fichas_tecnicas_y_registros_sanitarios',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_formato_informacion_contacto_emergencia',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_ingredientes_activos_aprobados',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tipo_instalaciones',
            field=models.CharField(blank=True, choices=[('Trabaja en residencia', 'Trabaja en residencia'), ('Compartida por varias empresas', 'Compartida por varias empresas'), ('Propias', 'Propias')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(blank=True, choices=[('INACTIVO', 'INACTIVO'), ('ACTIVO', 'ACTIVO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='respondio_encuesta',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='es_proveedor_maquinaria_o_equipo',
            field=models.CharField(blank=True, choices=[('Repuestos de maquinaria y/o equipos', 'Repuestos de maquinaria y/o equipos'), ('No', 'No'), ('Maquinaria y/o equipos', 'Maquinaria y/o equipos'), ('Servicio de mantenimiento de maquinaria y/o equipos', 'Servicio de mantenimiento de maquinaria y/o equipos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='numero_de_fichas',
            field=models.IntegerField(blank=True, choices=[(1, 1), (13, 13), (3, 3), (15, 15), (10, 10), (5, 5), (17, 17), (12, 12), (19, 19), (14, 14), (2, 2), (4, 4), (6, 6), (7, 7), (8, 8), (9, 9), (16, 16), (11, 11), (18, 18), (20, 20)], null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_fertilizantes_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(6, 'Conocer el orígen de las materias primas'), (5, 'Los ingredientes activos vigentes en las legislaciones de USA, Japón, Europa'), (3, 'Análisis de metales pesados'), (4, 'Certificado de que esta libre de noni fenol y cloruro de benzalconio'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (7, 'No soy proveedor de fertilizantes')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_foliares_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (5, 'No soy proveedor de FOLIARES'), (4, 'Conocer el orígen de las materias primas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (1, 'Registro de los productos en Agrocalidad o MAGAP')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_materia_organica_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(5, 'No soy proveedor de MATERIA ORGANICA'), (4, 'Conocer el orígen de las materias primas'), (3, 'Análisis físico-químico y microbiológico de la M.O. (vigencia 1 año)'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (1, 'Registro de los productos en Agrocalidad o MAGAP')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_pesticidas_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (1, 'Registro de los productos en Agrocalidad o Magar'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleado'), (4, 'Los ingredientes activos deben estar vigentes en las legislaciones de USA,Japón y Europa'), (5, 'No soy proveedor de pesticidas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_biodegradabilidad',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_determinar_concentracion_quimico',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_copia_hoja_seguridad_datos_msds',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_fichas',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_fichas_tecnicas_y_registros_sanitarios',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_formato_informacion_contacto_emergencia',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_ingredientes_activos_aprobados',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo requiero', 'No lo requiero'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico'), ('No lo tengo', 'No lo tengo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tipo_instalaciones',
            field=models.CharField(blank=True, choices=[('Trabaja en residencia', 'Trabaja en residencia'), ('Compartida por varias empresas', 'Compartida por varias empresas'), ('Propias', 'Propias')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_encuesta',
            name='seccion',
            field=models.CharField(blank=True, choices=[(6, 'Existencia y Legalidad'), (29, 'Buenas practicas de seguridad'), (2, 'Codigo de Etica'), (7, 'Requisitos persona Natural'), (22, 'Quimicos para el caldero'), (1, 'Fecha de elaboración'), (18, 'Materiales de laboratorio (insumos)'), (19, 'Laboratorios de calibracion'), (28, 'Buenas practicas de calidad'), (32, 'Buenas practicas laborales'), (11, 'Control de Plagas'), (31, 'Buenas prracticas de  responsabilidad social'), (17, 'Laboratorios de Analisis'), (15, 'Cajas'), (26, 'Korex - Sleep Shipt'), (5, 'Información General'), (34, 'Retroalimentacion Ecofroz'), (33, 'Buenas practicas con proveedores y clientes'), (14, 'Quimicos de limpieza (Desinfectantes)'), (9, 'Información de la relacion comercial con Ecofroz'), (3, 'Licitud de Fondos'), (16, 'Catering'), (23, 'Grados de grado alimenticio'), (12, 'Centros de acopio'), (10, 'Fundas/Rollos'), (4, 'Veracidad de las respuestas'), (30, 'Buenas practicas ambientales'), (27, 'Transporte'), (13, 'Quimicos de limpieza (Detergentes)'), (8, 'Requisitos Persona Juridica'), (21, 'Materia Prima'), (20, 'Gestores ambientales de desechos'), (24, 'Transporte de contenedores'), (25, 'Transporte maritimo (navieras)')], max_length=200, null=True),
        ),
    ]
