# Generated by Django 3.0.8 on 2021-04-09 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0084_auto_20210325_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor_encuesta',
            name='pregunta_comerciante',
        ),
        migrations.RemoveField(
            model_name='proveedor_encuesta',
            name='pregunta_distribuidor',
        ),
        migrations.RemoveField(
            model_name='proveedor_encuesta',
            name='pregunta_fabricante',
        ),
        migrations.RemoveField(
            model_name='proveedor_encuesta',
            name='pregunta_importador',
        ),
        migrations.RemoveField(
            model_name='proveedor_encuesta',
            name='pregunta_productor',
        ),
        migrations.AddField(
            model_name='historicalproveedor_respuestas',
            name='documento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.proveedor_documentos'),
        ),
        migrations.AddField(
            model_name='proveedor_respuestas',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proveedores.proveedor_documentos'),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='es_proveedor_maquinaria_o_equipo',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Servicio de mantenimiento de maquinaria y/o equipos', 'Servicio de mantenimiento de maquinaria y/o equipos'), ('Maquinaria y/o equipos', 'Maquinaria y/o equipos'), ('Repuestos de maquinaria y/o equipos', 'Repuestos de maquinaria y/o equipos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_fertilizantes_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(4, 'Certificado de que esta libre de noni fenol y cloruro de benzalconio'), (6, 'Conocer el orígen de las materias primas'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (7, 'No soy proveedor de fertilizantes'), (3, 'Análisis de metales pesados'), (5, 'Los ingredientes activos vigentes en las legislaciones de USA, Japón, Europa')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_foliares_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (5, 'No soy proveedor de FOLIARES'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (4, 'Conocer el orígen de las materias primas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_materia_organica_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis físico-químico y microbiológico de la M.O. (vigencia 1 año)'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (4, 'Conocer el orígen de las materias primas'), (5, 'No soy proveedor de MATERIA ORGANICA')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_pesticidas_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(1, 'Registro de los productos en Agrocalidad o Magar'), (4, 'Los ingredientes activos deben estar vigentes en las legislaciones de USA,Japón y Europa'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleado'), (5, 'No soy proveedor de pesticidas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo tengo', 'No lo tengo'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_biodegradabilidad',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo tengo', 'No lo tengo'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_determinar_concentracion_quimico',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo tengo', 'No lo tengo'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_copia_hoja_seguridad_datos_msds',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo tengo', 'No lo tengo'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_fichas_tecnicas_y_registros_sanitarios',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo tengo', 'No lo tengo'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_formato_informacion_contacto_emergencia',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo tengo', 'No lo tengo'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_ingredientes_activos_aprobados',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo tengo', 'No lo tengo'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tipo_instalaciones',
            field=models.CharField(blank=True, choices=[('Propias', 'Propias'), ('Compartida por varias empresas', 'Compartida por varias empresas'), ('Trabaja en residencia', 'Trabaja en residencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='es_proveedor_maquinaria_o_equipo',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Servicio de mantenimiento de maquinaria y/o equipos', 'Servicio de mantenimiento de maquinaria y/o equipos'), ('Maquinaria y/o equipos', 'Maquinaria y/o equipos'), ('Repuestos de maquinaria y/o equipos', 'Repuestos de maquinaria y/o equipos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_fertilizantes_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(4, 'Certificado de que esta libre de noni fenol y cloruro de benzalconio'), (6, 'Conocer el orígen de las materias primas'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (7, 'No soy proveedor de fertilizantes'), (3, 'Análisis de metales pesados'), (5, 'Los ingredientes activos vigentes en las legislaciones de USA, Japón, Europa')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_foliares_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (5, 'No soy proveedor de FOLIARES'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (4, 'Conocer el orígen de las materias primas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_materia_organica_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis físico-químico y microbiológico de la M.O. (vigencia 1 año)'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (4, 'Conocer el orígen de las materias primas'), (5, 'No soy proveedor de MATERIA ORGANICA')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_pesticidas_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(1, 'Registro de los productos en Agrocalidad o Magar'), (4, 'Los ingredientes activos deben estar vigentes en las legislaciones de USA,Japón y Europa'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleado'), (5, 'No soy proveedor de pesticidas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo tengo', 'No lo tengo'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_biodegradabilidad',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo tengo', 'No lo tengo'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_determinar_concentracion_quimico',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo tengo', 'No lo tengo'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_copia_hoja_seguridad_datos_msds',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo tengo', 'No lo tengo'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_fichas_tecnicas_y_registros_sanitarios',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo tengo', 'No lo tengo'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_formato_informacion_contacto_emergencia',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo tengo', 'No lo tengo'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_ingredientes_activos_aprobados',
            field=models.CharField(blank=True, choices=[('Adjunto a este formulario', 'Adjunto a este formulario'), ('No lo tengo', 'No lo tengo'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tipo_instalaciones',
            field=models.CharField(blank=True, choices=[('Propias', 'Propias'), ('Compartida por varias empresas', 'Compartida por varias empresas'), ('Trabaja en residencia', 'Trabaja en residencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_encuesta',
            name='seccion',
            field=models.CharField(blank=True, choices=[(12, 'Centros de acopio'), (22, 'Quimicos para el caldero'), (33, 'Buenas practicas con proveedores y clientes'), (18, 'Materiales de laboratorio (insumos)'), (20, 'Gestores ambientales de desechos'), (11, 'Control de Plagas'), (28, 'Buenas practicas de calidad'), (23, 'Grados de grado alimenticio'), (1, 'Fecha de elaboración'), (2, 'Codigo de Etica'), (26, 'Korex - Sleep Shipt'), (14, 'Quimicos de limpieza (Desinfectantes)'), (27, 'Transporte'), (6, 'Existencia y Legalidad'), (19, 'Laboratorios de calibracion'), (15, 'Cajas'), (7, 'Requisitos persona Natural'), (9, 'Información de la relacion comercial con Ecofroz'), (25, 'Transporte maritimo (navieras)'), (32, 'Buenas practicas laborales'), (16, 'Catering'), (17, 'Laboratorios de Analisis'), (5, 'Información General'), (29, 'Buenas practicas de seguridad'), (30, 'Buenas practicas ambientales'), (8, 'Requisitos Persona Juridica'), (10, 'Fundas/Rollos'), (3, 'Licitud de Fondos'), (4, 'Veracidad de las respuestas'), (13, 'Quimicos de limpieza (Detergentes)'), (21, 'Materia Prima'), (34, 'Retroalimentacion Ecofroz'), (31, 'Buenas prracticas de  responsabilidad social'), (24, 'Transporte de contenedores')], max_length=200, null=True),
        ),
    ]
