# Generated by Django 3.0.8 on 2021-07-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0116_auto_20210727_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p003',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p004',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p005',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p006',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p007',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p008',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p009',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p010',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p011',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p012',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p013',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p014',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p015',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p016',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p017',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p018',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p019',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p020',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p021',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p022',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p023',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p024',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p025',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p026',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p027',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p028',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p029',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p030',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p031',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p032',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p033',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p034',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p035',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p036',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p037',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p038',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p039',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p040',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p041',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p042',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p043',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p044',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p045',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p046',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p047',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p048',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p049',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p050',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p051',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p052',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p053',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p054',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p055',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p056',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p057',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p058',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p059',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p060',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p061',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p062',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p063',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p064',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p065',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p066',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p067',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p068',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p069',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p070',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p071',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p072',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p073',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p074',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p075',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p076',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p077',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p078',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p079',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p080',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p081',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p082',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p083',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p084',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p085',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p086',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p087',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p001',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carga_respuestas_prod_serv_varios',
            name='p002',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='documentos_prove',
            name='marca_cal',
            field=models.CharField(blank=True, choices=[('CORRECTA', 'CORECTA'), ('DESACTUALIZADA', 'DESACTUALIZADA'), ('INCORRECTA', 'INCORRECTA')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='proveedor_critico',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='proveedor_revisado',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='respondio_encuesta',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='antecedentes_verificados_rep_legal',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='capacita_usuarios_prevencion_accidentes',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='conoce_proceso_pago',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='conoce_proceso_recepcion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='contesta_reclamos_administrativos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='contesta_reclamos_calidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='contrato_vigente_ecofroz',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='cumple_procedimiento_compra',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='cumple_procedimiento_compra_calidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='cumple_procedimiento_entrega',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='cumple_procedimiento_entrega_calidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='cumple_procedimiento_facturacion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='cumple_procedimiento_facturacion_calidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='cumplimiento_proceso_pago',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='ecofroz_explico_proceso_compra',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='es_atendido_bien',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='es_proveedor_maquinaria_o_equipo',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Servicio de mantenimiento de maquinaria y/o equipos', 'Servicio de mantenimiento de maquinaria y/o equipos'), ('Maquinaria y/o equipos', 'Maquinaria y/o equipos'), ('Repuestos de maquinaria y/o equipos', 'Repuestos de maquinaria y/o equipos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='especificaciones_oportunas_claras',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='giro_negocio_igual',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='hace_mantenimiento_preventivo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='hace_respaldos_periodicos_informacion_empresa',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='optimiza_uso_recursos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='prioriza_contratacion_personal_zona',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proceso_compra_agil',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_fertilizantes_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(4, 'Certificado de que esta libre de noni fenol y cloruro de benzalconio'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (5, 'Los ingredientes activos vigentes en las legislaciones de USA, Japón, Europa'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (6, 'Conocer el orígen de las materias primas'), (3, 'Análisis de metales pesados'), (7, 'No soy proveedor de fertilizantes')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_foliares_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(1, 'Registro de los productos en Agrocalidad o MAGAP'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (4, 'Conocer el orígen de las materias primas'), (5, 'No soy proveedor de FOLIARES')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_materia_organica_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(5, 'No soy proveedor de MATERIA ORGANICA'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (4, 'Conocer el orígen de las materias primas'), (3, 'Análisis físico-químico y microbiológico de la M.O. (vigencia 1 año)')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_pesticidas_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(4, 'Los ingredientes activos deben estar vigentes en las legislaciones de USA,Japón y Europa'), (5, 'No soy proveedor de pesticidas'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleado'), (1, 'Registro de los productos en Agrocalidad o Magar')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='realiza_simulacro_emergencia',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='requiere_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='subcontrata',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_activos_asegurados',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_afiliacion_empleados_iess',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_analisis_composicion_concentraciones',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_analisis_cumplimiento_fda_173310',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_aprobaciones_contacto_alimentos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_carta_garantia',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificacion_basc',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificacion_gfsi_o_bpm',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_aecpu',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_arcsa',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_auditoria_ecofroz_por_no_gfsi',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_biodegradabilidad',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_buenas_practicas_manufactura',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_calidad_por_lote',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_calidad_producto',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_destruccion_material_x_carga',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_determinar_concentracion_quimico',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_fabricacion_libre_alergenicos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_insumos_aoac',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_iso_17025',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_iso_21469',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_logistica_producto',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_migracion_fundas',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_mip_personal',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_nfs_h1_h2',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_npma',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_patrones_trazables_baja_incertidumbre',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_tiempo_analisis',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_transporte_exclusivo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_transporte_sellado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_validaciones_reduccion_logaritmica',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_cobertura_seguro_ocupantes_vehiculos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_cobertura_seguro_vehiculos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_codigo_conducta',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_copia_hoja_seguridad_datos_msds',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_documento_aceptacion_especificaciones_ecofroz',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_documentos_habilitantes_vehiculos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_especificacion_material_empaque',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_especificaciones_fichas_tecnicas',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_ficha_tecnica_hoja_seguridad_registro_sanitario',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_fichas',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_fichas_tecnicas_y_registros_sanitarios',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_formato_informacion_contacto_emergencia',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_formato_seleccion_materia_prima',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_homologacion_auditoria_basc_ecofroz',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_homologacion_gfsi',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_ingredientes_activos_aprobados',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_licencia_unica_funcionamiento_luae',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_lista_choferes_autorizados',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_matricula_vehiculo_actualizada',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_mecanismo_discrimen',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_mecanismo_satisfaccion_cliente',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_permiso_funcionamiento',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_permiso_operacion_transporte',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_plan_continuidad_negocio',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_plan_respuesta_riesgos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_politica_inclusion_social',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_politica_prevencion_actos_acoso',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_politica_prevencion_actos_corrupcion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_politica_proteccion_ambiente',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_politica_responsabilidad_social',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_poliza_responsabilidad_civil',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_practicas_no_discriminacion_laboral',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_procedimientos_ventas_no_conformes',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_procesos_mejora_continua',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_programa_auditoria_interna',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_programa_manejo_desechos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_reglamento_interno_seguridad_salud_laboral',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_reglamento_interno_trabajo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_reporte_inspeccion_permiso_funcionamiento',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_seguimiento_medico_trabajadores',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_seguro_ocupantes_vehiculo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_sistema_calidad_iso9001',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_sistema_comunicacion_transmision_datos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_sistema_evaluacion_seleccion_proveedores',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_sistema_seguridad_logistica_transporte',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tieneweb',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tipo_instalaciones',
            field=models.CharField(blank=True, choices=[('Propias', 'Propias'), ('Compartida por varias empresas', 'Compartida por varias empresas'), ('Trabaja en residencia', 'Trabaja en residencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='trabajadores_menores_16anios',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='utiliza_transporte_propio',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='vehiculos_estan_asegurados',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='proveedor_critico',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='proveedor_revisado',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='respondio_encuesta',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='antecedentes_verificados_rep_legal',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='capacita_usuarios_prevencion_accidentes',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='conoce_proceso_pago',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='conoce_proceso_recepcion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='contesta_reclamos_administrativos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='contesta_reclamos_calidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='contrato_vigente_ecofroz',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='cumple_procedimiento_compra',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='cumple_procedimiento_compra_calidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='cumple_procedimiento_entrega',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='cumple_procedimiento_entrega_calidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='cumple_procedimiento_facturacion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='cumple_procedimiento_facturacion_calidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='cumplimiento_proceso_pago',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='ecofroz_explico_proceso_compra',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='es_atendido_bien',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='es_proveedor_maquinaria_o_equipo',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Servicio de mantenimiento de maquinaria y/o equipos', 'Servicio de mantenimiento de maquinaria y/o equipos'), ('Maquinaria y/o equipos', 'Maquinaria y/o equipos'), ('Repuestos de maquinaria y/o equipos', 'Repuestos de maquinaria y/o equipos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='especificaciones_oportunas_claras',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='giro_negocio_igual',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='hace_mantenimiento_preventivo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='hace_respaldos_periodicos_informacion_empresa',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='optimiza_uso_recursos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='prioriza_contratacion_personal_zona',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proceso_compra_agil',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_fertilizantes_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(4, 'Certificado de que esta libre de noni fenol y cloruro de benzalconio'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (5, 'Los ingredientes activos vigentes en las legislaciones de USA, Japón, Europa'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (6, 'Conocer el orígen de las materias primas'), (3, 'Análisis de metales pesados'), (7, 'No soy proveedor de fertilizantes')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_foliares_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(1, 'Registro de los productos en Agrocalidad o MAGAP'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (4, 'Conocer el orígen de las materias primas'), (5, 'No soy proveedor de FOLIARES')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_materia_organica_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(5, 'No soy proveedor de MATERIA ORGANICA'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (4, 'Conocer el orígen de las materias primas'), (3, 'Análisis físico-químico y microbiológico de la M.O. (vigencia 1 año)')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_pesticidas_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(4, 'Los ingredientes activos deben estar vigentes en las legislaciones de USA,Japón y Europa'), (5, 'No soy proveedor de pesticidas'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleado'), (1, 'Registro de los productos en Agrocalidad o Magar')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='realiza_simulacro_emergencia',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='requiere_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='subcontrata',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_activos_asegurados',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_afiliacion_empleados_iess',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_analisis_composicion_concentraciones',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_analisis_cumplimiento_fda_173310',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_aprobaciones_contacto_alimentos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_carta_garantia',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificacion_basc',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificacion_gfsi_o_bpm',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_aecpu',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_arcsa',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_auditoria_ecofroz_por_no_gfsi',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_biodegradabilidad',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_buenas_practicas_manufactura',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_calidad_por_lote',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_calidad_producto',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_destruccion_material_x_carga',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_determinar_concentracion_quimico',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_fabricacion_libre_alergenicos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_insumos_aoac',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_iso_17025',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_iso_21469',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_logistica_producto',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_migracion_fundas',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_mip_personal',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_nfs_h1_h2',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_npma',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_patrones_trazables_baja_incertidumbre',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_tiempo_analisis',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_transporte_exclusivo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_transporte_sellado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_validaciones_reduccion_logaritmica',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_cobertura_seguro_ocupantes_vehiculos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_cobertura_seguro_vehiculos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_codigo_conducta',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_copia_hoja_seguridad_datos_msds',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_documento_aceptacion_especificaciones_ecofroz',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_documentos_habilitantes_vehiculos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_especificacion_material_empaque',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_especificaciones_fichas_tecnicas',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_ficha_tecnica_hoja_seguridad_registro_sanitario',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_fichas',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_fichas_tecnicas_y_registros_sanitarios',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_formato_informacion_contacto_emergencia',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_formato_seleccion_materia_prima',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_homologacion_auditoria_basc_ecofroz',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_homologacion_gfsi',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_ingredientes_activos_aprobados',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('No lo requiero', 'No lo requiero'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_licencia_unica_funcionamiento_luae',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_lista_choferes_autorizados',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_matricula_vehiculo_actualizada',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_mecanismo_discrimen',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_mecanismo_satisfaccion_cliente',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_permiso_funcionamiento',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_permiso_operacion_transporte',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_plan_continuidad_negocio',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_plan_respuesta_riesgos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_politica_inclusion_social',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_politica_prevencion_actos_acoso',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_politica_prevencion_actos_corrupcion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_politica_proteccion_ambiente',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_politica_responsabilidad_social',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_poliza_responsabilidad_civil',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_practicas_no_discriminacion_laboral',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_procedimientos_ventas_no_conformes',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_procesos_mejora_continua',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_programa_auditoria_interna',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_programa_manejo_desechos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_reglamento_interno_seguridad_salud_laboral',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_reglamento_interno_trabajo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_reporte_inspeccion_permiso_funcionamiento',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_seguimiento_medico_trabajadores',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_seguro_ocupantes_vehiculo',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_sistema_calidad_iso9001',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_sistema_comunicacion_transmision_datos',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_sistema_evaluacion_seleccion_proveedores',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_sistema_seguridad_logistica_transporte',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tieneweb',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tipo_instalaciones',
            field=models.CharField(blank=True, choices=[('Propias', 'Propias'), ('Compartida por varias empresas', 'Compartida por varias empresas'), ('Trabaja en residencia', 'Trabaja en residencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='trabajadores_menores_16anios',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='utiliza_transporte_propio',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='vehiculos_estan_asegurados',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_encuesta',
            name='seccion',
            field=models.CharField(blank=True, choices=[(22, 'Quimicos para el caldero'), (31, 'Buenas prracticas de  responsabilidad social'), (33, 'Buenas practicas con proveedores y clientes'), (17, 'Laboratorios de Analisis'), (16, 'Catering'), (5, 'Información General'), (11, 'Control de Plagas'), (20, 'Gestores ambientales de desechos'), (23, 'Grados de grado alimenticio'), (29, 'Buenas practicas de seguridad'), (12, 'Centros de acopio'), (13, 'Quimicos de limpieza (Detergentes)'), (24, 'Transporte de contenedores'), (6, 'Existencia y Legalidad'), (19, 'Laboratorios de calibracion'), (25, 'Transporte maritimo (navieras)'), (26, 'Korex - Sleep Shipt'), (27, 'Transporte'), (32, 'Buenas practicas laborales'), (18, 'Materiales de laboratorio (insumos)'), (4, 'Veracidad de las respuestas'), (15, 'Cajas'), (14, 'Quimicos de limpieza (Desinfectantes)'), (8, 'Requisitos Persona Juridica'), (10, 'Fundas/Rollos'), (21, 'Materia Prima'), (3, 'Licitud de Fondos'), (34, 'Retroalimentacion Ecofroz'), (30, 'Buenas practicas ambientales'), (7, 'Requisitos persona Natural'), (28, 'Buenas practicas de calidad'), (9, 'Información de la relacion comercial con Ecofroz'), (2, 'Codigo de Etica'), (1, 'Fecha de elaboración')], max_length=200, null=True),
        ),
    ]
