# Generated by Django 3.0.8 on 2021-08-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0132_auto_20210825_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor_det',
            name='observaciones_etiquetas_single_calidad',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='proveedor_det',
            name='observaciones_etiquetas_single_calidad',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='estado',
            field=models.CharField(blank=True, choices=[('INACTIVO', 'INACTIVO'), ('ACTIVO', 'ACTIVO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='es_proveedor_maquinaria_o_equipo',
            field=models.CharField(blank=True, choices=[('Servicio de mantenimiento de maquinaria y/o equipos', 'Servicio de mantenimiento de maquinaria y/o equipos'), ('No', 'No'), ('Maquinaria y/o equipos', 'Maquinaria y/o equipos'), ('Repuestos de maquinaria y/o equipos', 'Repuestos de maquinaria y/o equipos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_fertilizantes_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(5, 'Los ingredientes activos vigentes en las legislaciones de USA, Japón, Europa'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (7, 'No soy proveedor de fertilizantes'), (3, 'Análisis de metales pesados'), (4, 'Certificado de que esta libre de noni fenol y cloruro de benzalconio'), (6, 'Conocer el orígen de las materias primas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_foliares_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(5, 'No soy proveedor de FOLIARES'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (4, 'Conocer el orígen de las materias primas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_materia_organica_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(1, 'Registro de los productos en Agrocalidad o MAGAP'), (3, 'Análisis físico-químico y microbiológico de la M.O. (vigencia 1 año)'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (4, 'Conocer el orígen de las materias primas'), (5, 'No soy proveedor de MATERIA ORGANICA')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_pesticidas_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (4, 'Los ingredientes activos deben estar vigentes en las legislaciones de USA,Japón y Europa'), (5, 'No soy proveedor de pesticidas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleado'), (1, 'Registro de los productos en Agrocalidad o Magar')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_biodegradabilidad',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_determinar_concentracion_quimico',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_copia_hoja_seguridad_datos_msds',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_fichas_tecnicas_y_registros_sanitarios',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_formato_informacion_contacto_emergencia',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_ingredientes_activos_aprobados',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(blank=True, choices=[('INACTIVO', 'INACTIVO'), ('ACTIVO', 'ACTIVO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='es_proveedor_maquinaria_o_equipo',
            field=models.CharField(blank=True, choices=[('Servicio de mantenimiento de maquinaria y/o equipos', 'Servicio de mantenimiento de maquinaria y/o equipos'), ('No', 'No'), ('Maquinaria y/o equipos', 'Maquinaria y/o equipos'), ('Repuestos de maquinaria y/o equipos', 'Repuestos de maquinaria y/o equipos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_fertilizantes_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(5, 'Los ingredientes activos vigentes en las legislaciones de USA, Japón, Europa'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (7, 'No soy proveedor de fertilizantes'), (3, 'Análisis de metales pesados'), (4, 'Certificado de que esta libre de noni fenol y cloruro de benzalconio'), (6, 'Conocer el orígen de las materias primas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_foliares_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(5, 'No soy proveedor de FOLIARES'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (4, 'Conocer el orígen de las materias primas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_materia_organica_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(1, 'Registro de los productos en Agrocalidad o MAGAP'), (3, 'Análisis físico-químico y microbiológico de la M.O. (vigencia 1 año)'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (4, 'Conocer el orígen de las materias primas'), (5, 'No soy proveedor de MATERIA ORGANICA')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_pesticidas_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (4, 'Los ingredientes activos deben estar vigentes en las legislaciones de USA,Japón y Europa'), (5, 'No soy proveedor de pesticidas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleado'), (1, 'Registro de los productos en Agrocalidad o Magar')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_biodegradabilidad',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_determinar_concentracion_quimico',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_copia_hoja_seguridad_datos_msds',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_fichas_tecnicas_y_registros_sanitarios',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_formato_informacion_contacto_emergencia',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_ingredientes_activos_aprobados',
            field=models.CharField(blank=True, choices=[('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('Documento Físico', 'Documento Físico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_encuesta',
            name='seccion',
            field=models.CharField(blank=True, choices=[(15, 'Cajas'), (10, 'Fundas/Rollos'), (13, 'Quimicos de limpieza (Detergentes)'), (11, 'Control de Plagas'), (27, 'Transporte'), (4, 'Veracidad de las respuestas'), (2, 'Codigo de Etica'), (22, 'Quimicos para el caldero'), (14, 'Quimicos de limpieza (Desinfectantes)'), (6, 'Existencia y Legalidad'), (20, 'Gestores ambientales de desechos'), (12, 'Centros de acopio'), (25, 'Transporte maritimo (navieras)'), (28, 'Buenas practicas de calidad'), (29, 'Buenas practicas de seguridad'), (19, 'Laboratorios de calibracion'), (23, 'Grados de grado alimenticio'), (30, 'Buenas practicas ambientales'), (17, 'Laboratorios de Analisis'), (21, 'Materia Prima'), (3, 'Licitud de Fondos'), (9, 'Información de la relacion comercial con Ecofroz'), (8, 'Requisitos Persona Juridica'), (32, 'Buenas practicas laborales'), (18, 'Materiales de laboratorio (insumos)'), (24, 'Transporte de contenedores'), (26, 'Korex - Sleep Shipt'), (7, 'Requisitos persona Natural'), (16, 'Catering'), (31, 'Buenas prracticas de  responsabilidad social'), (34, 'Retroalimentacion Ecofroz'), (1, 'Fecha de elaboración'), (5, 'Información General'), (33, 'Buenas practicas con proveedores y clientes')], max_length=200, null=True),
        ),
    ]
