# Generated by Django 3.0.8 on 2021-09-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0135_auto_20210826_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_prove',
            name='es_agro_fer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='es_agro_fol',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='es_agro_mao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='es_agro_pes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='es_agro_sem',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='es_ficha_fer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='es_ficha_fol',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='es_ficha_mao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='es_ficha_pes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='es_ficha_sem',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='es_msds_fer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='es_msds_fol',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='es_msds_mao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='es_msds_pes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='es_msds_sem',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos_prove',
            name='observaciones_docs_agrocalidad',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='documentos_prove',
            name='marca_cal',
            field=models.CharField(blank=True, choices=[('CORRECTA', 'CORECTA'), ('INCORRECTA', 'INCORRECTA'), ('DESACTUALIZADA', 'DESACTUALIZADA')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='es_proveedor_maquinaria_o_equipo',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Maquinaria y/o equipos', 'Maquinaria y/o equipos'), ('Servicio de mantenimiento de maquinaria y/o equipos', 'Servicio de mantenimiento de maquinaria y/o equipos'), ('Repuestos de maquinaria y/o equipos', 'Repuestos de maquinaria y/o equipos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_fertilizantes_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(4, 'Certificado de que esta libre de noni fenol y cloruro de benzalconio'), (6, 'Conocer el orígen de las materias primas'), (7, 'No soy proveedor de fertilizantes'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (5, 'Los ingredientes activos vigentes en las legislaciones de USA, Japón, Europa'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (3, 'Análisis de metales pesados')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_foliares_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(5, 'No soy proveedor de FOLIARES'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (4, 'Conocer el orígen de las materias primas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_materia_organica_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(1, 'Registro de los productos en Agrocalidad o MAGAP'), (4, 'Conocer el orígen de las materias primas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (3, 'Análisis físico-químico y microbiológico de la M.O. (vigencia 1 año)'), (5, 'No soy proveedor de MATERIA ORGANICA')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='proveedor_pesticidas_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleado'), (4, 'Los ingredientes activos deben estar vigentes en las legislaciones de USA,Japón y Europa'), (1, 'Registro de los productos en Agrocalidad o Magar'), (5, 'No soy proveedor de pesticidas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('Documento Físico', 'Documento Físico'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_biodegradabilidad',
            field=models.CharField(blank=True, choices=[('Documento Físico', 'Documento Físico'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_certificado_determinar_concentracion_quimico',
            field=models.CharField(blank=True, choices=[('Documento Físico', 'Documento Físico'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_copia_hoja_seguridad_datos_msds',
            field=models.CharField(blank=True, choices=[('Documento Físico', 'Documento Físico'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_fichas_tecnicas_y_registros_sanitarios',
            field=models.CharField(blank=True, choices=[('Documento Físico', 'Documento Físico'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_formato_informacion_contacto_emergencia',
            field=models.CharField(blank=True, choices=[('Documento Físico', 'Documento Físico'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_det',
            name='tiene_ingredientes_activos_aprobados',
            field=models.CharField(blank=True, choices=[('Documento Físico', 'Documento Físico'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='es_proveedor_maquinaria_o_equipo',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Maquinaria y/o equipos', 'Maquinaria y/o equipos'), ('Servicio de mantenimiento de maquinaria y/o equipos', 'Servicio de mantenimiento de maquinaria y/o equipos'), ('Repuestos de maquinaria y/o equipos', 'Repuestos de maquinaria y/o equipos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_fertilizantes_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(4, 'Certificado de que esta libre de noni fenol y cloruro de benzalconio'), (6, 'Conocer el orígen de las materias primas'), (7, 'No soy proveedor de fertilizantes'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (5, 'Los ingredientes activos vigentes en las legislaciones de USA, Japón, Europa'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (3, 'Análisis de metales pesados')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_foliares_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(5, 'No soy proveedor de FOLIARES'), (3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (1, 'Registro de los productos en Agrocalidad o MAGAP'), (4, 'Conocer el orígen de las materias primas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_materia_organica_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(1, 'Registro de los productos en Agrocalidad o MAGAP'), (4, 'Conocer el orígen de las materias primas'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleados'), (3, 'Análisis físico-químico y microbiológico de la M.O. (vigencia 1 año)'), (5, 'No soy proveedor de MATERIA ORGANICA')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='proveedor_pesticidas_requisitos_indispensables',
            field=models.CharField(blank=True, choices=[(3, 'Análisis producto libre de noni fenol y cloruro de banzalconio con límite de 0.01 ppm de c/compuesto'), (2, 'Fichas técnicas y hojas de seguridad de los productos empleado'), (4, 'Los ingredientes activos deben estar vigentes en las legislaciones de USA,Japón y Europa'), (1, 'Registro de los productos en Agrocalidad o Magar'), (5, 'No soy proveedor de pesticidas')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_ambiental',
            field=models.CharField(blank=True, choices=[('Documento Físico', 'Documento Físico'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_biodegradabilidad',
            field=models.CharField(blank=True, choices=[('Documento Físico', 'Documento Físico'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_certificado_determinar_concentracion_quimico',
            field=models.CharField(blank=True, choices=[('Documento Físico', 'Documento Físico'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_copia_hoja_seguridad_datos_msds',
            field=models.CharField(blank=True, choices=[('Documento Físico', 'Documento Físico'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_fichas_tecnicas_y_registros_sanitarios',
            field=models.CharField(blank=True, choices=[('Documento Físico', 'Documento Físico'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_formato_informacion_contacto_emergencia',
            field=models.CharField(blank=True, choices=[('Documento Físico', 'Documento Físico'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_det',
            name='tiene_ingredientes_activos_aprobados',
            field=models.CharField(blank=True, choices=[('Documento Físico', 'Documento Físico'), ('Por correo electrónico', 'Por correo electrónico'), ('No lo requiero', 'No lo requiero'), ('No lo tengo', 'No lo tengo'), ('Adjunto a este formulario', 'Adjunto a este formulario')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_encuesta',
            name='seccion',
            field=models.CharField(blank=True, choices=[(27, 'Transporte'), (17, 'Laboratorios de Analisis'), (3, 'Licitud de Fondos'), (23, 'Grados de grado alimenticio'), (10, 'Fundas/Rollos'), (25, 'Transporte maritimo (navieras)'), (19, 'Laboratorios de calibracion'), (4, 'Veracidad de las respuestas'), (29, 'Buenas practicas de seguridad'), (9, 'Información de la relacion comercial con Ecofroz'), (16, 'Catering'), (24, 'Transporte de contenedores'), (7, 'Requisitos persona Natural'), (6, 'Existencia y Legalidad'), (22, 'Quimicos para el caldero'), (34, 'Retroalimentacion Ecofroz'), (28, 'Buenas practicas de calidad'), (33, 'Buenas practicas con proveedores y clientes'), (5, 'Información General'), (21, 'Materia Prima'), (32, 'Buenas practicas laborales'), (12, 'Centros de acopio'), (18, 'Materiales de laboratorio (insumos)'), (11, 'Control de Plagas'), (20, 'Gestores ambientales de desechos'), (13, 'Quimicos de limpieza (Detergentes)'), (8, 'Requisitos Persona Juridica'), (14, 'Quimicos de limpieza (Desinfectantes)'), (15, 'Cajas'), (1, 'Fecha de elaboración'), (26, 'Korex - Sleep Shipt'), (31, 'Buenas prracticas de  responsabilidad social'), (2, 'Codigo de Etica'), (30, 'Buenas practicas ambientales')], max_length=200, null=True),
        ),
    ]
