# Generated by Django 3.0 on 2020-06-05 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion_matriz', models.CharField(blank=True, max_length=200, null=True)),
                ('horario_trabajo', models.CharField(blank=True, max_length=200, null=True)),
                ('representante_legal', models.CharField(blank=True, max_length=100, null=True)),
                ('ruc', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre_contacto_ecofroz', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('calificacion', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=20, null=True)),
                ('categorizacion', models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=20, null=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
                ('fecha_modifica_txt', models.CharField(blank=True, max_length=8, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_registro_txt', models.CharField(blank=True, max_length=8, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'proveedoresnew"."proveedor',
                'ordering': ['-fecha_modifica'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='proveedor_encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'proveedoresnew"."proveedor_encuesta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='proveedor_respuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(blank=True, max_length=2000, null=True)),
                ('encuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proveedoresnew.proveedor_encuesta')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proveedoresnew.proveedor')),
            ],
            options={
                'db_table': 'proveedoresnew"."proveedor_respuestas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='proveedor_categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('encuesta', models.ManyToManyField(to='proveedoresnew.proveedor_encuesta')),
            ],
            options={
                'db_table': 'proveedoresnew"."proveedor_categoria',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proveedoresnew.proveedor_categoria'),
        ),
    ]
