# Generated by Django 3.0 on 2020-06-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedoresnew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='categorizacion',
            field=models.CharField(blank=True, choices=[('INACTIVO', 'INACTIVO'), ('ACTIVO', 'ACTIVO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(blank=True, choices=[('INACTIVO', 'INACTIVO'), ('ACTIVO', 'ACTIVO')], max_length=20, null=True),
        ),
    ]
