# Generated by Django 3.0 on 2020-02-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_estado', 'Cambio de Estado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_custodio', 'Cambio de Custodio')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_usuario_modifica',
            field=models.CharField(blank=True, choices=[('eclavijo', 'Eduardo Clavijo'), ('jcvillamarin', 'Juan Carlos Villamrín'), ('pborja', 'Pablo Borja'), ('dmencias', 'David Mencías')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_usuario_registra',
            field=models.CharField(blank=True, choices=[('eclavijo', 'Eduardo Clavijo'), ('jcvillamarin', 'Juan Carlos Villamrín'), ('pborja', 'Pablo Borja'), ('dmencias', 'David Mencías')], max_length=50, null=True),
        ),
    ]
