# Generated by Django 3.0 on 2020-02-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_auto_20200218_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_estado', 'Cambio de Estado'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_custodio', 'Cambio de Custodio'), ('cambio_ubicacion', 'Cambio de Ubicación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_usuario_modifica',
            field=models.CharField(blank=True, choices=[('dmencias', 'David Mencías'), ('pborja', 'Pablo Borja'), ('jcvillamarin', 'Juan Carlos Villamrín'), ('eclavijo', 'Eduardo Clavijo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_usuario_registra',
            field=models.CharField(blank=True, choices=[('dmencias', 'David Mencías'), ('pborja', 'Pablo Borja'), ('jcvillamarin', 'Juan Carlos Villamrín'), ('eclavijo', 'Eduardo Clavijo')], max_length=50, null=True),
        ),
    ]
