# Generated by Django 3.0 on 2020-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_auto_20200218_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('DADO DE BAJA', 'DADO DE BAJA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activo_nomenclatura',
            name='nomenclatura_estado',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='activos_temp_excel',
            name='desc_activo_asegurado',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_asegurado',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_estado', 'Cambio de Estado'), ('cambio_custodio', 'Cambio de Custodio'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('actualiza_asegurado', 'Cambio valor Asegurado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_usuario_modifica',
            field=models.CharField(blank=True, choices=[('jcvillamarin', 'Juan Carlos Villamrín'), ('eclavijo', 'Eduardo Clavijo'), ('dmencias', 'David Mencías'), ('pborja', 'Pablo Borja')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_usuario_registra',
            field=models.CharField(blank=True, choices=[('jcvillamarin', 'Juan Carlos Villamrín'), ('eclavijo', 'Eduardo Clavijo'), ('dmencias', 'David Mencías'), ('pborja', 'Pablo Borja')], max_length=50, null=True),
        ),
    ]
