# Generated by Django 3.0 on 2020-03-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_auto_20200302_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_custodio', 'Cambio de Custodio'), ('cambio_estado', 'Cambio de Estado'), ('cambio_ubicacion', 'Cambio de Ubicación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_usuario_modifica',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_usuario_registra',
            field=models.CharField(blank=True, choices=[('pborja', 'Pablo Borja'), ('jcvillamarin', 'Juan Carlos Villamrín'), ('eclavijo', 'Eduardo Clavijo'), ('dmencias', 'David Mencías')], max_length=50, null=True),
        ),
    ]
