# Generated by Django 3.0 on 2020-03-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_auto_20200303_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_custodio', 'Cambio de Custodio'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_estado', 'Cambio de Estado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_usuario_registra',
            field=models.CharField(blank=True, choices=[('eclavijo', 'Eduardo Clavijo'), ('jcvillamarin', 'Juan Carlos Villamrín'), ('pborja', 'Pablo Borja'), ('dmencias', 'David Mencías')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='salida_activos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('retorno', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True)),
                ('detalle_activo', models.CharField(blank=True, max_length=500, null=True)),
                ('sale_por', models.CharField(blank=True, choices=[('Préstamo entre ubicaciones propias', 'Préstamo entre ubicaciones propias'), ('Salida por Reparacion', 'Salida por Reparacion')], max_length=200, null=True)),
                ('num_orden_trabajo', models.IntegerField(blank=True, null=True, unique=True)),
                ('solicitado_por', models.CharField(blank=True, choices=[('Préstamo entre ubicaciones propias', 'Préstamo entre ubicaciones propias'), ('Salida por Reparacion', 'Salida por Reparacion')], max_length=200, null=True)),
                ('motivo', models.CharField(blank=True, max_length=500, null=True)),
                ('empresa_mantenimiento', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_estimada_retorno', models.DateField(null=True)),
                ('hora_salida', models.CharField(blank=True, max_length=20, null=True)),
                ('pers_autoriza_seguridad', models.CharField(blank=True, choices=[('Galo Jaramillo', 'Galo Jaramillo'), ('Fernando Ortiz', 'Fernando Ortiz')], max_length=200, null=True)),
                ('persona_retira', models.CharField(blank=True, max_length=200, null=True)),
                ('guardia_control', models.CharField(blank=True, max_length=200, null=True)),
                ('activo_num_serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activos.detalle_desc_activo')),
                ('activo_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_tipo')),
            ],
            options={
                'db_table': 'activos"."salida_activos',
                'managed': True,
            },
        ),
    ]
