# Generated by Django 3.0 on 2020-03-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_auto_20200303_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_estado', 'Cambio de Estado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_custodio', 'Cambio de Custodio')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_usuario_registra',
            field=models.CharField(blank=True, choices=[('pborja', 'Pablo Borja'), ('eclavijo', 'Eduardo Clavijo'), ('dmencias', 'David Mencías'), ('jcvillamarin', 'Juan Carlos Villamrín')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.CharField(blank=True, choices=[('Salida por Reparacion', 'Salida por Reparacion'), ('Préstamo entre ubicaciones propias', 'Préstamo entre ubicaciones propias')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='solicitado_por',
            field=models.CharField(blank=True, choices=[('Salida por Reparacion', 'Salida por Reparacion'), ('Préstamo entre ubicaciones propias', 'Préstamo entre ubicaciones propias')], max_length=200, null=True),
        ),
    ]
