# Generated by Django 3.0 on 2020-03-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_auto_20200304_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo_tipo',
            name='tipo_grupo',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_grupo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_custodio', 'Cambio de Custodio'), ('cambio_estado', 'Cambio de Estado'), ('actualiza_asegurado', 'Cambio valor Asegurado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='pers_autoriza_seguridad',
            field=models.CharField(blank=True, choices=[('Galo Jaramillo', 'Galo Jaramillo'), ('Fernando Ortiz', 'Fernando Ortiz')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.CharField(blank=True, choices=[('Salida por Reparacion', 'Salida por Reparacion'), ('Préstamo entre ubicaciones propias', 'Préstamo entre ubicaciones propias')], max_length=200, null=True),
        ),
    ]
