# Generated by Django 3.0 on 2020-04-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0015_auto_20200311_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_ubicacion', 'Cambio de Ubicación'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_custodio', 'Cambio de Custodio'), ('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_estado', 'Cambio de Estado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='estado',
            field=models.CharField(blank=True, choices=[(2, 'Retornó'), (1, 'En Reparación Externa')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='pers_autoriza_seguridad',
            field=models.CharField(blank=True, choices=[('Fernando Ortiz', 'Fernando Ortiz'), ('Galo Jaramillo', 'Galo Jaramillo')], max_length=200, null=True),
        ),
    ]
