# Generated by Django 3.0 on 2020-04-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0016_auto_20200403_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo_nomenclatura',
            name='nomenclatura_estado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='activos_temp_excel',
            name='desc_activo_asegurado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_asegurado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_estado', 'Cambio de Estado'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_custodio', 'Cambio de Custodio'), ('cambio_caracteristicas', 'Cambio de Caracteristicas')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='estado',
            field=models.CharField(blank=True, choices=[(1, 'En Reparación Externa'), (2, 'Retornó')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='retorno',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
    ]
