# Generated by Django 3.0 on 2020-04-21 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0017_auto_20200420_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='pestanias_seguros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pestania_nombre', models.CharField(max_length=50, null=True)),
                ('pestania_estado', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'activos"."pestanias_seguros',
                'ordering': ['pestania_nombre'],
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_custodio', 'Cambio de Custodio'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_estado', 'Cambio de Estado'), ('cambio_caracteristicas', 'Cambio de Caracteristicas')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='estado',
            field=models.CharField(blank=True, default='TRANSITO', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.CharField(blank=True, choices=[('Préstamo entre ubicaciones propias', 'Préstamo entre ubicaciones propias'), ('Salida por Reparacion', 'Salida por Reparacion')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='desc_activo',
            name='pestanias_seguros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activos.pestanias_seguros'),
        ),
    ]
