# Generated by Django 3.0 on 2020-04-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0018_auto_20200421_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='desc_activo',
            name='activo_valor_compra',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_estado', 'Cambio de Estado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_custodio', 'Cambio de Custodio'), ('actualiza_asegurado', 'Cambio valor Asegurado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='pers_autoriza_seguridad',
            field=models.CharField(blank=True, choices=[('Galo Jaramillo', 'Galo Jaramillo'), ('Fernando Ortiz', 'Fernando Ortiz')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.CharField(blank=True, choices=[('Salida por Reparacion', 'Salida por Reparacion'), ('Préstamo entre ubicaciones propias', 'Préstamo entre ubicaciones propias')], max_length=200, null=True),
        ),
    ]
