# Generated by Django 3.0 on 2020-06-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0029_auto_20200521_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida_activos',
            name='activo_codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activos.desc_activo'),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('MANTENIMIENTO', 'MANTENIMIENTO'), ('DADO DE BAJA', 'DADO DE BAJA'), ('ACTIVO', 'ACTIVO')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_custodio', 'Cambio de Custodio'), ('cambio_estado', 'Cambio de Estado')], max_length=50, null=True),
        ),
    ]
