# Generated by Django 3.0 on 2020-07-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0041_auto_20200701_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo_nomenclatura',
            name='nomenclatura_estado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='activos_temp_excel',
            name='desc_activo_asegurado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('MN', 'MANTENIMIENTO'), ('RE', 'REPARACIÓN EXTERNA'), ('AC', 'ACTIVO'), ('DB', 'DADO DE BAJA')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='incendios',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('4', 'SIN SEGURO'), ('3', 'INCENDIO'), ('6', 'EQUIPO ELECTRONICO'), ('1', 'ROTURA DE MAQUINARIA'), ('5', 'VEHICULOS'), ('2', 'EQUIPO Y MAQUINARIA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_asegurado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_estado', 'Cambio de Estado'), ('cambio_custodio', 'Cambio de Custodio'), ('cambio_ubicacion', 'Cambio de Ubicación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='fecha_estimada_retorno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='pers_autoriza_seguridad',
            field=models.CharField(blank=True, choices=[('Galo Jaramillo', 'Galo Jaramillo'), ('Fernando Ortiz', 'Fernando Ortiz')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='retorno',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('PABLO BORJA', 'PABLO BORJA'), ('DAVID  MENCIAS', 'DAVID MENCIAS'), ('JUAN VILLAMARIN', 'JUAN VILLAMARIN'), ('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
