# Generated by Django 3.0 on 2020-09-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0053_auto_20200916_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='desc_activo',
            name='num_pedido',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('MN', 'MANTENIMIENTO'), ('VE', 'VENDIDO'), ('DB', 'DADO DE BAJA'), ('DO', 'DONADO'), ('AC', 'ACTIVO'), ('RE', 'REPARACIÓN EXTERNA')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('2', 'EQUIPO Y MAQUINARIA'), ('6', 'EQUIPO ELECTRONICO'), ('1', 'ROTURA DE MAQUINARIA'), ('5', 'VEHICULOS'), ('4', 'SIN SEGURO'), ('3', 'INCENDIO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_custodio', 'Cambio de Custodio'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_fecha', 'Cambio de Fecha'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_estado', 'Cambio de Estado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='pers_autoriza_seguridad',
            field=models.CharField(blank=True, choices=[('Fernando Ortiz', 'Fernando Ortiz'), ('Galo Jaramillo', 'Galo Jaramillo')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('PABLO BORJA', 'PABLO BORJA'), ('JUAN VILLAMARIN', 'JUAN VILLAMARIN'), ('DAVID  MENCIAS', 'DAVID MENCIAS'), ('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
