# Generated by Django 3.0 on 2021-01-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0058_auto_20210119_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_internos_temp',
            name='marca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movimientos_internos_temp',
            name='serie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movimientos_internos_temp',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activo_nomenclatura',
            name='nomenclatura_estado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='activos_temp_excel',
            name='desc_activo_asegurado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('DO', 'DONADO'), ('MN', 'MANTENIMIENTO'), ('AC', 'ACTIVO'), ('VE', 'VENDIDO'), ('RE', 'REPARACIÓN EXTERNA'), ('DB', 'DADO DE BAJA')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='incendios',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('3', 'INCENDIO'), ('1', 'ROTURA DE MAQUINARIA'), ('2', 'EQUIPO Y MAQUINARIA'), ('6', 'EQUIPO ELECTRONICO'), ('5', 'VEHICULOS'), ('4', 'SIN SEGURO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_asegurado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_estado', 'Cambio de Estado'), ('cambio_custodio', 'Cambio de Custodio'), ('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_fecha', 'Cambio de Fecha'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_ubicacion', 'Cambio de Ubicación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='pers_autoriza_seguridad',
            field=models.CharField(blank=True, choices=[('Galo Jaramillo', 'Galo Jaramillo'), ('Fernando Ortiz', 'Fernando Ortiz')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='retorno',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('JUAN VILLAMARIN', 'JUAN VILLAMARIN'), ('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO'), ('DAVID  MENCIAS', 'DAVID MENCIAS'), ('PABLO BORJA', 'PABLO BORJA')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
