# Generated by Django 3.0 on 2021-02-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0072_auto_20210209_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo_nomenclatura',
            name='nomenclatura_estado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='activos_temp_excel',
            name='desc_activo_asegurado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('VE', 'VENDIDO'), ('AC', 'ACTIVO'), ('MN', 'MANTENIMIENTO'), ('RE', 'REPARACIÓN EXTERNA'), ('DO', 'DONADO'), ('DB', 'DADO DE BAJA')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='grabado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='incendios',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('3', 'INCENDIO'), ('5', 'VEHICULOS'), ('4', 'SIN SEGURO'), ('1', 'ROTURA DE MAQUINARIA'), ('2', 'EQUIPO Y MAQUINARIA'), ('6', 'EQUIPO ELECTRONICO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_asegurado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_custodio', 'Cambio de Custodio'), ('cambio_fecha', 'Cambio de Fecha'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_estado', 'Cambio de Estado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historial_movimientos_internos',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_depar'),
        ),
        migrations.AlterField(
            model_name='historial_movimientos_internos',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_areas'),
        ),
        migrations.AlterField(
            model_name='historial_movimientos_internos',
            name='subsector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_subsector'),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='retorno',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.IntegerField(blank=True, choices=[(4, 'Cambio de Ubicación Geográfica'), (2, 'Dado de Baja'), (1, 'Reparación'), (3, 'Venta')], null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('PABLO BORJA', 'PABLO BORJA'), ('DAVID  MENCIAS', 'DAVID MENCIAS'), ('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO'), ('JUAN VILLAMARIN', 'JUAN VILLAMARIN')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
