# Generated by Django 3.0 on 2021-02-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0074_auto_20210209_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('AC', 'ACTIVO'), ('MN', 'MANTENIMIENTO'), ('RE', 'REPARACIÓN EXTERNA'), ('VE', 'VENDIDO'), ('DO', 'DONADO'), ('DB', 'DADO DE BAJA')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('1', 'ROTURA DE MAQUINARIA'), ('4', 'SIN SEGURO'), ('5', 'VEHICULOS'), ('6', 'EQUIPO ELECTRONICO'), ('2', 'EQUIPO Y MAQUINARIA'), ('3', 'INCENDIO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_custodio', 'Cambio de Custodio'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_fecha', 'Cambio de Fecha'), ('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_estado', 'Cambio de Estado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historial_movimientos_internos',
            name='subsector',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.IntegerField(blank=True, choices=[(1, 'Reparación'), (4, 'Cambio de Ubicación Geográfica'), (2, 'Dado de Baja'), (3, 'Venta')], null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('JUAN VILLAMARIN', 'JUAN VILLAMARIN'), ('DAVID  MENCIAS', 'DAVID MENCIAS'), ('PABLO BORJA', 'PABLO BORJA'), ('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
