# Generated by Django 3.0 on 2021-03-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0079_auto_20210312_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='no_encontrados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=150, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('sector', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=2000, null=True)),
                ('grabado', models.BooleanField(blank=True, null=True)),
                ('usuario_registra', models.CharField(blank=True, max_length=100, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=2000, null=True)),
                ('gestionado', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activos"."no_encontrados',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('DB', 'DADO DE BAJA'), ('AC', 'ACTIVO'), ('RE', 'REPARACIÓN EXTERNA'), ('VE', 'VENDIDO'), ('MN', 'MANTENIMIENTO'), ('DO', 'DONADO')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('3', 'INCENDIO'), ('6', 'EQUIPO ELECTRONICO'), ('4', 'SIN SEGURO'), ('2', 'EQUIPO Y MAQUINARIA'), ('1', 'ROTURA DE MAQUINARIA'), ('5', 'VEHICULOS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_custodio', 'Cambio de Custodio'), ('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_fecha', 'Cambio de Fecha'), ('cambio_estado', 'Cambio de Estado'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_ubicacion', 'Cambio de Ubicación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.IntegerField(blank=True, choices=[(2, 'Dado de Baja'), (1, 'Reparación'), (4, 'Cambio de Ubicación Geográfica'), (3, 'Venta')], null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('DAVID  MENCIAS', 'DAVID MENCIAS'), ('PABLO BORJA', 'PABLO BORJA'), ('JUAN VILLAMARIN', 'JUAN VILLAMARIN'), ('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
