# Generated by Django 3.0 on 2021-03-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0083_auto_20210319_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_movimientos_internos',
            name='usuario_retira',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('RE', 'REPARACIÓN EXTERNA'), ('DB', 'DADO DE BAJA'), ('DO', 'DONADO'), ('VE', 'VENDIDO'), ('AC', 'ACTIVO'), ('MN', 'MANTENIMIENTO')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('3', 'INCENDIO'), ('5', 'VEHICULOS'), ('1', 'ROTURA DE MAQUINARIA'), ('4', 'SIN SEGURO'), ('2', 'EQUIPO Y MAQUINARIA'), ('6', 'EQUIPO ELECTRONICO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_estado', 'Cambio de Estado'), ('cambio_fecha', 'Cambio de Fecha'), ('cambio_custodio', 'Cambio de Custodio'), ('cambio_caracteristicas', 'Cambio de Caracteristicas')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.IntegerField(blank=True, choices=[(3, 'Venta'), (2, 'Dado de Baja'), (1, 'Reparación'), (4, 'Cambio de Ubicación Geográfica')], null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('PABLO BORJA', 'PABLO BORJA'), ('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO'), ('DAVID  MENCIAS', 'DAVID MENCIAS'), ('JUAN VILLAMARIN', 'JUAN VILLAMARIN')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
