# Generated by Django 3.0.7 on 2021-03-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0087_auto_20210326_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida_activos',
            name='ubica_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salida_activos',
            name='ubica_depar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('VE', 'VENDIDO'), ('RE', 'REPARACIÓN EXTERNA'), ('DB', 'DADO DE BAJA'), ('AC', 'ACTIVO'), ('DO', 'DONADO'), ('MN', 'MANTENIMIENTO')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('2', 'EQUIPO Y MAQUINARIA'), ('6', 'EQUIPO ELECTRONICO'), ('4', 'SIN SEGURO'), ('3', 'INCENDIO'), ('5', 'VEHICULOS'), ('1', 'ROTURA DE MAQUINARIA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_custodio', 'Cambio de Custodio'), ('cambio_fecha', 'Cambio de Fecha'), ('cambio_estado', 'Cambio de Estado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('actualiza_asegurado', 'Cambio valor Asegurado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.IntegerField(blank=True, choices=[(4, 'Cambio de Ubicación Geográfica'), (3, 'Venta'), (2, 'Dado de Baja'), (1, 'Reparación')], null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO'), ('PABLO BORJA', 'PABLO BORJA'), ('JUAN VILLAMARIN', 'JUAN VILLAMARIN'), ('DAVID  MENCIAS', 'DAVID MENCIAS')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
