# Generated by Django 3.0 on 2021-04-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0089_auto_20210401_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida_activos',
            name='fecha_efectiva_retorno',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salida_activos',
            name='fecha_movimiento',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activo_nomenclatura',
            name='nomenclatura_estado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='activos_temp_excel',
            name='desc_activo_asegurado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('AC', 'ACTIVO'), ('DB', 'DADO DE BAJA'), ('RE', 'REPARACIÓN EXTERNA'), ('DO', 'DONADO'), ('MN', 'MANTENIMIENTO'), ('VE', 'VENDIDO')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='grabado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='incendios',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('4', 'SIN SEGURO'), ('6', 'EQUIPO ELECTRONICO'), ('1', 'ROTURA DE MAQUINARIA'), ('3', 'INCENDIO'), ('5', 'VEHICULOS'), ('2', 'EQUIPO Y MAQUINARIA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_asegurado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_fecha', 'Cambio de Fecha'), ('cambio_custodio', 'Cambio de Custodio'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_estado', 'Cambio de Estado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_caracteristicas', 'Cambio de Caracteristicas')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='retorno',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.IntegerField(blank=True, choices=[(4, 'Cambio de Ubicación (Haciendas / Machachi)'), (1, 'Reparación'), (2, 'Dado de Baja'), (3, 'Venta')], null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('PABLO BORJA', 'PABLO BORJA'), ('DAVID  MENCIAS', 'DAVID MENCIAS'), ('JUAN VILLAMARIN', 'JUAN VILLAMARIN'), ('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
