# Generated by Django 3.0.7 on 2021-04-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0091_auto_20210420_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('MN', 'MANTENIMIENTO'), ('DO', 'DONADO'), ('VE', 'VENDIDO'), ('RE', 'REPARACIÓN EXTERNA'), ('DB', 'DADO DE BAJA'), ('AC', 'ACTIVO')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('1', 'ROTURA DE MAQUINARIA'), ('6', 'EQUIPO ELECTRONICO'), ('3', 'INCENDIO'), ('4', 'SIN SEGURO'), ('5', 'VEHICULOS'), ('2', 'EQUIPO Y MAQUINARIA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_estado', 'Cambio de Estado'), ('cambio_custodio', 'Cambio de Custodio'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_fecha', 'Cambio de Fecha')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historial_movimientos_internos',
            name='nuevo_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='depar_nueva', to='activos.activo_depar'),
        ),
        migrations.AlterField(
            model_name='historial_movimientos_internos',
            name='nuevo_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='area_nueva', to='activos.activo_areas'),
        ),
        migrations.AlterField(
            model_name='historial_movimientos_internos',
            name='nuevo_ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ubica_nueva', to='activos.activo_ubica'),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.IntegerField(blank=True, choices=[(3, 'Venta'), (2, 'Dado de Baja'), (4, 'Cambio de Ubicación (Haciendas / Machachi)'), (1, 'Reparación')], null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('DAVID  MENCIAS', 'DAVID MENCIAS'), ('PABLO BORJA', 'PABLO BORJA'), ('JUAN VILLAMARIN', 'JUAN VILLAMARIN'), ('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
