# Generated by Django 3.0.8 on 2021-08-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0095_auto_20210812_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_desc_activo',
            name='fecha_baja_dona_vende',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalle_desc_activo',
            name='usuario_realiza_baja_dona_vende',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('RE', 'REPARACIÓN EXTERNA'), ('AC', 'ACTIVO'), ('MN', 'MANTENIMIENTO'), ('DO', 'DONADO'), ('DB', 'DADO DE BAJA'), ('VE', 'VENDIDO')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='grabado',
            field=models.CharField(blank=True, choices=[('GRABADO', 'GRABADO'), ('ETIQUETA', 'ETIQUETA'), ('NO', 'NO')], default='NO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('4', 'SIN SEGURO'), ('2', 'EQUIPO Y MAQUINARIA'), ('3', 'INCENDIO'), ('1', 'ROTURA DE MAQUINARIA'), ('5', 'VEHICULOS'), ('6', 'EQUIPO ELECTRONICO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_fecha', 'Cambio de Fecha'), ('cambio_estado', 'Cambio de Estado'), ('cambio_custodio', 'Cambio de Custodio')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.IntegerField(blank=True, choices=[(3, 'Venta'), (4, 'Cambio de Ubicación (Haciendas / Machachi)'), (1, 'Reparación'), (2, 'Dado de Baja')], null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('JUAN VILLAMARIN', 'JUAN VILLAMARIN'), ('DAVID  MENCIAS', 'DAVID MENCIAS'), ('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO'), ('PABLO BORJA', 'PABLO BORJA')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
