# Generated by Django 3.0.8 on 2021-08-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0096_auto_20210819_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_desc_activo',
            name='notas_baja_dona_vende',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('RE', 'REPARACIÓN EXTERNA'), ('AC', 'ACTIVO'), ('MN', 'MANTENIMIENTO'), ('DO', 'DONADO'), ('VE', 'VENDIDO'), ('DB', 'DADO DE BAJA')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='grabado',
            field=models.CharField(blank=True, choices=[('ETIQUETA', 'ETIQUETA'), ('NO', 'NO'), ('GRABADO', 'GRABADO')], default='NO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('4', 'SIN SEGURO'), ('2', 'EQUIPO Y MAQUINARIA'), ('5', 'VEHICULOS'), ('1', 'ROTURA DE MAQUINARIA'), ('6', 'EQUIPO ELECTRONICO'), ('3', 'INCENDIO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_estado', 'Cambio de Estado'), ('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_fecha', 'Cambio de Fecha'), ('cambio_custodio', 'Cambio de Custodio'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_ubicacion', 'Cambio de Ubicación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.IntegerField(blank=True, choices=[(2, 'Dado de Baja'), (3, 'Venta'), (1, 'Reparación'), (4, 'Cambio de Ubicación (Haciendas / Machachi)')], null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('PABLO BORJA', 'PABLO BORJA'), ('DAVID  MENCIAS', 'DAVID MENCIAS'), ('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO'), ('JUAN VILLAMARIN', 'JUAN VILLAMARIN')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
