# Generated by Django 3.0.8 on 2021-09-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0097_auto_20210824_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo_nomenclatura',
            name='nomenclatura_estado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='activos_temp_excel',
            name='desc_activo_asegurado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('DO', 'DONADO'), ('VE', 'VENDIDO'), ('RE', 'REPARACIÓN EXTERNA'), ('MN', 'MANTENIMIENTO'), ('AC', 'ACTIVO'), ('DB', 'DADO DE BAJA')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='grabado',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('ETIQUETA', 'ETIQUETA'), ('GRABADO', 'GRABADO')], default='NO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='incendios',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('1', 'ROTURA DE MAQUINARIA'), ('5', 'VEHICULOS'), ('4', 'SIN SEGURO'), ('6', 'EQUIPO ELECTRONICO'), ('3', 'INCENDIO'), ('2', 'EQUIPO Y MAQUINARIA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_asegurado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_estado_identifica', 'Cambio de Estado Identificación Grabado/Etiquetado'), ('cambio_fecha', 'Cambio de Fecha'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_estado', 'Cambio de Estado'), ('cambio_custodio', 'Cambio de Custodio')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='retorno',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.IntegerField(blank=True, choices=[(1, 'Reparación'), (2, 'Dado de Baja'), (3, 'Venta'), (4, 'Cambio de Ubicación (Haciendas / Machachi)')], null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('DAVID  MENCIAS', 'DAVID MENCIAS'), ('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO'), ('JUAN VILLAMARIN', 'JUAN VILLAMARIN'), ('PABLO BORJA', 'PABLO BORJA')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
