# Generated by Django 3.0.8 on 2022-04-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0112_auto_20220401_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salida_activos',
            options={'managed': True, 'permissions': (('acceso_activos', 'Acceso Provicional'), ('movimiento_activos', 'Acceso Movimiento de Activos'), ('consulta_activos_en_taller', 'Consulta Activos en Taller'), ('autorizacion_salida_activos', 'Autorización de Salida de Activos'), ('control_salida_activos', 'Control de Seguridad Salida de Activos'), ('movimiento_bodega_activos', 'Acceso Movimiento de Activos en Bodega'), ('rehistro_salida_activos', 'Registro de Salida de Activos'))},
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('MN', 'MANTENIMIENTO'), ('AC', 'ACTIVO'), ('RE', 'REPARACIÓN EXTERNA'), ('DO', 'DONADO'), ('DB', 'DADO DE BAJA'), ('VE', 'VENDIDO')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='grabado',
            field=models.CharField(blank=True, choices=[('ETIQUETA', 'ETIQUETA'), ('NO ES POSIBLE IDENTIFICAR', 'NO ES POSIBLE IDENTIFICAR'), ('GRABADO', 'GRABADO'), ('NO', 'NO')], default='NO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('6', 'EQUIPO ELECTRONICO'), ('5', 'VEHICULOS'), ('1', 'ROTURA DE MAQUINARIA'), ('3', 'INCENDIO'), ('2', 'EQUIPO Y MAQUINARIA'), ('4', 'SIN SEGURO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_custodio', 'Cambio de Custodio'), ('cambio_estado_identifica', 'Cambio de Estado Identificación Grabado/Etiquetado'), ('cambio_estado', 'Cambio de Estado'), ('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_fecha', 'Cambio de Fecha'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_ubicacion', 'Cambio de Ubicación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('PABLO BORJA', 'PABLO BORJA'), ('DAVID  MENCIAS', 'DAVID MENCIAS'), ('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO'), ('JUAN VILLAMARIN', 'JUAN VILLAMARIN')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
