# Generated by Django 3.0.8 on 2022-06-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0115_auto_20220606_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desc_activo',
            options={'managed': True, 'ordering': ['-activo_fecha_modifica'], 'permissions': (('acceso_activos', 'Acceso Provicional'), ('modificaciones_activos', 'Modificaciones Activos'), ('genera_código', 'Generación de Activos'), ('consulta_edita', 'Consulta y Edita Activos'), ('mis_activos', 'Consulta Activos en Custodio Propio'), ('descargo_activos', 'Descargo de Activos Seguridad'), ('custom_rep1', 'Consulta Reportes Activos Custom1'))},
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='activo_estado',
            field=models.CharField(blank=True, choices=[('DB', 'DADO DE BAJA'), ('MN', 'MANTENIMIENTO'), ('DO', 'DONADO'), ('AC', 'ACTIVO'), ('RE', 'REPARACIÓN EXTERNA'), ('VE', 'VENDIDO')], default='ACTIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='grabado',
            field=models.CharField(blank=True, choices=[('GRABADO', 'GRABADO'), ('NO ES POSIBLE IDENTIFICAR', 'NO ES POSIBLE IDENTIFICAR'), ('NO', 'NO'), ('ETIQUETA', 'ETIQUETA')], default='NO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='desc_activo',
            name='poliza_seguros',
            field=models.CharField(blank=True, choices=[('2', 'EQUIPO Y MAQUINARIA'), ('5', 'VEHICULOS'), ('6', 'EQUIPO ELECTRONICO'), ('4', 'SIN SEGURO'), ('1', 'ROTURA DE MAQUINARIA'), ('3', 'INCENDIO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_desc_activo',
            name='desc_activo_motivo_modifica',
            field=models.CharField(blank=True, choices=[('cambio_fecha', 'Cambio de Fecha'), ('cambio_custodio', 'Cambio de Custodio'), ('cambio_estado', 'Cambio de Estado'), ('cambio_caracteristicas', 'Cambio de Caracteristicas'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('actualiza_asegurado', 'Cambio valor Asegurado'), ('cambio_estado_identifica', 'Cambio de Estado Identificación Grabado/Etiquetado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salida_activos',
            name='sale_por',
            field=models.IntegerField(blank=True, choices=[(1, 'Reparación'), (4, 'Cambio de Ubicación (Haciendas / Machachi)')], null=True),
        ),
        migrations.AlterField(
            model_name='toma_fisica',
            name='usuario',
            field=models.CharField(blank=True, choices=[('DAVID  MENCIAS', 'DAVID MENCIAS'), ('PABLO BORJA', 'PABLO BORJA'), ('JUAN VILLAMARIN', 'JUAN VILLAMARIN'), ('EDUARDO CLAVIJO', 'EDUARDO CLAVIJO')], default='EDUARDO CLAVIJO', max_length=50, null=True),
        ),
    ]
