# Generated by Django 3.0.8 on 2022-05-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proyectos_contabilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(blank=True, max_length=1000, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_modifica', models.DateField(blank=True, null=True)),
                ('persona_edita', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'parametros"."proyectos_contabilidad',
                'permissions': (('edicion_proyectos_conta', 'Edicion Proyectos Contabilidad'),),
                'managed': True,
            },
        ),
    ]
