# Generated by Django 3.0.8 on 2022-05-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrosGlobales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos_contabilidad',
            name='codigo_proyecto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
