# Generated by Django 3.0.8 on 2022-05-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrosGlobales', '0002_proyectos_contabilidad_codigo_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_notificacion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'parametros"."tipo_notificacion',
                'managed': True,
            },
        ),
    ]
