# Generated by Django 3.0.8 on 2022-05-25 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametrosGlobales', '0003_tipo_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificaciones_globales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('identificador', models.IntegerField(blank=True, null=True)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parametrosGlobales.tipo_notificacion')),
                ('usuario_activa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parametros"."notificaciones_globales',
                'managed': True,
            },
        ),
    ]
