# Generated by Django 3.0.8 on 2022-05-27 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametrosGlobales', '0006_auto_20220527_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones_globales',
            name='autorizador_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autorizadorid', to=settings.AUTH_USER_MODEL),
        ),
    ]
