# Generated by Django 3.0.3 on 2022-05-30 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrosGlobales', '0007_auto_20220527_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelo_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_origen', models.CharField(blank=True, max_length=150, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'parametros"."modelo_app',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='notificaciones_globales',
            name='app_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parametrosGlobales.modelo_App'),
        ),
    ]
