# Generated by Django 3.0.3 on 2022-05-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrosGlobales', '0008_auto_20220530_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_notificacion',
            name='url_lista',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tipo_notificacion',
            name='url_tipo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
