# Generated by Django 3.0.8 on 2022-06-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrosGlobales', '0009_auto_20220531_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones_globales',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tipo_notificacion',
            name='nombre_abreviado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
