# Generated by Django 3.0.8 on 2022-06-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrosGlobales', '0010_auto_20220601_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones_globales',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
