# Generated by Django 3.0.8 on 2022-06-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrosGlobales', '0012_auto_20220601_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='consolida_ordenes_proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_aprueba_compra', models.DateTimeField(blank=True, null=True)),
                ('app_origen', models.CharField(blank=True, choices=[(1, 'ACTIVOS'), (2, 'INSUMOS/TRAB.')], max_length=60, null=True)),
            ],
            options={
                'db_table': 'parametros"."consolida_ordenes_proyectos',
                'managed': True,
            },
        ),
    ]
