# Generated by Django 3.0.8 on 2022-06-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrosGlobales', '0013_consolida_ordenes_proyectos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolida_ordenes_proyectos',
            name='app_origen',
            field=models.CharField(blank=True, choices=[('2', 'INSUMOS/TRAB.'), ('1', 'ACTIVOS')], max_length=60, null=True),
        ),
    ]
