# Generated by Django 3.0.8 on 2022-06-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrosGlobales', '0014_auto_20220630_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolida_ordenes_proyectos',
            name='analista',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consolida_ordenes_proyectos',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consolida_ordenes_proyectos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='consolida_ordenes_proyectos',
            name='proveedor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='consolida_ordenes_proyectos',
            name='proyecto',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='consolida_ordenes_proyectos',
            name='solicita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consolida_ordenes_proyectos',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consolida_ordenes_proyectos',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consolida_ordenes_proyectos',
            name='app_origen',
            field=models.CharField(blank=True, choices=[('1', 'ACTIVOS'), ('2', 'INSUMOS/TRAB.')], max_length=60, null=True),
        ),
    ]
