# Generated by Django 3.0.3 on 2022-07-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrosGlobales', '0016_auto_20220701_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolida_ordenes_proyectos',
            name='app_origen',
            field=models.CharField(blank=True, choices=[('1', 'ACTIVOS'), ('2', 'INSUMOS/TRAB.')], max_length=60, null=True),
        ),
    ]
