# Generated by Django 3.0 on 2020-03-11 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('cod_empleado', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'personal"."persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('placa', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('matricula', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('random', models.IntegerField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controlPersonal.Persona')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'personal"."vehiculos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VehiculoRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fch_ingreso', models.DateField(blank=True, null=True)),
                ('fch_ingreso_txt', models.CharField(blank=True, max_length=8, null=True)),
                ('hr_ingreso', models.DateTimeField(blank=True, null=True)),
                ('hr_ingreso_txt', models.CharField(blank=True, max_length=5, null=True)),
                ('hr_salida_almuerzo', models.DateTimeField(blank=True, null=True)),
                ('hr_salida_almuerzo_txt', models.CharField(blank=True, max_length=5, null=True)),
                ('hr_entrada_almuerzo', models.DateTimeField(blank=True, null=True)),
                ('hr_entrada_almuerzo_txt', models.CharField(blank=True, max_length=5, null=True)),
                ('hr_salida', models.DateTimeField(blank=True, null=True)),
                ('hr_salida_txt', models.CharField(blank=True, max_length=5, null=True)),
                ('revision_vehiculo', models.BooleanField(blank=True, null=True)),
                ('usuario_registra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controlPersonal.Vehiculos')),
            ],
            options={
                'verbose_name': 'Registro Vehículo',
                'verbose_name_plural': 'Registros Vehículos',
                'db_table': 'personal"."vehiculo_registro',
                'permissions': (('registro_vehiculo', 'Registros de Vehículos'),),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonaRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fch_ingreso', models.DateField(blank=True, null=True)),
                ('fch_ingreso_txt', models.CharField(blank=True, max_length=8, null=True)),
                ('hr_ingreso', models.DateTimeField(blank=True, null=True)),
                ('hr_ingreso_txt', models.CharField(blank=True, max_length=5, null=True)),
                ('hr_salida_almuerzo', models.DateTimeField(blank=True, null=True)),
                ('hr_salida_almuerzo_txt', models.CharField(blank=True, max_length=5, null=True)),
                ('hr_entrada_almuerzo', models.DateTimeField(blank=True, null=True)),
                ('hr_entrada_almuerzo_txt', models.CharField(blank=True, max_length=5, null=True)),
                ('hr_salida', models.DateTimeField(blank=True, null=True)),
                ('hr_salida_txt', models.CharField(blank=True, max_length=5, null=True)),
                ('carnet', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controlPersonal.Persona')),
                ('usuario_registra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Persona',
                'verbose_name_plural': 'Registros Personas',
                'db_table': 'personal"."persona_registro',
                'ordering': ['-id'],
                'permissions': (('registro_personal', 'Registros de Personal'),),
                'managed': True,
            },
        ),
    ]
