# Generated by Django 3.0 on 2020-03-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='bandera',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='bandera',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
