# Generated by Django 3.0 on 2020-03-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0002_auto_20200313_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaregistro',
            name='ord',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
