# Generated by Django 3.0 on 2020-03-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0003_personaregistro_ord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaregistro',
            options={'managed': True, 'ordering': ['-ord'], 'permissions': (('registro_personal', 'Registros de Personal'),), 'verbose_name': 'Registro Persona', 'verbose_name_plural': 'Registros Personas'},
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='estado_pl',
            field=models.BooleanField(default=False),
        ),
    ]
