# Generated by Django 3.0 on 2020-03-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0004_auto_20200317_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculoregistro',
            name='estado_pl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculoregistro',
            name='ord',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
