# Generated by Django 3.0 on 2020-03-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0005_auto_20200317_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaregistro',
            name='estado_pl',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
