# Generated by Django 3.0 on 2020-03-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0006_auto_20200317_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculoregistro',
            name='estado_pl',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
