# Generated by Django 3.0 on 2020-03-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0007_auto_20200317_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaregistro',
            name='estado_pl',
        ),
        migrations.RemoveField(
            model_name='vehiculoregistro',
            name='estado_pl',
        ),
        migrations.AddField(
            model_name='persona',
            name='estado_pl',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='estado_pl',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
