# Generated by Django 3.0 on 2020-03-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0008_auto_20200317_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaregistro',
            name='fch_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='fch_salida_txt',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoregistro',
            name='fch_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoregistro',
            name='fch_salida_txt',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
