# Generated by Django 3.0 on 2020-03-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0009_auto_20200319_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaregistro',
            options={'managed': True, 'ordering': ['-ord'], 'permissions': (('registro_personal', 'Registros de Personal'), ('reporte_ingresos', 'Reporte de Ingresos')), 'verbose_name': 'Registro Persona', 'verbose_name_plural': 'Registros Personas'},
        ),
    ]
