# Generated by Django 3.0 on 2020-04-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0010_auto_20200326_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabezales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Cabezal',
                'verbose_name_plural': 'Cabezales',
                'db_table': 'personal"."cabezales',
                'permissions': (('registro_cabezal', 'Registro de Cabezales'),),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('cedula', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(default=1)),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controlPersonal.Cabezales')),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
                'db_table': 'personal"."chofer',
                'permissions': (('registro_chofer', 'Registro de Choferes'),),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('transportista', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'db_table': 'personal"."transportista',
                'permissions': (('registro_transporte', 'Registro de Transportistas'),),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContenedorRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('num_contenedor_ingreso', models.CharField(max_length=12)),
                ('fch_ingreso', models.DateField(blank=True, null=True)),
                ('fch_ingreso_txt', models.CharField(blank=True, max_length=8, null=True)),
                ('hr_ingreso', models.DateTimeField(blank=True, null=True)),
                ('hr_ingreso_txt', models.CharField(blank=True, max_length=5, null=True)),
                ('num_contenedor_salida', models.CharField(max_length=12)),
                ('fch_salida', models.DateField(blank=True, null=True)),
                ('fch_salida_txt', models.CharField(blank=True, max_length=8, null=True)),
                ('hr_salida', models.DateTimeField(blank=True, null=True)),
                ('hr_salida_txt', models.CharField(blank=True, max_length=5, null=True)),
                ('ord', models.DateTimeField(auto_now=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controlPersonal.Chofer')),
            ],
            options={
                'verbose_name': 'Registro Contenedor',
                'verbose_name_plural': 'Registro Contenedores',
                'db_table': 'personal"."contenedor_registro',
                'permissions': (('registro_contenedor', 'Registro de Contenedores'), ('reporte_contenedor', 'Reporte de Contenedores')),
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chofer',
            name='transportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controlPersonal.Transportista'),
        ),
        migrations.AddField(
            model_name='cabezales',
            name='transportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controlPersonal.Transportista'),
        ),
    ]
