# Generated by Django 3.0 on 2020-04-20 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0017_auto_20200420_1649'),
        ('controlPersonal', '0012_auto_20200415_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='area',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_areas'),
            preserve_default=False,
        ),
    ]
