# Generated by Django 3.0 on 2020-06-05 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0014_chofer_observaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabezales',
            options={'managed': True, 'ordering': ['placa'], 'permissions': (('registro_cabezal', 'Registro de Cabezales'),), 'verbose_name': 'Cabezal', 'verbose_name_plural': 'Cabezales'},
        ),
        migrations.AlterModelOptions(
            name='transportista',
            options={'managed': True, 'ordering': ['transportista'], 'permissions': (('registro_transporte', 'Registro de Transportistas'),), 'verbose_name': 'Transportista', 'verbose_name_plural': 'Transportistas'},
        ),
        migrations.AddField(
            model_name='contenedorregistro',
            name='sello_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contenedorregistro',
            name='sello_basc_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='placa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='controlPersonal.Cabezales'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='transportista',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='controlPersonal.Transportista'),
        ),
    ]
