# Generated by Django 3.0 on 2020-06-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0015_auto_20200605_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedorregistro',
            name='sello_basc_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contenedorregistro',
            name='sello_basc_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contenedorregistro',
            name='sello_eco_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contenedorregistro',
            name='sello_eco_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contenedorregistro',
            name='sello_eco_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contenedorregistro',
            name='sello_naviera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
