# Generated by Django 3.0.7 on 2020-07-30 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controlPersonal', '0016_auto_20200605_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmuerzoRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_txt', models.CharField(blank=True, max_length=8, null=True)),
                ('hr_salida_almuerzo', models.DateTimeField(blank=True, null=True)),
                ('hr_salida_almuerzo_txt', models.CharField(blank=True, max_length=5, null=True)),
                ('hr_entrada_almuerzo', models.DateTimeField(blank=True, null=True)),
                ('hr_entrada_almuerzo_txt', models.CharField(blank=True, max_length=5, null=True)),
                ('ord', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controlPersonal.Persona')),
                ('usuario_registra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Almuerzo',
                'verbose_name_plural': 'Registros Almuerzos',
                'db_table': 'personal"."almuerzo_registro',
                'ordering': ['-ord'],
                'permissions': (('registro_almuerzos', 'Registros de Almuerzos'), ('reporte_almuerzos', 'Reporte de Almuerzos')),
                'managed': True,
            },
        ),
    ]
