# Generated by Django 3.0.7 on 2020-07-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0017_almuerzoregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado_al',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
