# Generated by Django 3.0.7 on 2020-08-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0019_auto_20200831_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaregistro',
            options={'managed': True, 'ordering': ['-ord'], 'permissions': (('registro_personal', 'Registros de Personal'), ('reporte_ingresos', 'Reporte de Ingresos'), ('registro_ac', 'Registros de Personal Agua Clara')), 'verbose_name': 'Registro Persona', 'verbose_name_plural': 'Registros Personas'},
        ),
    ]
