# Generated by Django 3.0.7 on 2020-08-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0020_auto_20200831_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaregistro',
            name='ubica',
            field=models.CharField(default='MCH', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculoregistro',
            name='ubica',
            field=models.CharField(default='MCH', max_length=3),
            preserve_default=False,
        ),
    ]
