# Generated by Django 3.0.7 on 2020-10-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0023_auto_20201020_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculoregistro',
            name='prueba',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
