# Generated by Django 3.0.7 on 2020-10-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0024_vehiculoregistro_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculoregistro',
            name='prueba',
        ),
    ]
