# Generated by Django 3.0 on 2020-11-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0025_remove_vehiculoregistro_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
