# Generated by Django 3.0.7 on 2020-11-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0026_persona_extension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaregistro',
            options={'managed': True, 'ordering': ['-ord'], 'permissions': (('registro_personal', 'Registros de Personal'), ('reporte_ingresos', 'Reporte de Ingresos'), ('busqueda_rapida', 'Busqueda Rapida'), ('registro_ac', 'Registros de Personal Agua Clara'), ('registro_ll', 'Registros de Personal La Laurita'), ('registro_la', 'Registros de Personal La Avelina')), 'verbose_name': 'Registro Persona', 'verbose_name_plural': 'Registros Personas'},
        ),
    ]
