# Generated by Django 3.0.7 on 2020-12-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0027_auto_20201126_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculoregistro',
            options={'managed': True, 'permissions': (('registro_vehiculo', 'Registros de Vehículos'), ('reporte_vehiculos', 'Reporte de ingreso de Vehículos')), 'verbose_name': 'Registro Vehículo', 'verbose_name_plural': 'Registros Vehículos'},
        ),
    ]
