# Generated by Django 3.0.7 on 2020-12-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0028_auto_20201201_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': True, 'permissions': (('menu_ecofroz', 'Acceso Menu Ecofroz'), ('persona_directorio', 'Directorio de Personal')), 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
