# Generated by Django 3.0.8 on 2021-10-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0031_auto_20211011_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nom_empresa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
