# Generated by Django 3.0.8 on 2022-01-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0032_persona_nom_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='maximo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
