# Generated by Django 3.0.8 on 2022-01-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0033_vehiculos_maximo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='username_sia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
