# Generated by Django 3.0.8 on 2022-03-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0034_persona_username_sia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteNovedades',
            fields=[
                ('numreporte', models.AutoField(primary_key=True, serialize=False)),
                ('guardia1', models.CharField(blank=True, choices=[(2, 'FAJARDO MOSQUERA FABIAN'), (4, 'CHANGOLUISA ZAMBRANO FREDDY'), (5, 'FLORES MARTINEZ VICENTE'), (8, 'ORTIZ REMACHE MARCO'), (6, 'LEON VARGAS WILMER'), (3, 'ARGUERO YANCHAPAXI HECTOR'), (7, 'OCAÑA HERMOSA EDISON'), (1, 'CHILIQUINGA CADENA CARLOS')], max_length=200, null=True)),
                ('guardia2', models.CharField(blank=True, choices=[(2, 'FAJARDO MOSQUERA FABIAN'), (4, 'CHANGOLUISA ZAMBRANO FREDDY'), (5, 'FLORES MARTINEZ VICENTE'), (8, 'ORTIZ REMACHE MARCO'), (6, 'LEON VARGAS WILMER'), (3, 'ARGUERO YANCHAPAXI HECTOR'), (7, 'OCAÑA HERMOSA EDISON'), (1, 'CHILIQUINGA CADENA CARLOS')], max_length=200, null=True)),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Enviado'), (2, 'Recibido'), (3, 'Recibido con Observaciones')], null=True)),
                ('fchregistro', models.DateTimeField(blank=True, null=True)),
                ('fchrecibido', models.DateTimeField(blank=True, null=True)),
                ('asunto', models.CharField(blank=True, max_length=1000, null=True)),
                ('observaciones_guardias', models.CharField(blank=True, max_length=10000, null=True)),
                ('observaciones_seg', models.CharField(blank=True, max_length=10000, null=True)),
                ('estado_observaciones_seg', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personal"."reportenovedades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetReporteNovedades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='otros_doc/', verbose_name='Imagen 1')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='otros_doc/', verbose_name='Imagen 2')),
                ('numreporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detnovedades', to='controlPersonal.ReporteNovedades')),
            ],
            options={
                'db_table': 'personal"."detreportenovedades',
                'managed': True,
            },
        ),
    ]
