# Generated by Django 3.0.8 on 2022-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0035_detreportenovedades_reportenovedades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculoregistro',
            options={'managed': True, 'permissions': (('registro_vehiculo', 'Registros de Vehículos'), ('reporte_vehiculos', 'Reporte de ingreso de Vehículos'), ('registro_reporte_diario', 'Registro Diario de Novedades Seguridad'), ('supervisa_reporte_diario', 'Supervisa Reporte Diario de Novedades Seguridad')), 'verbose_name': 'Registro Vehículo', 'verbose_name_plural': 'Registros Vehículos'},
        ),
        migrations.AlterField(
            model_name='reportenovedades',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(3, 'Recibido con Observaciones'), (2, 'Recibido'), (1, 'Enviado')], null=True),
        ),
        migrations.AlterField(
            model_name='reportenovedades',
            name='guardia1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reportenovedades',
            name='guardia2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
