# Generated by Django 3.0.8 on 2022-03-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0036_auto_20220322_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': True, 'permissions': (('menu_ecofroz', 'Acceso Menu Ecofroz'), ('persona_directorio', 'Directorio de Personal'), ('capacitacion', 'Capacitacion'), ('capacitacion_guardias', 'Capacitación Guardianía')), 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterField(
            model_name='reportenovedades',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Enviado'), (3, 'Recibido con Observaciones'), (2, 'Recibido')], null=True),
        ),
    ]
