# Generated by Django 3.0.3 on 2022-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0037_auto_20220325_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportenovedades',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(2, 'Recibido'), (1, 'Enviado'), (3, 'Recibido con Observaciones')], null=True),
        ),
    ]
