# Generated by Django 3.0.8 on 2022-05-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0038_auto_20220512_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportenovedades',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Enviado'), (2, 'Recibido'), (3, 'Recibido con Observaciones')], null=True),
        ),
    ]
