# Generated by Django 3.0.8 on 2022-05-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0039_auto_20220516_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackBusqueda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personabb', models.CharField(blank=True, max_length=300, null=True)),
                ('personab', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personal"."busquedas',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='reportenovedades',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(3, 'Recibido con Observaciones'), (1, 'Enviado'), (2, 'Recibido')], null=True),
        ),
    ]
