# Generated by Django 3.0.8 on 2022-05-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0040_auto_20220516_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackbusqueda',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportenovedades',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(2, 'Recibido'), (1, 'Enviado'), (3, 'Recibido con Observaciones')], null=True),
        ),
    ]
