# Generated by Django 3.0.8 on 2022-10-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0043_auto_20221024_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': True, 'permissions': (('menu_ecofroz', 'Acceso Menu Ecofroz'), ('persona_directorio', 'Directorio de Personal'), ('capacitacion', 'Capacitacion'), ('capacitacion_guardias', 'Capacitación Guardianía')), 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
