# Generated by Django 3.0.3 on 2023-09-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0045_auto_20230512_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportenovedades',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(2, 'Recibido'), (1, 'Enviado'), (3, 'Recibido con Observaciones')], null=True),
        ),
        migrations.AlterField(
            model_name='reportenovedades',
            name='observaciones_guardias',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='reportenovedades',
            name='observaciones_seg',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
