# Generated by Django 3.2.15 on 2023-09-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0046_auto_20230906_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportenovedades',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Enviado'), (3, 'Recibido con Observaciones'), (2, 'Recibido')], null=True),
        ),
        migrations.AlterField(
            model_name='reportenovedades',
            name='observaciones_guardias',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
