# Generated by Django 3.2.15 on 2023-11-08 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0047_auto_20230907_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='referencia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reportenovedades',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Enviado'), (2, 'Recibido'), (3, 'Recibido con Observaciones')], null=True),
        ),
        migrations.AlterField(
            model_name='vehiculoregistro',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalle_reg', to='controlPersonal.vehiculos'),
        ),
    ]
