# Generated by Django 3.2.15 on 2023-11-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0048_auto_20231108_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='fecha_modifica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='persona_edita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportenovedades',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(2, 'Recibido'), (1, 'Enviado'), (3, 'Recibido con Observaciones')], null=True),
        ),
    ]
