# Generated by Django 3.2.15 on 2023-11-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0049_auto_20231108_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedorregistro',
            name='destino',
            field=models.CharField(blank=True, choices=[('GY', 'GUAYAQUIL'), ('PS', 'POSORJA')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reportenovedades',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(3, 'Recibido con Observaciones'), (1, 'Enviado'), (2, 'Recibido')], null=True),
        ),
    ]
