# Generated by Django 3.2.15 on 2023-11-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPersonal', '0050_auto_20231108_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedorregistro',
            name='tmaxgye',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenedorregistro',
            name='tmaxpsj',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportenovedades',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(2, 'Recibido'), (1, 'Enviado'), (3, 'Recibido con Observaciones')], null=True),
        ),
    ]
