# Generated by Django 3.0 on 2020-02-18 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0003_auto_20200218_1619'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenesPedidos',
            fields=[
                ('numpedido', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_aprueba', models.CharField(blank=True, max_length=100, null=True)),
                ('aprobado', models.IntegerField(blank=True, choices=[('', 'Pendiente'), (1, 'Aprobado'), (0, 'No Aprobado')], null=True)),
                ('fchsolicita', models.DateField(auto_now_add=True)),
                ('fchsolicitatxt', models.CharField(blank=True, max_length=8, null=True)),
                ('tiempo_vida', models.IntegerField()),
                ('tiempo_tipo', models.CharField(choices=[('hora', 'Horas'), ('semana', 'Semanas'), ('mes', 'Meses'), ('anio', 'Años'), ('dia', 'Dias')], max_length=7)),
                ('numproyecto', models.CharField(blank=True, max_length=70, null=True)),
                ('regimenespecial', models.BooleanField(blank=True, default=False, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('files', models.CharField(blank=True, max_length=1000, null=True)),
                ('fchaprueba', models.DateField(auto_now=True, null=True)),
                ('fchapruebatxt', models.CharField(blank=True, max_length=8, null=True)),
                ('motRechaza', models.CharField(blank=True, max_length=250, null=True)),
                ('estado_cotiza', models.BooleanField(blank=True, null=True)),
                ('genera_compra', models.IntegerField(blank=True, null=True)),
                ('motivo_compra', models.CharField(blank=True, choices=[('reemplazo', 'Reemplazo'), ('nuevo', 'Nuevo')], max_length=50, null=True)),
                ('justificacion_compra', models.CharField(blank=True, max_length=250, null=True)),
                ('reemplazo_accion', models.CharField(blank=True, max_length=250, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_areas')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_depar')),
                ('tipoactivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_tipo')),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden Pedido',
                'verbose_name_plural': 'Ordenes Pedidos',
                'db_table': 'pedidos"."ordenespedidos',
                'ordering': ['-numpedido'],
                'permissions': (('aprueba_ordenespedidos', 'Aprueba Ordenes de Pedidos'), ('genera_ordenescompra', 'Genera Ordenes de Conpra')),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('unimedida', models.CharField(blank=True, choices=[('m', 'Metro'), ('cm', 'Centimetro'), ('unidad', 'Unidad'), ('mm', 'Milimetro'), ('kg', 'Kilos'), ('gr', 'Gramos'), ('lt', 'Litros'), ('gl', 'Galones'), ('lb', 'Libras')], max_length=15, null=True)),
                ('numpedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenPedido.OrdenesPedidos')),
            ],
            options={
                'verbose_name': 'Detalle Pedido',
                'verbose_name_plural': 'Detalles Pedidos',
                'db_table': 'pedidos"."detallepedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CotizaPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('empresa_cotiza', models.IntegerField(blank=True, choices=[(2, 'DELCORP S.A.'), (5, 'ELECTROLEG'), (4, 'GRUPASA'), (3, 'IDC'), (1, 'COREPTEC'), (6, 'GRUENTEC')], null=True, verbose_name='Proveedor')),
                ('pdf_cotiza', models.FileField(blank=True, null=True, upload_to='cotizaciones/', verbose_name='Cotización')),
                ('cotiza_seleccion', models.BooleanField(blank=True, null=True, verbose_name='Selección')),
                ('numpedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenPedido.OrdenesPedidos')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'pedidos"."cotizapedido',
                'permissions': (('selecciona_cotizapedido', 'Seleccionar Cotizaciones'),),
                'managed': True,
            },
        ),
    ]
