# Generated by Django 3.0 on 2020-02-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20200221_1110'),
        ('ordenPedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizapedido',
            name='empresa_cotiza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='unimedida',
            field=models.CharField(blank=True, choices=[('m', 'Metro'), ('lt', 'Litros'), ('lb', 'Libras'), ('gr', 'Gramos'), ('kg', 'Kilos'), ('gl', 'Galones'), ('unidad', 'Unidad'), ('mm', 'Milimetro'), ('cm', 'Centimetro')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('reemplazo', 'Reemplazo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('semana', 'Semanas'), ('hora', 'Horas'), ('dia', 'Dias'), ('mes', 'Meses'), ('anio', 'Años')], max_length=7),
        ),
    ]
