# Generated by Django 3.0 on 2020-02-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0003_auto_20200227_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='unimedida',
            field=models.CharField(blank=True, choices=[('unidad', 'Unidad'), ('lb', 'Libras'), ('cm', 'Centimetro'), ('m', 'Metro'), ('gr', 'Gramos'), ('gl', 'Galones'), ('lt', 'Litros'), ('mm', 'Milimetro'), ('kg', 'Kilos')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(choices=[(5, 'Mejora'), (4, 'Reparación'), (2, 'Reubicación'), (3, 'Backup'), (1, 'Dada de Baja')]),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('hora', 'Horas'), ('anio', 'Años'), ('dia', 'Dias'), ('mes', 'Meses'), ('semana', 'Semanas')], max_length=7),
        ),
    ]
