# Generated by Django 3.0 on 2020-02-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0004_auto_20200227_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenespedidos',
            name='activado_activo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenespedidos',
            name='entrega_observa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ordenespedidos',
            name='entregado_bodega',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenespedidos',
            name='fecha_activacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenespedidos',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenespedidos',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenespedidos',
            name='recibido_bodega',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='unimedida',
            field=models.CharField(blank=True, choices=[('mm', 'Milimetro'), ('kg', 'Kilos'), ('gl', 'Galones'), ('cm', 'Centimetro'), ('unidad', 'Unidad'), ('lt', 'Litros'), ('gr', 'Gramos'), ('lb', 'Libras'), ('m', 'Metro')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (1, 'Aprobado'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_m', 'Reemplazo por Mejora')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(choices=[(4, 'Reparación'), (3, 'Backup'), (1, 'Dada de Baja'), (2, 'Reubicación')]),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('hora', 'Horas'), ('mes', 'Meses'), ('dia', 'Dias'), ('semana', 'Semanas'), ('anio', 'Años')], max_length=7),
        ),
    ]
