# Generated by Django 3.0 on 2020-03-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0005_auto_20200228_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='unimedida',
            field=models.CharField(blank=True, choices=[('m', 'Metro'), ('gl', 'Galones'), ('kg', 'Kilos'), ('cm', 'Centimetro'), ('lt', 'Litros'), ('gr', 'Gramos'), ('lb', 'Libras'), ('mm', 'Milimetro'), ('unidad', 'Unidad')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('hora', 'Horas'), ('semana', 'Semanas'), ('dia', 'Dias'), ('anio', 'Años'), ('mes', 'Meses')], max_length=7),
        ),
    ]
