# Generated by Django 3.0 on 2020-03-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0007_auto_20200302_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenespedidos',
            name='codigo_genera',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='unimedida',
            field=models.CharField(blank=True, choices=[('mm', 'Milimetro'), ('gr', 'Gramos'), ('cm', 'Centimetro'), ('lb', 'Libras'), ('kg', 'Kilos'), ('unidad', 'Unidad'), ('lt', 'Litros'), ('m', 'Metro'), ('gl', 'Galones')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(blank=True, choices=[('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo'), ('reemplazo_m', 'Reemplazo por Mejora')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(choices=[(4, 'Reparación'), (2, 'Reubicación'), (3, 'Backup'), (1, 'Dada de Baja')]),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('semana', 'Semanas'), ('mes', 'Meses'), ('anio', 'Años'), ('hora', 'Horas'), ('dia', 'Dias')], max_length=7),
        ),
    ]
