# Generated by Django 3.0 on 2020-03-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0008_auto_20200302_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='unimedida',
            field=models.CharField(blank=True, choices=[('unidad', 'Unidad')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(blank=True, choices=[('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_m', 'Reemplazo por Mejora'), ('nuevo', 'Nuevo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(1, 'Dada de Baja'), (2, 'Reubicación'), (4, 'Reparación'), (3, 'Backup')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('dia', 'Dias'), ('mes', 'Meses'), ('semana', 'Semanas'), ('hora', 'Horas'), ('anio', 'Años')], max_length=7),
        ),
    ]
