# Generated by Django 3.0 on 2020-03-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0009_auto_20200304_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenespedidos',
            options={'managed': True, 'ordering': ['-numpedido'], 'permissions': (('aprueba_ordenespedidos', 'Aprueba Ordenes de Pedidos'), ('genera_ordenescompra', 'Genera Ordenes de Conpra'), ('activa_activos', 'Activación de Activos'), ('acceso_pedidos', 'Acceso a Pedidos')), 'verbose_name': 'Orden Pedido', 'verbose_name_plural': 'Ordenes Pedidos'},
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(blank=True, choices=[('reemplazo_m', 'Reemplazo por Mejora'), ('nuevo', 'Nuevo'), ('reemplazo_o', 'Reemplazo por Obsolescencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(3, 'Backup'), (2, 'Reubicación'), (4, 'Reparación'), (1, 'Dada de Baja')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('mes', 'Meses'), ('hora', 'Horas'), ('anio', 'Años'), ('semana', 'Semanas'), ('dia', 'Dias')], max_length=7),
        ),
    ]
