# Generated by Django 3.0 on 2020-04-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0013_auto_20200421_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='img_1',
            field=models.FileField(blank=True, null=True, upload_to='img_pedidos/', verbose_name='Imagen 1'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='img_2',
            field=models.FileField(blank=True, null=True, upload_to='img_pedidos/', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_o', 'Reemplazo por Obsolescencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(3, 'Backup'), (1, 'Dada de Baja'), (2, 'Reubicación'), (4, 'Reparación')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('anio', 'Años'), ('hora', 'Horas'), ('dia', 'Dias'), ('mes', 'Meses'), ('semana', 'Semanas')], max_length=7),
        ),
    ]
