# Generated by Django 3.0 on 2020-04-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0014_auto_20200422_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='cotizaciones/', verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='cotizaciones/', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(blank=True, choices=[('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(4, 'Reparación'), (3, 'Backup'), (2, 'Reubicación'), (1, 'Dada de Baja')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('hora', 'Horas'), ('semana', 'Semanas'), ('dia', 'Dias'), ('mes', 'Meses'), ('anio', 'Años')], max_length=7),
        ),
    ]
