# Generated by Django 3.0 on 2020-04-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0015_auto_20200422_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='img_pedidos/', verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='img_pedidos/', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (1, 'Aprobado'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(4, 'Reparación'), (2, 'Reubicación'), (3, 'Backup'), (1, 'Dada de Baja')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('dia', 'Dias'), ('anio', 'Años'), ('hora', 'Horas'), ('semana', 'Semanas'), ('mes', 'Meses')], max_length=7),
        ),
    ]
