# Generated by Django 3.0 on 2020-04-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0017_auto_20200424_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='cotiza_Ref',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones/', verbose_name='Cotización Referencial'),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(blank=True, choices=[('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(4, 'Reparación'), (1, 'Dada de Baja'), (2, 'Reubicación'), (3, 'Backup')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('anio', 'Años'), ('dia', 'Dias'), ('semana', 'Semanas'), ('mes', 'Meses'), ('hora', 'Horas')], max_length=7),
        ),
    ]
