# Generated by Django 3.0 on 2020-05-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0020_auto_20200506_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenespedidos',
            name='select_cotiza',
            field=models.BooleanField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_m', 'Reemplazo por Mejora'), ('nuevo', 'Nuevo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(3, 'Backup'), (1, 'Dada de Baja'), (4, 'Reparación'), (2, 'Reubicación')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('dia', 'Dias'), ('hora', 'Horas'), ('mes', 'Meses'), ('anio', 'Años'), ('semana', 'Semanas')], max_length=7),
        ),
    ]
