# Generated by Django 3.0 on 2020-05-14 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activos', '0024_auto_20200513_2011'),
        ('proveedores', '0023_auto_20200513_2011'),
        ('ordenPedido', '0022_auto_20200506_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_r', 'Reemplazo por Reparación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(3, 'Backup'), (4, 'Reparación'), (2, 'Reubicación'), (1, 'Dada de Baja')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('mes', 'Meses'), ('dia', 'Dias'), ('semana', 'Semanas'), ('anio', 'Años'), ('hora', 'Horas')], max_length=7),
        ),
        migrations.CreateModel(
            name='RechazaOrdenesPedidos',
            fields=[
                ('numpedido', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario_aprueba', models.CharField(blank=True, max_length=100, null=True)),
                ('aprobado', models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (0, 'No Aprobado')], null=True)),
                ('observa_selec_cot', models.CharField(blank=True, max_length=250, null=True)),
                ('fchsolicita', models.DateField(auto_now_add=True)),
                ('fchsolicitatxt', models.CharField(blank=True, max_length=8, null=True)),
                ('tiempo_vida', models.IntegerField()),
                ('tiempo_tipo', models.CharField(choices=[('mes', 'Meses'), ('dia', 'Dias'), ('semana', 'Semanas'), ('anio', 'Años'), ('hora', 'Horas')], max_length=7)),
                ('numproyecto', models.CharField(blank=True, max_length=70, null=True)),
                ('regimenespecial', models.BooleanField(blank=True, default=False, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('files', models.CharField(blank=True, max_length=1000, null=True)),
                ('fchaprueba', models.DateField(auto_now=True, null=True)),
                ('fchapruebatxt', models.CharField(blank=True, max_length=8, null=True)),
                ('motRechaza', models.CharField(blank=True, max_length=250, null=True)),
                ('estado_cotiza', models.BooleanField(blank=True, null=True)),
                ('cotiza_observa', models.CharField(blank=True, max_length=250, null=True)),
                ('select_cotiza', models.BooleanField(blank=True, max_length=250, null=True)),
                ('genera_compra', models.IntegerField(blank=True, null=True)),
                ('observa_compra', models.CharField(blank=True, max_length=250, null=True)),
                ('motivo_compra', models.CharField(choices=[('nuevo', 'Nuevo'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_r', 'Reemplazo por Reparación')], max_length=50, null=True)),
                ('justificacion_compra', models.CharField(blank=True, max_length=250, null=True)),
                ('reemplazo_accion', models.IntegerField(blank=True, choices=[(3, 'Backup'), (4, 'Reparación'), (2, 'Reubicación'), (1, 'Dada de Baja')], null=True)),
                ('reemplazo_observa', models.CharField(blank=True, max_length=250, null=True)),
                ('activado_activo', models.BooleanField(blank=True, null=True)),
                ('fecha_activacion', models.DateField(blank=True, null=True)),
                ('recibido_bodega', models.BooleanField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('codigo_genera', models.BooleanField(blank=True, null=True)),
                ('entregado_bodega', models.BooleanField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('entrega_observa', models.CharField(blank=True, max_length=250, null=True)),
                ('ord', models.DateTimeField(auto_now=True)),
                ('cod_activo', models.CharField(blank=True, max_length=10, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_areas')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_depar')),
                ('tipoactivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_tipo')),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden Pedido Rechazada',
                'verbose_name_plural': 'Ordenes Pedidos Rechazadas',
                'db_table': 'pedidos"."ordenespedidosrechaza',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RechazaDetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('unimedida', models.CharField(blank=True, choices=[('unidad', 'Unidad')], max_length=15, null=True)),
                ('img_1', models.CharField(blank=True, max_length=250, null=True)),
                ('img_2', models.CharField(blank=True, max_length=250, null=True)),
                ('cotiza_Ref', models.CharField(blank=True, max_length=250, null=True)),
                ('numpedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenPedido.RechazaOrdenesPedidos')),
            ],
            options={
                'verbose_name': 'Detalle Pedido Rechazada',
                'verbose_name_plural': 'Detalles Pedidos Rechazadas',
                'db_table': 'pedidos"."detallepedidorechaza',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RechazaCotizaPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('pdf_cotiza', models.CharField(blank=True, max_length=250, null=True)),
                ('cotiza_seleccion', models.BooleanField(blank=True, null=True, verbose_name='Selección')),
                ('empresa_cotiza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proveedores.proveedor', verbose_name='Proveedor')),
                ('numpedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenPedido.RechazaOrdenesPedidos')),
            ],
            options={
                'verbose_name': 'Cotización Rechazada',
                'verbose_name_plural': 'Cotizaciones Rechazadas',
                'db_table': 'pedidos"."cotizapedidorechaza',
                'managed': True,
            },
        ),
    ]
