# Generated by Django 3.0.7 on 2020-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0033_auto_20200708_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenespedidos',
            name='compra_directa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (0, 'No Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_r', 'Reemplazo por Reparación'), ('nuevo', 'Nuevo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('semana', 'Semanas'), ('hora', 'Horas'), ('mes', 'Meses'), ('anio', 'Años'), ('dia', 'Dias')], max_length=7),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (0, 'No Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_r', 'Reemplazo por Reparación'), ('nuevo', 'Nuevo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('semana', 'Semanas'), ('hora', 'Horas'), ('mes', 'Meses'), ('anio', 'Años'), ('dia', 'Dias')], max_length=7),
        ),
    ]
