# Generated by Django 3.0.7 on 2020-07-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0034_auto_20200714_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenespedidos',
            options={'managed': True, 'ordering': ['-numpedido'], 'permissions': (('aprueba_ordenespedidos', 'Aprueba Ordenes de Pedidos'), ('genera_ordenescompra', 'Genera Ordenes de Conpra'), ('activa_activos', 'Activación de Activos'), ('acceso_pedidos', 'Acceso a Pedidos'), ('facturacion', 'Revisión de Facturación')), 'verbose_name': 'Orden Pedido', 'verbose_name_plural': 'Ordenes Pedidos'},
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo'), ('reemplazo_m', 'Reemplazo por Mejora')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(4, 'Reparación'), (2, 'Reubicación'), (1, 'Dada de Baja'), (3, 'Backup')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('hora', 'Horas'), ('anio', 'Años'), ('semana', 'Semanas'), ('dia', 'Dias'), ('mes', 'Meses')], max_length=7),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo'), ('reemplazo_m', 'Reemplazo por Mejora')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(4, 'Reparación'), (2, 'Reubicación'), (1, 'Dada de Baja'), (3, 'Backup')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('hora', 'Horas'), ('anio', 'Años'), ('semana', 'Semanas'), ('dia', 'Dias'), ('mes', 'Meses')], max_length=7),
        ),
    ]
