# Generated by Django 3.0.7 on 2021-01-11 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenPedido', '0044_auto_20201126_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo'), ('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_m', 'Reemplazo por Mejora')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(2, 'Reubicación'), (1, 'Dada de Baja'), (5, 'Venta'), (3, 'Backup'), (4, 'Reparación')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('anio', 'Años'), ('mes', 'Meses'), ('hora', 'Horas'), ('dia', 'Dias'), ('semana', 'Semanas')], max_length=7),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo'), ('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_m', 'Reemplazo por Mejora')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(2, 'Reubicación'), (1, 'Dada de Baja'), (5, 'Venta'), (3, 'Backup'), (4, 'Reparación')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('anio', 'Años'), ('mes', 'Meses'), ('hora', 'Horas'), ('dia', 'Dias'), ('semana', 'Semanas')], max_length=7),
        ),
        migrations.CreateModel(
            name='OrdenesPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fch_genera', models.DateField(blank=True, null=True)),
                ('fch_genera_txt', models.CharField(blank=True, max_length=8, null=True)),
                ('origen', models.IntegerField(blank=True, choices=[(2, 'SIA'), (1, 'MBA'), (3, 'RESERVA')], null=True)),
                ('numero', models.CharField(blank=True, max_length=25, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='pagos/', verbose_name='Pagos')),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=2500, null=True)),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Pago',
                'verbose_name_plural': 'Ordenes de Pagos',
                'db_table': 'pedidos"."ordenespago',
                'permissions': (('menu_ingreso_pagos', 'Acceso al menu de Ingreso Pagos'), ('menu_autoriza_pagos', 'Acceso al menu de Autrización Pagos'), ('menu_consulta_pagos', 'Acceso al menu de Consulta Pagos')),
                'managed': True,
            },
        ),
    ]
