# Generated by Django 3.0.8 on 2021-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0050_auto_20210903_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenespago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(2, 'SIA'), (1, 'MBA'), (3, 'RESERVA')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (0, 'No Aprobado'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='justificacion_compra',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_m', 'Reemplazo por Mejora'), ('nuevo', 'Nuevo'), ('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_o', 'Reemplazo por Obsolescencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(2, 'Reubicación'), (4, 'Reparación'), (3, 'Backup'), (5, 'Venta'), (1, 'Dada de Baja')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('hora', 'Horas'), ('mes', 'Meses'), ('dia', 'Dias'), ('semana', 'Semanas'), ('anio', 'Años')], max_length=7),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (0, 'No Aprobado'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_m', 'Reemplazo por Mejora'), ('nuevo', 'Nuevo'), ('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_o', 'Reemplazo por Obsolescencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(2, 'Reubicación'), (4, 'Reparación'), (3, 'Backup'), (5, 'Venta'), (1, 'Dada de Baja')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('hora', 'Horas'), ('mes', 'Meses'), ('dia', 'Dias'), ('semana', 'Semanas'), ('anio', 'Años')], max_length=7),
        ),
    ]
