# Generated by Django 3.0.8 on 2021-10-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0051_auto_20210903_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenespago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(1, 'MBA'), (3, 'RESERVA'), (2, 'SIA')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (1, 'Aprobado'), (0, 'No Aprobado'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_m', 'Reemplazo por Mejora')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(2, 'Reubicación'), (4, 'Reparación'), (3, 'Backup'), (1, 'Dada de Baja'), (5, 'Venta')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('hora', 'Horas'), ('semana', 'Semanas'), ('mes', 'Meses'), ('anio', 'Años'), ('dia', 'Dias')], max_length=7),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (1, 'Aprobado'), (0, 'No Aprobado'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_m', 'Reemplazo por Mejora')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(2, 'Reubicación'), (4, 'Reparación'), (3, 'Backup'), (1, 'Dada de Baja'), (5, 'Venta')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('hora', 'Horas'), ('semana', 'Semanas'), ('mes', 'Meses'), ('anio', 'Años'), ('dia', 'Dias')], max_length=7),
        ),
    ]
