# Generated by Django 3.0.8 on 2021-12-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0053_auto_20211126_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenespedidos',
            name='persona_entrega_en_bodega',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(2, 'SIA'), (3, 'RESERVA'), (1, 'MBA')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (2, 'Anulada'), (0, 'No Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(1, 'Dada de Baja'), (3, 'Backup'), (5, 'Venta'), (2, 'Reubicación'), (4, 'Reparación')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('hora', 'Horas'), ('mes', 'Meses'), ('dia', 'Dias'), ('semana', 'Semanas'), ('anio', 'Años')], max_length=7),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (2, 'Anulada'), (0, 'No Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(1, 'Dada de Baja'), (3, 'Backup'), (5, 'Venta'), (2, 'Reubicación'), (4, 'Reparación')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('hora', 'Horas'), ('mes', 'Meses'), ('dia', 'Dias'), ('semana', 'Semanas'), ('anio', 'Años')], max_length=7),
        ),
    ]
