# Generated by Django 3.0.8 on 2022-01-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0055_auto_20220119_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenespedidos',
            name='descargo_custodio_observa',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(3, 'RESERVA'), (1, 'MBA'), (2, 'SIA')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (2, 'Anulada'), ('', 'Pendiente'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_r', 'Reemplazo por Reparación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(5, 'Venta'), (1, 'Dada de Baja'), (2, 'Reubicación'), (3, 'Backup'), (4, 'Reparación')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('dia', 'Dias'), ('hora', 'Horas'), ('mes', 'Meses'), ('semana', 'Semanas'), ('anio', 'Años')], max_length=7),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (2, 'Anulada'), ('', 'Pendiente'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_r', 'Reemplazo por Reparación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(5, 'Venta'), (1, 'Dada de Baja'), (2, 'Reubicación'), (3, 'Backup'), (4, 'Reparación')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('dia', 'Dias'), ('hora', 'Horas'), ('mes', 'Meses'), ('semana', 'Semanas'), ('anio', 'Años')], max_length=7),
        ),
    ]
