# Generated by Django 3.0.8 on 2022-01-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0056_auto_20220119_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenespedidos',
            name='fecha_descargo_custodiom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(2, 'Reubicación'), (1, 'Dada de Baja'), (4, 'Reparación'), (3, 'Backup'), (5, 'Venta')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('semana', 'Semanas'), ('anio', 'Años'), ('mes', 'Meses'), ('dia', 'Dias'), ('hora', 'Horas')], max_length=7),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(2, 'Reubicación'), (1, 'Dada de Baja'), (4, 'Reparación'), (3, 'Backup'), (5, 'Venta')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('semana', 'Semanas'), ('anio', 'Años'), ('mes', 'Meses'), ('dia', 'Dias'), ('hora', 'Horas')], max_length=7),
        ),
    ]
