# Generated by Django 3.0.8 on 2022-01-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0057_auto_20220119_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenespedidos',
            old_name='fecha_descargo_custodiom',
            new_name='fecha_descargo_custodio',
        ),
        migrations.AlterField(
            model_name='ordenespago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(1, 'MBA'), (3, 'RESERVA'), (2, 'SIA')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_m', 'Reemplazo por Mejora'), ('nuevo', 'Nuevo'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_r', 'Reemplazo por Reparación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(4, 'Reparación'), (1, 'Dada de Baja'), (2, 'Reubicación'), (3, 'Backup'), (5, 'Venta')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('mes', 'Meses'), ('semana', 'Semanas'), ('dia', 'Dias'), ('anio', 'Años'), ('hora', 'Horas')], max_length=7),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_m', 'Reemplazo por Mejora'), ('nuevo', 'Nuevo'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_r', 'Reemplazo por Reparación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(4, 'Reparación'), (1, 'Dada de Baja'), (2, 'Reubicación'), (3, 'Backup'), (5, 'Venta')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('mes', 'Meses'), ('semana', 'Semanas'), ('dia', 'Dias'), ('anio', 'Años'), ('hora', 'Horas')], max_length=7),
        ),
    ]
