# Generated by Django 3.0.3 on 2022-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0061_auto_20220429_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenespago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(3, 'RESERVA'), (2, 'SIA'), (1, 'MBA')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (2, 'Anulada'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_m', 'Reemplazo por Mejora')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(2, 'Reubicación'), (1, 'Dada de Baja'), (5, 'Venta'), (3, 'Backup'), (4, 'Reparación')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('anio', 'Años')], default='anio', max_length=7),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_vida',
            field=models.IntegerField(choices=[(5, '5'), (11, '11'), (18, '18'), (15, '15'), (20, '20'), (19, '19'), (17, '17'), (12, '12'), (7, '7'), (13, '13'), (3, '3'), (8, '8'), (16, '16'), (4, '4'), (1, '1'), (10, '10'), (14, '14'), (9, '9'), (2, '2'), (6, '6')]),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (2, 'Anulada'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_m', 'Reemplazo por Mejora')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(2, 'Reubicación'), (1, 'Dada de Baja'), (5, 'Venta'), (3, 'Backup'), (4, 'Reparación')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='tiempo_tipo',
            field=models.CharField(choices=[('anio', 'Años')], max_length=7),
        ),
    ]
