# Generated by Django 3.0.8 on 2022-06-16 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenPedido', '0062_auto_20220512_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenespago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(2, 'SIA'), (1, 'MBA'), (3, 'RESERVA')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (1, 'Aprobado'), (0, 'No Aprobado'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(3, 'Backup'), (4, 'Reparación'), (5, 'Venta'), (1, 'Dada de Baja'), (2, 'Reubicación')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_vida',
            field=models.IntegerField(choices=[(10, '10'), (7, '7'), (5, '5'), (9, '9'), (19, '19'), (2, '2'), (11, '11'), (14, '14'), (3, '3'), (4, '4'), (12, '12'), (17, '17'), (6, '6'), (13, '13'), (18, '18'), (1, '1'), (8, '8'), (16, '16'), (15, '15'), (20, '20')]),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (1, 'Aprobado'), (0, 'No Aprobado'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(3, 'Backup'), (4, 'Reparación'), (5, 'Venta'), (1, 'Dada de Baja'), (2, 'Reubicación')], null=True),
        ),
        migrations.CreateModel(
            name='ConsultaExperto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pregunta', models.DateTimeField(blank=True, null=True)),
                ('pregunta', models.CharField(blank=True, max_length=5000, null=True)),
                ('respuesta', models.CharField(blank=True, max_length=5000, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('experto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='experto', to=settings.AUTH_USER_MODEL)),
                ('numpedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenPedido.OrdenesPedidos')),
            ],
            options={
                'db_table': 'pedidos"."consulta_experto',
                'managed': True,
            },
        ),
    ]
