# Generated by Django 3.0.8 on 2022-06-17 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenPedido', '0063_auto_20220616_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenespago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(3, 'RESERVA'), (2, 'SIA'), (1, 'MBA')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(2, 'Anulada'), (0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_m', 'Reemplazo por Mejora'), ('nuevo', 'Nuevo'), ('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_o', 'Reemplazo por Obsolescencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(4, 'Reparación'), (3, 'Backup'), (5, 'Venta'), (2, 'Reubicación'), (1, 'Dada de Baja')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_vida',
            field=models.IntegerField(choices=[(19, '19'), (7, '7'), (5, '5'), (10, '10'), (13, '13'), (14, '14'), (2, '2'), (1, '1'), (6, '6'), (16, '16'), (18, '18'), (17, '17'), (4, '4'), (3, '3'), (15, '15'), (20, '20'), (8, '8'), (11, '11'), (9, '9'), (12, '12')]),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(2, 'Anulada'), (0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_m', 'Reemplazo por Mejora'), ('nuevo', 'Nuevo'), ('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_o', 'Reemplazo por Obsolescencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(4, 'Reparación'), (3, 'Backup'), (5, 'Venta'), (2, 'Reubicación'), (1, 'Dada de Baja')], null=True),
        ),
        migrations.CreateModel(
            name='Consultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultadoa', models.ManyToManyField(blank=True, related_name='consultados', to='ordenPedido.ConsultaExperto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidos"."consultados',
                'managed': True,
            },
        ),
    ]
