# Generated by Django 3.0.8 on 2022-06-21 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenPedido', '0067_auto_20220620_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaexperto',
            name='presona_pregunta',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.DO_NOTHING, related_name='realiza_pregunta', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordenespago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(3, 'RESERVA'), (1, 'MBA'), (2, 'SIA')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(2, 'Anulada'), (0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_m', 'Reemplazo por Mejora'), ('nuevo', 'Nuevo'), ('reemplazo_o', 'Reemplazo por Obsolescencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(1, 'Dada de Baja'), (4, 'Reparación'), (2, 'Reubicación'), (3, 'Backup'), (5, 'Venta')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_vida',
            field=models.IntegerField(choices=[(14, '14'), (1, '1'), (16, '16'), (3, '3'), (12, '12'), (5, '5'), (17, '17'), (8, '8'), (9, '9'), (4, '4'), (10, '10'), (2, '2'), (15, '15'), (18, '18'), (13, '13'), (11, '11'), (20, '20'), (6, '6'), (7, '7'), (19, '19')]),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(2, 'Anulada'), (0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_m', 'Reemplazo por Mejora'), ('nuevo', 'Nuevo'), ('reemplazo_o', 'Reemplazo por Obsolescencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(1, 'Dada de Baja'), (4, 'Reparación'), (2, 'Reubicación'), (3, 'Backup'), (5, 'Venta')], null=True),
        ),
    ]
