# Generated by Django 3.0.8 on 2022-06-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0069_auto_20220621_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenespedidos',
            options={'managed': True, 'ordering': ['-numpedido'], 'permissions': (('aprueba_ordenespedidos', 'Aprueba Ordenes de Pedidos'), ('genera_ordenescompra', 'Genera Ordenes de Conpra'), ('activa_activos', 'Activación de Activos'), ('acceso_pedidos', 'Acceso a Pedidos'), ('facturacion', 'Revisión de Facturación'), ('facturas_laboratorio', 'Ingreso de Facturas Laboratorio'), ('preguntas_experto', 'Preguntas Rol Experto')), 'verbose_name': 'Orden Pedido', 'verbose_name_plural': 'Ordenes Pedidos'},
        ),
        migrations.AlterField(
            model_name='ordenespago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(2, 'SIA'), (3, 'RESERVA'), (1, 'MBA')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (2, 'Anulada'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(4, 'Reparación'), (5, 'Venta'), (2, 'Reubicación'), (1, 'Dada de Baja'), (3, 'Backup')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_vida',
            field=models.IntegerField(choices=[(2, '2'), (10, '10'), (12, '12'), (6, '6'), (1, '1'), (16, '16'), (11, '11'), (15, '15'), (5, '5'), (9, '9'), (4, '4'), (18, '18'), (14, '14'), (8, '8'), (20, '20'), (19, '19'), (3, '3'), (7, '7'), (17, '17'), (13, '13')]),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (2, 'Anulada'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(4, 'Reparación'), (5, 'Venta'), (2, 'Reubicación'), (1, 'Dada de Baja'), (3, 'Backup')], null=True),
        ),
    ]
