# Generated by Django 3.0.3 on 2022-07-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrosGlobales', '0017_auto_20220701_1433'),
        ('ordenPedido', '0071_auto_20220701_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenespedidos',
            name='numproyectoconta',
        ),
        migrations.AlterField(
            model_name='ordenespago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(2, 'SIA'), (1, 'MBA'), (3, 'RESERVA')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (2, 'Anulada'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_r', 'Reemplazo por Reparación'), ('nuevo', 'Nuevo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='numproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parametrosGlobales.proyectos_contabilidad'),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(2, 'Reubicación'), (1, 'Dada de Baja'), (4, 'Reparación'), (5, 'Venta'), (3, 'Backup')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_vida',
            field=models.IntegerField(choices=[(15, '15'), (9, '9'), (16, '16'), (1, '1'), (7, '7'), (17, '17'), (11, '11'), (18, '18'), (5, '5'), (13, '13'), (2, '2'), (6, '6'), (10, '10'), (12, '12'), (3, '3'), (19, '19'), (14, '14'), (8, '8'), (20, '20'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (2, 'Anulada'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_r', 'Reemplazo por Reparación'), ('nuevo', 'Nuevo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(2, 'Reubicación'), (1, 'Dada de Baja'), (4, 'Reparación'), (5, 'Venta'), (3, 'Backup')], null=True),
        ),
    ]
