# Generated by Django 3.0.8 on 2022-11-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0072_auto_20220701_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenespedidos',
            name='codigo_activo_reemplazado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(3, 'RESERVA'), (2, 'SIA'), (1, 'MBA')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (2, 'Anulada'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo'), ('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_r', 'Reemplazo por Reparación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(3, 'Backup'), (5, 'Venta'), (1, 'Dada de Baja'), (4, 'Reparación'), (2, 'Reubicación')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_vida',
            field=models.IntegerField(choices=[(8, '8'), (2, '2'), (9, '9'), (13, '13'), (19, '19'), (10, '10'), (11, '11'), (17, '17'), (3, '3'), (4, '4'), (14, '14'), (6, '6'), (15, '15'), (18, '18'), (1, '1'), (7, '7'), (16, '16'), (20, '20'), (5, '5'), (12, '12')]),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (2, 'Anulada'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo'), ('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_r', 'Reemplazo por Reparación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(3, 'Backup'), (5, 'Venta'), (1, 'Dada de Baja'), (4, 'Reparación'), (2, 'Reubicación')], null=True),
        ),
    ]
