# Generated by Django 3.0.8 on 2023-04-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0073_auto_20221115_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='observa_envia_precotiza',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='observa_responde_precotiza',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='ordenespedidos',
            name='estado_precotiza',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenespedidos',
            name='estado_responde_precotiza',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenespedidos',
            name='fchprecotiza',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenespedidos',
            name='fchpreresponde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenespedidos',
            name='usuario_precotiza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(2, 'SIA'), (3, 'RESERVA'), (1, 'MBA')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(3, 'Backup'), (4, 'Reparación'), (5, 'Venta'), (2, 'Reubicación'), (1, 'Dar de Baja')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_vida',
            field=models.IntegerField(choices=[(12, '12'), (11, '11'), (19, '19'), (4, '4'), (15, '15'), (9, '9'), (3, '3'), (5, '5'), (14, '14'), (13, '13'), (2, '2'), (6, '6'), (18, '18'), (17, '17'), (1, '1'), (8, '8'), (7, '7'), (20, '20'), (16, '16'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(3, 'Backup'), (4, 'Reparación'), (5, 'Venta'), (2, 'Reubicación'), (1, 'Dar de Baja')], null=True),
        ),
        migrations.CreateModel(
            name='PreCotiza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivos', models.FileField(blank=True, null=True, upload_to='cotizaciones/')),
                ('nombre_corto', models.CharField(blank=True, max_length=1000, null=True)),
                ('seleccion', models.BooleanField(blank=True, null=True)),
                ('fecha_pre_cotiza', models.DateField(auto_now_add=True)),
                ('escrito', models.BooleanField(blank=True, null=True)),
                ('numtrabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ordenPedido.OrdenesPedidos')),
            ],
            options={
                'db_table': 'pedidos"."pre_cotiza_activos',
                'managed': True,
            },
        ),
    ]
