# Generated by Django 3.2.15 on 2023-10-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenPedido', '0075_auto_20230421_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='otros_doc',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='otros_doc/', verbose_name='Otros Documentos'),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (2, 'Anulada'), (1, 'Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(2, 'Reubicación'), (5, 'Venta'), (4, 'Reparación'), (3, 'Backup'), (1, 'Dar de Baja')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidos',
            name='tiempo_vida',
            field=models.IntegerField(choices=[(9, '9'), (17, '17'), (11, '11'), (10, '10'), (8, '8'), (16, '16'), (22, '22'), (23, '23'), (18, '18'), (4, '4'), (19, '19'), (1, '1'), (6, '6'), (7, '7'), (21, '21'), (24, '24'), (25, '25'), (13, '13'), (3, '3'), (12, '12'), (5, '5'), (14, '14'), (2, '2'), (15, '15'), (20, '20')]),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (2, 'Anulada'), (1, 'Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='motivo_compra',
            field=models.CharField(choices=[('reemplazo_r', 'Reemplazo por Reparación'), ('reemplazo_m', 'Reemplazo por Mejora'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rechazaordenespedidos',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(2, 'Reubicación'), (5, 'Venta'), (4, 'Reparación'), (3, 'Backup'), (1, 'Dar de Baja')], null=True),
        ),
    ]
