# Generated by Django 5.0.1 on 2024-01-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicita_puestos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='motivo',
        ),
        migrations.AddField(
            model_name='solicita_puesto',
            name='motivo',
            field=models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('reemplazo', 'Reemplazo')], default='nuevo', null=True),
        ),
        migrations.AlterField(
            model_name='solicita_puesto',
            name='estado_aprobacion',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (2, 'Anulada'), (1, 'Aprobado'), (0, 'No Aprobado')], null=True),
        ),
    ]
