# Generated by Django 5.0.1 on 2024-01-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicita_puestos', '0002_delete_motivo_solicita_puesto_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicita_puesto',
            name='fecha_aprueba',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicita_puesto',
            name='usuario_aprueba',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicita_puesto',
            name='estado_aprobacion',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (1, 'Aprobado'), (2, 'Anulada'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicita_puesto',
            name='motivo',
            field=models.CharField(blank=True, choices=[('reemplazo', 'Reemplazo'), ('nuevo', 'Nuevo')], default='nuevo', null=True),
        ),
    ]
