# Generated by Django 5.0.1 on 2024-01-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicita_puestos', '0003_solicita_puesto_fecha_aprueba_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicita_puesto',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='solicita_puesto',
            name='estado_aprobacion',
            field=models.IntegerField(blank=True, choices=[(2, 'Anulada'), (0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicita_puesto',
            name='motivo',
            field=models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('reemplazo', 'Reemplazo')], default='nuevo', null=True),
        ),
    ]
