# Generated by Django 5.0.1 on 2024-01-04 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicita_puestos', '0004_cargo_remove_solicita_puesto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicita_puesto',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='solicita_puestos.cargo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicita_puesto',
            name='estado_aprobacion',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (2, 'Anulada'), (1, 'Aprobado')], null=True),
        ),
    ]
