# Generated by Django 5.0.1 on 2024-01-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicita_puestos', '0005_solicita_puesto_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicita_puesto',
            name='cargo',
        ),
        migrations.AddField(
            model_name='solicita_puesto',
            name='estado_ingreso',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado'), (2, 'Anulada')], null=True),
        ),
        migrations.AddField(
            model_name='solicita_puesto',
            name='motRechaza',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='solicita_puesto',
            name='notasges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicita_puesto',
            name='estado_aprobacion',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicita_puesto',
            name='motivo',
            field=models.CharField(blank=True, choices=[('reemplazo', 'Reemplazo'), ('nuevo', 'Nuevo')], default='nuevo', null=True),
        ),
    ]
