# Generated by Django 5.0.1 on 2024-01-10 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicita_puestos', '0006_remove_solicita_puesto_cargo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicita_puesto',
            name='estado_aprobacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (2, 'Anulada'), (0, 'No Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicita_puesto',
            name='estado_ingreso',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (2, 'Anulada'), (0, 'No Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicita_puesto',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
