# Generated by Django 5.0.1 on 2024-01-15 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='activo_depar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_nombre', models.CharField(max_length=50, null=True)),
                ('dep_estado', models.IntegerField(blank=True)),
                ('autoriza_salida', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='activo_ubica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubica_nombre', models.CharField(max_length=50, null=True)),
                ('ubica_estado', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='activo_areas',
            fields=[
                ('area_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('area_nombre', models.CharField(max_length=50, null=True)),
                ('area_estado', models.IntegerField(blank=True)),
                ('area_ubica', models.IntegerField(blank=True, null=True)),
                ('area_departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solicita_puestos.activo_depar')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitaPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=20)),
                ('motivo', models.CharField(blank=True, choices=[('reemplazo', 'Reemplazo'), ('nuevo', 'Nuevo')], default='nuevo', null=True)),
                ('justificacion', models.CharField(blank=True, max_length=255)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprueba', models.DateTimeField(blank=True, null=True)),
                ('usuario_aprueba', models.CharField(blank=True, max_length=50, null=True)),
                ('motRechaza', models.CharField(blank=True, max_length=250, null=True)),
                ('estado_aprobacion', models.IntegerField(blank=True, choices=[(2, 'Anulada'), ('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True)),
                ('notasges', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_ingreso', models.IntegerField(blank=True, choices=[(2, 'Anulada'), ('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solicita_puestos.activo_areas')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solicita_puestos.activo_depar')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solicita_puestos.activo_ubica')),
            ],
            options={
                'db_table': 'solicita_puesto',
            },
        ),
    ]
