# Generated by Django 5.0.1 on 2024-01-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicita_puestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitapuesto',
            name='observacion_aprueba',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitapuesto',
            name='estado_aprobacion',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (2, 'Anulada'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitapuesto',
            name='estado_ingreso',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (2, 'Anulada'), (1, 'Aprobado')], null=True),
        ),
    ]
