# Generated by Django 5.0.1 on 2024-01-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicita_puestos', '0002_solicitapuesto_observacion_aprueba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitapuesto',
            name='fecha_aprueba_rrhh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitapuesto',
            name='estado_aprobacion',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (1, 'Aprobado'), (2, 'Anulada'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitapuesto',
            name='estado_ingreso',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (1, 'Aprobado'), (2, 'Anulada'), (0, 'No Aprobado')], null=True),
        ),
    ]
