# Generated by Django 5.0.1 on 2024-01-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicita_puestos', '0003_solicitapuesto_fecha_aprueba_rrhh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitapuesto',
            name='usuario_aprueba_rrhh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitapuesto',
            name='estado_aprobacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (0, 'No Aprobado'), ('', 'Pendiente'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitapuesto',
            name='estado_ingreso',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (0, 'No Aprobado'), ('', 'Pendiente'), (2, 'Anulada')], null=True),
        ),
    ]
