# Generated by Django 5.0.1 on 2024-01-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicita_puestos', '0004_solicitapuesto_usuario_aprueba_rrhh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitapuesto',
            name='fecha_inicio_proceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitapuesto',
            name='estado_aprobacion',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (2, 'Anulada'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitapuesto',
            name='estado_ingreso',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (2, 'Anulada'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitapuesto',
            name='motivo',
            field=models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('reemplazo', 'Reemplazo')], default='nuevo', null=True),
        ),
    ]
