# Generated by Django 3.0 on 2020-05-21 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedores', '0024_auto_20200521_1319'),
        ('activos', '0029_auto_20200521_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenesTrabajos',
            fields=[
                ('numtrabajo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_trabajo', models.IntegerField(choices=[(1, 'Interno'), (2, 'Externo')])),
                ('usuario_aprueba', models.CharField(blank=True, max_length=100, null=True)),
                ('aprobado', models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (0, 'No Aprobado'), ('', 'Pendiente')], null=True)),
                ('observa_selec_cot', models.CharField(blank=True, max_length=250, null=True)),
                ('fchsolicita', models.DateField(auto_now_add=True)),
                ('fchsolicitatxt', models.CharField(blank=True, max_length=8, null=True)),
                ('numproyecto', models.CharField(blank=True, max_length=70, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('fchaprueba', models.DateField(auto_now=True, null=True)),
                ('fchapruebatxt', models.CharField(blank=True, max_length=8, null=True)),
                ('motRechaza', models.CharField(blank=True, max_length=250, null=True)),
                ('estado_cotiza', models.BooleanField(blank=True, null=True)),
                ('cotiza_observa', models.CharField(blank=True, max_length=250, null=True)),
                ('select_cotiza', models.BooleanField(blank=True, max_length=250, null=True)),
                ('genera_compra', models.IntegerField(blank=True, null=True)),
                ('observa_compra', models.CharField(blank=True, max_length=250, null=True)),
                ('justificacion_compra', models.CharField(blank=True, max_length=250, null=True)),
                ('activado_activo', models.BooleanField(blank=True, null=True)),
                ('activado_observa', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_activacion', models.DateField(blank=True, null=True)),
                ('recibido_bodega', models.BooleanField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('codigo_genera', models.BooleanField(blank=True, null=True)),
                ('entregado_bodega', models.BooleanField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('entrega_observa', models.CharField(blank=True, max_length=250, null=True)),
                ('ord', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_areas')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_depar')),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden Trabajo',
                'verbose_name_plural': 'Ordenes Trabajos',
                'db_table': 'pedidos"."ordenestrabajos',
                'permissions': (('acceso_ordenes', 'Acceso a Ordenes'),),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('unimedida', models.CharField(blank=True, choices=[('unidad', 'Unidad')], max_length=15, null=True)),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='img_pedidos/', verbose_name='Imagen 1')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='img_pedidos/', verbose_name='Imagen 2')),
                ('cotiza_Ref', models.FileField(blank=True, null=True, upload_to='cotizaciones/', verbose_name='Cotización Referencial')),
                ('numtrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenTrabajo.OrdenesTrabajos')),
            ],
            options={
                'verbose_name': 'Detalle Trabajo',
                'verbose_name_plural': 'Detalles Trabajos',
                'db_table': 'pedidos"."detalletrabajo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CotizaTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('pdf_cotiza', models.FileField(blank=True, null=True, upload_to='cotizaciones/', verbose_name='Cotización')),
                ('cotiza_seleccion', models.BooleanField(blank=True, null=True, verbose_name='Selección')),
                ('empresa_cotiza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proveedores.proveedor', verbose_name='Proveedor')),
                ('numtrabajos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenTrabajo.OrdenesTrabajos')),
            ],
            options={
                'verbose_name': 'Cotización Trabajo',
                'verbose_name_plural': 'Cotizaciones Trabajos',
                'db_table': 'pedidos"."cotizatrabajo',
                'permissions': (('selecciona_cotizatrabajo', 'Seleccionar Cotizaciones Trabajos'),),
                'managed': True,
            },
        ),
    ]
