# Generated by Django 3.0 on 2020-05-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizatrabajo',
            old_name='numtrabajos',
            new_name='numtrabajo',
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(choices=[(1, 'Interno'), (2, 'Externo')], default=None),
        ),
    ]
