# Generated by Django 3.0 on 2020-05-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0003_auto_20200522_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenestrabajos',
            name='compra_directa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='tipo_liquida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('MC', 'Mantenimiento Correctivo'), ('OT', 'Otros'), ('MP', 'Mantenimiento Preventivo'), ('PR', 'Proyecto')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente')], null=True),
        ),
    ]
