# Generated by Django 3.0 on 2020-06-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0004_auto_20200526_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenestrabajos',
            name='total_observa',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (0, 'No Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='entrega_observa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('PR', 'Proyecto'), ('MC', 'Mantenimiento Correctivo'), ('OT', 'Otros'), ('MP', 'Mantenimiento Preventivo')], default=None, max_length=2, null=True),
        ),
    ]
