# Generated by Django 3.0 on 2020-06-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0005_auto_20200602_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenestrabajos',
            name='fchactivatxt',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='fchcotiza',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='fchcotizatxt',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='fchengtregatxt',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='fchgenerac',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='fchgeneractxt',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='fchrecibetxt',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='orden_referencial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='usuario_cotiza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='usuario_genera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='usuario_recibe',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('OT', 'Otros Insumos'), ('PR', 'Proyecto'), ('MC', 'Mantenimiento Correctivo'), ('MP', 'Mantenimiento Preventivo'), ('OS', 'Orden de Servicio')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(1, 'Interno'), (2, 'Externo')], default=None, null=True),
        ),
    ]
