# Generated by Django 3.0 on 2020-06-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0007_auto_20200611_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='orden_referencial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('OS', 'Orden de Servicio'), ('MP', 'Mantenimiento Preventivo'), ('OT', 'Otros Insumos'), ('MC', 'Mantenimiento Correctivo'), ('PR', 'Proyecto')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(1, 'Interno'), (2, 'Externo')], default=None, null=True),
        ),
    ]
