# Generated by Django 3.0 on 2020-06-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0011_auto_20200612_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='orden_referencial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('OS', 'Orden de Servicio'), ('MC', 'Mantenimiento Correctivo'), ('PR', 'Proyecto'), ('MP', 'Mantenimiento Preventivo'), ('OT', 'Otros Insumos')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(2, 'Externo'), (1, 'Interno')], default=None, null=True),
        ),
    ]
