# Generated by Django 3.0 on 2020-06-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0012_auto_20200612_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (0, 'No Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('OS', 'Orden de Servicio'), ('OT', 'Otros Insumos'), ('PR', 'Proyecto'), ('MP', 'Mantenimiento Preventivo'), ('MC', 'Mantenimiento Correctivo')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(1, 'Interno'), (2, 'Externo')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='usuario_aprueba',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
