# Generated by Django 3.0 on 2020-06-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0013_auto_20200615_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('OT', 'Otros Insumos'), ('MP', 'Mantenimiento Preventivo'), ('OS', 'Orden de Servicio'), ('PR', 'Proyecto'), ('MC', 'Mantenimiento Correctivo')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='usuario_aprueba',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
