# Generated by Django 3.0.7 on 2020-06-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0015_auto_20200615_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalletrabajo',
            name='cotiza_Ref',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='cotizaciones/', verbose_name='Cotización Referencial'),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('MC', 'Mantenimiento Correctivo'), ('OT', 'Otros Insumos'), ('PR', 'Proyecto'), ('MP', 'Mantenimiento Preventivo'), ('OS', 'Orden de Servicio')], default=None, max_length=2, null=True),
        ),
    ]
