# Generated by Django 3.0.7 on 2020-07-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0017_auto_20200701_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenestrabajos',
            name='grupo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='ubica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True),
        ),
    ]
