# Generated by Django 3.0.7 on 2020-07-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0019_auto_20200713_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenestrabajos',
            name='entrega_solicita',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (0, 'No Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('MC', 'Mantenimiento Correctivo'), ('PR', 'Proyecto'), ('MP', 'Mantenimiento Preventivo'), ('OT', 'Otros Insumos'), ('OS', 'Orden de Servicio')], default=None, max_length=2, null=True),
        ),
    ]
