# Generated by Django 3.0.7 on 2020-07-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0038_auto_20200721_0939'),
        ('ordenTrabajo', '0020_auto_20200713_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('PR', 'Proyecto'), ('OS', 'Orden de Servicio'), ('MC', 'Mantenimiento Correctivo'), ('MP', 'Mantenimiento Preventivo'), ('OT', 'Otros Insumos')], default=None, max_length=2, null=True),
        ),
    ]
