# Generated by Django 3.0.7 on 2020-07-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0021_auto_20200721_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenestrabajos',
            name='aceptacion_factura',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='valor_factura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (1, 'Aprobado'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('PR', 'Proyecto'), ('MC', 'Mantenimiento Correctivo'), ('MP', 'Mantenimiento Preventivo'), ('OS', 'Orden de Servicio'), ('OT', 'Otros Insumos')], default=None, max_length=2, null=True),
        ),
    ]
