# Generated by Django 3.0.7 on 2020-08-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0023_auto_20200731_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='cotiza_observa',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('MP', 'Mantenimiento Preventivo'), ('PR', 'Proyecto'), ('CT', 'Cotización'), ('MC', 'Mantenimiento Correctivo'), ('OT', 'Otros Insumos'), ('OS', 'Orden de Servicio')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(1, 'Interno'), (2, 'Externo')], default=None, null=True),
        ),
    ]
