# Generated by Django 3.0.7 on 2020-09-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0024_auto_20200821_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('OS', 'Orden de Servicio'), ('MP', 'Mantenimiento Preventivo'), ('MC', 'Mantenimiento Correctivo'), ('OT', 'Otros Insumos'), ('PR', 'Proyecto')], default=None, max_length=2, null=True),
        ),
    ]
