# Generated by Django 3.0.7 on 2020-09-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0025_auto_20200901_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='activado_observa',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (1, 'Aprobado'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='cotiza_observa',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='entrega_observa',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='observa_compra',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='observa_selec_cot',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('MP', 'Mantenimiento Preventivo'), ('PR', 'Proyecto'), ('OS', 'Orden de Servicio'), ('OT', 'Otros Insumos'), ('MC', 'Mantenimiento Correctivo')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(2, 'Externo'), (1, 'Interno')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='total_observa',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
