# Generated by Django 3.0.7 on 2020-12-11 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenTrabajo', '0027_auto_20201210_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('PR', 'Proyecto'), ('MC', 'Mantenimiento Correctivo'), ('OS', 'Orden de Servicio'), ('OT', 'Otros Insumos'), ('MP', 'Mantenimiento Preventivo')], default=None, max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='PedidosMba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentos', models.FileField(blank=True, max_length=500, null=True, upload_to='cotizaciones/', verbose_name='Cotización Referencial')),
                ('fch_carga', models.DateField(blank=True, null=True)),
                ('fch_carga_txt', models.CharField(blank=True, max_length=8, null=True)),
                ('estado_gestion', models.BooleanField(blank=True, null=True)),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido MBA',
                'verbose_name_plural': 'Pedidos MBA',
                'db_table': 'pedidos"."pedidos_mba',
                'permissions': (('ingreso_pedidos_mba', 'Ingreso de Pedidos MBA'),),
                'managed': True,
            },
        ),
    ]
