# Generated by Django 3.0.7 on 2020-12-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0028_auto_20201211_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('PR', 'Proyecto'), ('OT', 'Otros Insumos'), ('MC', 'Mantenimiento Correctivo'), ('MP', 'Mantenimiento Preventivo'), ('OS', 'Orden de Servicio')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(1, 'Interno'), (2, 'Externo')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pedidosmba',
            name='documentos',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='documentos_mba/', verbose_name='Documentos MBA'),
        ),
    ]
