# Generated by Django 3.0.7 on 2020-12-11 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenTrabajo', '0029_auto_20201211_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('PR', 'Proyecto'), ('OT', 'Otros Insumos'), ('OS', 'Orden de Servicio'), ('MP', 'Mantenimiento Preventivo'), ('MC', 'Mantenimiento Correctivo')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pedidosmba',
            name='usuario_solicita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
