# Generated by Django 3.0.7 on 2020-12-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0030_auto_20201211_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosmba',
            name='ordenar',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (0, 'No Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('OS', 'Orden de Servicio'), ('OT', 'Otros Insumos'), ('PR', 'Proyecto'), ('MC', 'Mantenimiento Correctivo'), ('MP', 'Mantenimiento Preventivo')], default=None, max_length=2, null=True),
        ),
    ]
