# Generated by Django 3.0.7 on 2020-12-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0031_auto_20201217_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('MP', 'Mantenimiento Preventivo'), ('PR', 'Proyecto'), ('MC', 'Mantenimiento Correctivo'), ('OT', 'Otros Insumos'), ('OS', 'Orden de Servicio')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pedidosmba',
            name='ordenar',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
