# Generated by Django 3.0.7 on 2021-01-20 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenTrabajo', '0032_auto_20201217_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('MC', 'Mantenimiento Correctivo'), ('PR', 'Proyecto'), ('MP', 'Mantenimiento Preventivo'), ('OT', 'Otros Insumos'), ('OS', 'Orden de Servicio')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(2, 'Externo'), (1, 'Interno')], default=None, null=True),
        ),
        migrations.CreateModel(
            name='TrabajosPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fch_genera', models.DateField(blank=True, null=True)),
                ('fch_genera_txt', models.CharField(blank=True, max_length=8, null=True)),
                ('origen', models.IntegerField(blank=True, choices=[(2, 'SIA'), (1, 'MBA'), (3, 'RESERVA')], null=True)),
                ('numero', models.CharField(blank=True, max_length=25, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='pagos/', verbose_name='Pagos')),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('observaciones_adqui', models.CharField(blank=True, max_length=2500, null=True)),
                ('observaciones_ga', models.CharField(blank=True, max_length=2500, null=True)),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Pago de Trabajo',
                'verbose_name_plural': 'Ordenes de Pagos de Trabajos',
                'db_table': 'pedidos"."trabajospago',
                'managed': True,
            },
        ),
    ]
