# Generated by Django 3.0.7 on 2021-04-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0035_auto_20210325_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalletrabajo',
            name='otros_doc',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='otros_doc/', verbose_name='Otros Documentos'),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('OT', 'Otros Insumos'), ('MP', 'Mantenimiento Preventivo'), ('MC', 'Mantenimiento Correctivo'), ('PR', 'Proyecto'), ('OS', 'Orden de Servicio')], default=None, max_length=2, null=True),
        ),
    ]
