# Generated by Django 3.0.7 on 2021-04-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0036_auto_20210412_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPedido',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Pedido',
                'verbose_name_plural': 'Tipos Pedidos',
                'db_table': 'pedidos"."tipopedido',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.CharField(blank=True, choices=[('PR', 'Proyecto'), ('OT', 'Otros Insumos'), ('OS', 'Orden de Servicio'), ('MP', 'Mantenimiento Preventivo'), ('MC', 'Mantenimiento Correctivo')], default=None, max_length=2, null=True),
        ),
    ]
