# Generated by Django 3.0.7 on 2021-04-14 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0038_auto_20210413_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (0, 'No Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_pedi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ordenTrabajo.TipoPedido'),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(3, 'RESERVA'), (1, 'MBA'), (2, 'SIA')], null=True),
        ),
    ]
