# Generated by Django 3.0.7 on 2021-04-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0040_auto_20210415_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='estado_cotiza',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
