# Generated by Django 3.0.7 on 2021-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0041_auto_20210416_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='fchaprueba',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='fchcotiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='fchgenerac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(1, 'Interno'), (2, 'Externo')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(2, 'SIA'), (1, 'MBA'), (3, 'RESERVA')], null=True),
        ),
    ]
