# Generated by Django 3.0.7 on 2021-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0043_auto_20210510_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenestrabajos',
            options={'managed': True, 'permissions': (('acceso_ordenes', 'Acceso a Ordenes'), ('supervisa_ordenes', 'Supervisión de Ordenes'), ('supervisa_ordenes_ga', 'Supervisión de Ordenes GA')), 'verbose_name': 'Orden Trabajo', 'verbose_name_plural': 'Ordenes Trabajos'},
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(2, 'Externo'), (1, 'Interno')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(1, 'MBA'), (2, 'SIA'), (3, 'RESERVA')], null=True),
        ),
    ]
