# Generated by Django 3.0.7 on 2021-05-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0044_auto_20210513_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenestrabajos',
            options={'managed': True, 'permissions': (('acceso_ordenes', 'Acceso a Ordenes'), ('supervisa_ordenes', 'Supervisión de Ordenes'), ('supervisa_ordenes_ga', 'Supervisión de Ordenes GA'), ('supervisa_ordenes2', 'Supervisión de Ordenes 2')), 'verbose_name': 'Orden Trabajo', 'verbose_name_plural': 'Ordenes Trabajos'},
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(2, 'SIA'), (3, 'RESERVA'), (1, 'MBA')], null=True),
        ),
    ]
