# Generated by Django 3.0.8 on 2022-01-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0049_auto_20211015_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenestrabajos',
            name='fchselectcotiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='fchselectcotizatxt',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='detalletrabajo',
            name='numtrabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camello', to='ordenTrabajo.OrdenesTrabajos'),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (0, 'No Aprobado'), ('', 'Pendiente'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(1, 'MBA'), (2, 'SIA'), (3, 'RESERVA')], null=True),
        ),
    ]
