# Generated by Django 3.0.8 on 2022-06-27 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenTrabajo', '0053_auto_20220627_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (2, 'Anulada'), ('', 'Pendiente'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(1, 'Interno'), (2, 'Externo')], default=None, null=True),
        ),
        migrations.CreateModel(
            name='ConsultaExpertoTrab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pregunta', models.DateTimeField(blank=True, null=True)),
                ('pregunta', models.CharField(blank=True, max_length=5000, null=True)),
                ('respuesta', models.CharField(blank=True, max_length=5000, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('numtrabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenTrabajo.OrdenesTrabajos')),
                ('persona_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='realiza_pregunta_trab', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidos"."consulta_experto_trab',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConsultadosTrab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultadoa', models.ManyToManyField(blank=True, related_name='consul_trab', to='ordenTrabajo.ConsultaExpertoTrab')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidos"."consultados_trab',
                'managed': True,
            },
        ),
    ]
