# Generated by Django 3.0.8 on 2022-07-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0057_auto_20220701_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenestrabajos',
            options={'managed': True, 'permissions': (('acceso_ordenes', 'Acceso a Ordenes'), ('supervisa_ordenes', 'Supervisión de Ordenes'), ('supervisa_ordenes_ga', 'Supervisión de Ordenes GA'), ('supervisa_ordenes2', 'Supervisión de Ordenes 2'), ('reporte_ga', 'Reporte GA'), ('reporte_requisiciones_por_proyecto', 'Reporte Proyectos')), 'verbose_name': 'Orden Trabajo', 'verbose_name_plural': 'Ordenes Trabajos'},
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(2, 'Anulada'), (1, 'Aprobado'), ('', 'Pendiente'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(1, 'Interno'), (2, 'Externo')], default=None, null=True),
        ),
    ]
