# Generated by Django 3.0.8 on 2023-04-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0058_auto_20220706_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCotiza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivos', models.FileField(blank=True, null=True, upload_to='pre_cotiza/')),
                ('nombre_corto', models.CharField(blank=True, max_length=1000, null=True)),
                ('observa_adqui', models.CharField(blank=True, max_length=20000, null=True)),
                ('observa_solicita', models.CharField(blank=True, max_length=20000, null=True)),
                ('fecha_pre_cotiza', models.DateTimeField(blank=True, null=True)),
                ('fecha_pre_responde', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedidos"."pre_cotiza_trab',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (2, 'Anulada'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.CreateModel(
            name='PreCotizaDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivos', models.FileField(blank=True, null=True, upload_to='pre_cotiza/')),
                ('nombre_corto', models.CharField(blank=True, max_length=1000, null=True)),
                ('observa_adqui', models.CharField(blank=True, max_length=20000, null=True)),
                ('observa_solicita', models.CharField(blank=True, max_length=20000, null=True)),
                ('fecha_pre_cotiza', models.DateTimeField(blank=True, null=True)),
                ('fecha_pre_responde', models.DateTimeField(blank=True, null=True)),
                ('numtrabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ordenTrabajo.PreCotiza')),
            ],
            options={
                'db_table': 'pedidos"."pre_cotiza_trab_det',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='precotiza',
            name='numtrabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ordenTrabajo.OrdenesTrabajos'),
        ),
    ]
