# Generated by Django 3.0.8 on 2023-04-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0059_auto_20230410_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenestrabajos',
            name='estado_precotiza',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='estado_responde_precotiza',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajos',
            name='fchprecotiza',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), (0, 'No Aprobado'), (2, 'Anulada'), ('', 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(3, 'RESERVA'), (1, 'MBA'), (2, 'SIA')], null=True),
        ),
    ]
