# Generated by Django 3.0.8 on 2023-04-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0062_auto_20230414_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precotiza',
            name='fecha_pre_cotiza',
        ),
        migrations.RemoveField(
            model_name='precotiza',
            name='fecha_pre_responde',
        ),
        migrations.RemoveField(
            model_name='precotiza',
            name='observa_adqui',
        ),
        migrations.RemoveField(
            model_name='precotiza',
            name='observa_solicita',
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(2, 'Anulada'), (0, 'No Aprobado'), ('', 'Pendiente'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(2, 'Externo'), (1, 'Interno')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(3, 'RESERVA'), (2, 'SIA'), (1, 'MBA')], null=True),
        ),
    ]
