# Generated by Django 3.0.8 on 2023-04-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0063_auto_20230414_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (1, 'Aprobado'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(1, 'MBA'), (3, 'RESERVA'), (2, 'SIA')], null=True),
        ),
    ]
