# Generated by Django 3.0.8 on 2023-04-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0065_auto_20230419_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalletrabajo',
            name='observa_envia_precotiza',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='detalletrabajo',
            name='observa_responde_precotiza',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(2, 'Externo'), (1, 'Interno')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(3, 'RESERVA'), (1, 'MBA'), (2, 'SIA')], null=True),
        ),
    ]
