# Generated by Django 3.0.8 on 2023-04-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0066_auto_20230419_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenestrabajos',
            name='fchpreresponde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (2, 'Anulada'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
    ]
