# Generated by Django 3.0.8 on 2023-04-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0067_auto_20230419_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenestrabajos',
            name='usuario_anula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (2, 'Anulada'), ('', 'Pendiente'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(1, 'Interno'), (2, 'Externo')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(2, 'SIA'), (1, 'MBA'), (3, 'RESERVA')], null=True),
        ),
    ]
