# Generated by Django 3.2.15 on 2023-11-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0069_auto_20231020_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenestrabajos',
            name='insumos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (1, 'Aprobado'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(3, 'RESERVA'), (2, 'SIA'), (1, 'MBA')], null=True),
        ),
    ]
