# Generated by Django 3.2.15 on 2023-12-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0071_auto_20231214_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesadqui',
            name='anula',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente'), (2, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='aprobado_cont',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), (1, 'Aprobado'), ('', 'Pendiente'), (2, 'Anulada')], null=True),
        ),
    ]
