# Generated by Django 3.2.15 on 2023-12-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0072_auto_20231214_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesadqui',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='otros_doc/', verbose_name='Anticipos'),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(2, 'Externo'), (1, 'Interno')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(2, 'SIA/ACTIVOS'), (1, 'MBA'), (3, 'SIA/TRABAJOS')], null=True),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(2, 'SIA/ACTIVOS'), (1, 'MBA'), (3, 'SIA/TRABAJOS')], null=True),
        ),
    ]
