# Generated by Django 3.2.15 on 2023-12-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0073_auto_20231218_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesadqui',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada Ger'), (4, 'Rechazada Conta'), (2, 'Gestionado Conta'), (0, 'Pendiente'), (1, 'Aprobado Ger')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='tipo_trabajo',
            field=models.IntegerField(blank=True, choices=[(1, 'Interno'), (2, 'Externo')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada Ger'), (4, 'Rechazada Conta'), (2, 'Gestionado Conta'), (0, 'Pendiente'), (1, 'Aprobado Ger')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='aprobado_cont',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada Ger'), (4, 'Rechazada Conta'), (2, 'Gestionado Conta'), (0, 'Pendiente'), (1, 'Aprobado Ger')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(2, 'SIA/ACTIVOS'), (3, 'SIA/TRABAJOS'), (1, 'MBA')], null=True),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(2, 'SIA/ACTIVOS'), (3, 'SIA/TRABAJOS'), (1, 'MBA')], null=True),
        ),
    ]
