# Generated by Django 3.2.15 on 2023-12-20 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenTrabajo', '0074_auto_20231219_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(4, 'Rechazada Conta'), (2, 'Gestionado Conta'), (0, 'Pendiente'), (3, 'Rechazada Ger'), (1, 'Aprobado Ger')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(4, 'Rechazada Conta'), (2, 'Gestionado Conta'), (0, 'Pendiente'), (3, 'Rechazada Ger'), (1, 'Aprobado Ger')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='aprobado_cont',
            field=models.IntegerField(blank=True, choices=[(4, 'Rechazada Conta'), (2, 'Gestionado Conta'), (0, 'Pendiente'), (3, 'Rechazada Ger'), (1, 'Aprobado Ger')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='pgestiona_cont',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pgestiona', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='usuario_aprueba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paprueba', to=settings.AUTH_USER_MODEL),
        ),
    ]
