# Generated by Django 3.2.15 on 2023-12-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0075_auto_20231220_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesadqui',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='otros_doc/', verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado Ger'), (3, 'Rechazada Ger'), (2, 'Gestionado Conta'), (0, 'Pendiente'), (4, 'Rechazada Conta')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'SI')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado Ger'), (3, 'Rechazada Ger'), (2, 'Gestionado Conta'), (0, 'Pendiente'), (4, 'Rechazada Conta')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='aprobado_cont',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado Ger'), (3, 'Rechazada Ger'), (2, 'Gestionado Conta'), (0, 'Pendiente'), (4, 'Rechazada Conta')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(3, 'SIA/TRABAJOS'), (2, 'SIA/ACTIVOS'), (1, 'MBA')], null=True),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(3, 'SIA/TRABAJOS'), (2, 'SIA/ACTIVOS'), (1, 'MBA')], null=True),
        ),
    ]
