# Generated by Django 3.2.15 on 2023-12-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenTrabajo', '0077_auto_20231221_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudesadqui',
            name='aprobado',
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(2, 'Gestionado Conta'), (3, 'Rechazada Ger'), (4, 'Rechazada Conta'), (0, 'Pendiente'), (1, 'Aprobado Ger')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='refer_orden',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajos',
            name='salida_activo',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='aprobado_cont',
            field=models.IntegerField(blank=True, choices=[(2, 'Gestionado Conta'), (3, 'Rechazada Ger'), (4, 'Rechazada Conta'), (0, 'Pendiente'), (1, 'Aprobado Ger')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesadqui',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(3, 'SIA/TRABAJOS'), (2, 'SIA/ACTIVOS'), (1, 'MBA')], null=True),
        ),
        migrations.AlterField(
            model_name='trabajospago',
            name='origen',
            field=models.IntegerField(blank=True, choices=[(3, 'SIA/TRABAJOS'), (2, 'SIA/ACTIVOS'), (1, 'MBA')], null=True),
        ),
    ]
