# Generated by Django 5.0.1 on 2024-01-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puestos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='activo_areas',
        ),
        migrations.DeleteModel(
            name='activo_depar',
        ),
        migrations.DeleteModel(
            name='activo_ubica',
        ),
    ]
