# Generated by Django 5.0.1 on 2024-01-02 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puestos', '0002_delete_activo_areas_delete_activo_depar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='activo_depar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_nombre', models.CharField(max_length=50, null=True)),
                ('dep_estado', models.IntegerField(blank=True)),
                ('autoriza_salida', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='activo_ubica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubica_nombre', models.CharField(max_length=50, null=True)),
                ('ubica_estado', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='solicita_puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('justificacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='activo_areas',
            fields=[
                ('area_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('area_nombre', models.CharField(max_length=50, null=True)),
                ('area_estado', models.IntegerField(blank=True)),
                ('area_ubica', models.IntegerField(blank=True, null=True)),
                ('area_departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='puestos.activo_depar')),
            ],
        ),
    ]
