# Generated by Django 5.0.1 on 2024-01-27 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='activo_areas',
            fields=[
                ('area_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('area_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('area_estado', models.IntegerField(blank=True, null=True)),
                ('area_departamento', models.IntegerField(blank=True, null=True)),
                ('area_ubica', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activos"."activo_areas',
                'ordering': ['area_nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CabRegistroAccesoUbica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('completado', models.IntegerField(choices=[(2, 'No Registrado'), (1, 'Completo'), (3, 'Incompleto'), (0, 'Pendiente')], default=0)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procesos"."cab_registro_acceso_ubicacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CodigoQrAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.IntegerField(blank=True, choices=[(0, 'Secundario'), (1, 'Principal')], default=0, null=True)),
                ('alterar', models.BooleanField(default=False)),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procesosAdministrativos.activo_areas')),
            ],
            options={
                'db_table': 'procesos"."area_codigo_qr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetRegistroAccesoUbica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.IntegerField(choices=[(2, 'No Registrado'), (1, 'Completo'), (3, 'Incompleto'), (0, 'Pendiente')], default=0)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procesosAdministrativos.codigoqrareas')),
                ('cab_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procesosAdministrativos.cabregistroaccesoubica')),
            ],
            options={
                'db_table': 'procesos"."det_registro_acceso_ubicacion',
                'managed': True,
            },
        ),
    ]
