# Generated by Django 3.0 on 2020-04-27 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0021_auto_20200427_1607'),
        ('activos', '0020_auto_20200427_1607'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenesPedidosMulti',
            fields=[
                ('numpedido', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_aprueba', models.CharField(blank=True, max_length=100, null=True)),
                ('aprobado', models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (0, 'No Aprobado')], null=True)),
                ('fchsolicita', models.DateField(auto_now_add=True)),
                ('fchsolicitatxt', models.CharField(blank=True, max_length=8, null=True)),
                ('numproyecto', models.CharField(blank=True, max_length=70, null=True)),
                ('regimenespecial', models.BooleanField(blank=True, default=False, null=True)),
                ('fchaprueba', models.DateField(auto_now=True, null=True)),
                ('fchapruebatxt', models.CharField(blank=True, max_length=8, null=True)),
                ('motRechaza', models.CharField(blank=True, max_length=250, null=True)),
                ('estado_cotiza', models.BooleanField(blank=True, null=True)),
                ('cotiza_observa', models.CharField(blank=True, max_length=250, null=True)),
                ('genera_compra', models.IntegerField(blank=True, null=True)),
                ('observa_compra', models.CharField(blank=True, max_length=250, null=True)),
                ('motivo_compra', models.CharField(blank=True, choices=[('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_m', 'Reemplazo por Mejora'), ('nuevo', 'Nuevo')], max_length=50, null=True)),
                ('justificacion_compra', models.CharField(blank=True, max_length=250, null=True)),
                ('reemplazo_accion', models.IntegerField(blank=True, choices=[(1, 'Dada de Baja'), (3, 'Backup'), (2, 'Reubicación'), (4, 'Reparación')], null=True)),
                ('reemplazo_observa', models.CharField(blank=True, max_length=250, null=True)),
                ('entregado_bodega', models.BooleanField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('entrega_observa', models.CharField(blank=True, max_length=250, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_areas')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_depar')),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden Pedido Multiple',
                'verbose_name_plural': 'Ordenes Pedidos Multiples',
                'db_table': 'pedidos"."ordenespedidosmulti',
                'ordering': ['-numpedido'],
                'permissions': (('menu_pedidos_multi', 'Acceso al Menu de Pedidos'), ('aprueba_pedidos_multi', 'Aprueba Pedidos Multiples'), ('genera_pedidos_multi', 'Generar Pedidos Multiples')),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoMulti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('unimedida', models.CharField(blank=True, choices=[('unidad', 'Unidad')], max_length=15, null=True)),
                ('tiempo_vida', models.IntegerField()),
                ('tiempo_tipo', models.CharField(choices=[('anio', 'Años'), ('mes', 'Meses'), ('hora', 'Horas'), ('semana', 'Semanas'), ('dia', 'Dias')], max_length=7)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('activado_activo', models.BooleanField(blank=True, null=True)),
                ('fchactivacion', models.DateField(blank=True, null=True)),
                ('fchactivaciontxt', models.CharField(blank=True, max_length=8, null=True)),
                ('recibido_bodega', models.BooleanField(blank=True, null=True)),
                ('fchrecepcion', models.DateField(blank=True, null=True)),
                ('fchrecepciontxt', models.CharField(blank=True, max_length=8, null=True)),
                ('codigo_genera', models.BooleanField(blank=True, null=True)),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='img_pedidos/', verbose_name='Imagen 1')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='img_pedidos/', verbose_name='Imagen 2')),
                ('numpedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multipleOrdenPedido.OrdenesPedidosMulti')),
                ('tipoactivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_tipo')),
            ],
            options={
                'verbose_name': 'Detalle Pedido Multiple',
                'verbose_name_plural': 'Detalles Pedidos Multiples',
                'db_table': 'pedidos"."detallepedidomulti',
                'permissions': (('menu_bodega_multi', 'Acceso al Menu de Bodega'), ('activa_pedidos_multi', 'Activación de Pedidos'), ('recibe_bodega_multi', 'Recepción de Producto Bodega'), ('genera_bodega_multi', 'Genera Codigo Activo'), ('entrega_bodega_multi', 'Entrega de Pedidos')),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CotizaPedidoMulti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('pdf_cotiza', models.FileField(blank=True, null=True, upload_to='cotizaciones/', verbose_name='Cotización')),
                ('cotiza_seleccion', models.BooleanField(blank=True, null=True, verbose_name='Selección')),
                ('empresa_cotiza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proveedores.proveedor', verbose_name='Proveedor')),
                ('numpedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multipleOrdenPedido.OrdenesPedidosMulti')),
            ],
            options={
                'verbose_name': 'Cotización Multiple',
                'verbose_name_plural': 'Cotizaciones Multiples',
                'db_table': 'pedidos"."cotizapedidomulti',
                'permissions': (('menu_cotiza_multi', 'Acceso al Menu de Cotizaciones'), ('selecciona_cotizapedido_multi', 'Seleccionar Cotizaciones Multiples')),
                'managed': True,
            },
        ),
    ]
