# Generated by Django 3.0 on 2020-04-28 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multipleOrdenPedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidomulti',
            name='numpedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multipleOrdenPedido.OrdenesPedidosMulti'),
        ),
        migrations.AlterField(
            model_name='detallepedidomulti',
            name='tiempo_tipo',
            field=models.CharField(choices=[('hora', 'Horas'), ('semana', 'Semanas'), ('dia', 'Dias'), ('mes', 'Meses'), ('anio', 'Años')], max_length=7),
        ),
        migrations.AlterField(
            model_name='ordenespedidosmulti',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(0, 'No Aprobado'), ('', 'Pendiente'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidosmulti',
            name='motivo_compra',
            field=models.CharField(blank=True, choices=[('reemplazo_o', 'Reemplazo por Obsolescencia'), ('nuevo', 'Nuevo'), ('reemplazo_m', 'Reemplazo por Mejora')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidosmulti',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(3, 'Backup'), (2, 'Reubicación'), (4, 'Reparación'), (1, 'Dada de Baja')], null=True),
        ),
    ]
