# Generated by Django 3.0 on 2020-04-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipleOrdenPedido', '0002_auto_20200427_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidomulti',
            name='tiempo_tipo',
            field=models.CharField(choices=[('anio', 'Años'), ('hora', 'Horas'), ('dia', 'Dias'), ('semana', 'Semanas'), ('mes', 'Meses')], max_length=7),
        ),
        migrations.AlterField(
            model_name='detallepedidomulti',
            name='tiempo_vida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidosmulti',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidosmulti',
            name='motivo_compra',
            field=models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('reemplazo_o', 'Reemplazo por Obsolescencia'), ('reemplazo_m', 'Reemplazo por Mejora')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidosmulti',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(4, 'Reparación'), (1, 'Dada de Baja'), (2, 'Reubicación'), (3, 'Backup')], null=True),
        ),
    ]
