# Generated by Django 3.0.3 on 2022-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipleOrdenPedido', '0007_auto_20211015_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidomulti',
            name='tiempo_tipo',
            field=models.CharField(choices=[('anio', 'Años'), ('mes', 'Meses'), ('semana', 'Semanas'), ('dia', 'Dias'), ('hora', 'Horas')], max_length=7),
        ),
        migrations.AlterField(
            model_name='ordenespedidosmulti',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[('', 'Pendiente'), (0, 'No Aprobado'), (1, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='ordenespedidosmulti',
            name='reemplazo_accion',
            field=models.IntegerField(blank=True, choices=[(4, 'Reparación'), (1, 'Dada de Baja'), (3, 'Backup'), (2, 'Reubicación')], null=True),
        ),
    ]
