# Generated by Django 4.2.9 on 2024-01-27 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='activo_areas',
            fields=[
                ('area_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('area_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('area_estado', models.IntegerField(blank=True, null=True)),
                ('area_departamento', models.IntegerField(blank=True, null=True)),
                ('area_ubica', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activos"."activo_areas',
                'ordering': ['area_nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CabRegistroAccesoUbica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('completado', models.IntegerField(choices=[(1, 'Completo'), (0, 'Incompleto'), (2, 'No Registrado')], default=0)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_usuario', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'procesos"."registro_acceso_ubicacion_cab',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CodigoQrAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.IntegerField(blank=True, choices=[(0, 'Secundario'), (1, 'Principal')], default=0, null=True)),
                ('alterar', models.BooleanField(default=False)),
                ('activo', models.BooleanField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procesosAdministrativos.activo_areas')),
            ],
            options={
                'db_table': 'procesos"."area_codigo_qr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetRegistroAccesoUbica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.IntegerField(choices=[(1, 'Completo'), (0, 'Incompleto'), (2, 'No Registrado')], default=0)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('cab_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procesosAdministrativos.cabregistroaccesoubica')),
                ('codigo_area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procesosAdministrativos.codigoqrareas')),
            ],
            options={
                'db_table': 'procesos"."registro_acceso_ubicacion_det',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cabregistroaccesoubica',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procesosAdministrativos.codigoqrareas'),
        ),
        migrations.AddField(
            model_name='cabregistroaccesoubica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
