# Generated by Django 3.0.8 on 2022-03-16 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0111_auto_20220316_1338'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTrabajoInterno',
            fields=[
                ('numtrabajo', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(blank=True, max_length=301, null=True)),
                ('usuario_aprueba1n', models.CharField(blank=True, max_length=10000, null=True)),
                ('aprobado', models.IntegerField(blank=True, choices=[('', 'Pendiente'), (2, 'Anulada'), (1, 'Aprobado'), (0, 'No Aprobado')], null=True)),
                ('fchsolicita', models.DateTimeField(blank=True, null=True)),
                ('fchaprueba1n', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=10000, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=10000, null=True)),
                ('estado_solicitud', models.BooleanField(blank=True, choices=[('', 'Pendiente'), (1, 'En proceso'), (2, 'Convertida'), (0, 'Rechazada')], null=True)),
                ('fecha_aprox_entrega', models.DateTimeField(blank=True, null=True)),
                ('usuario_aprueba_mantenimiento', models.CharField(blank=True, max_length=10000, null=True)),
                ('entregado', models.BooleanField(blank=True, null=True)),
                ('fecha_real_entrega', models.DateTimeField(blank=True, null=True)),
                ('observaciones_retro_mantenimiento', models.CharField(blank=True, max_length=10000, null=True)),
                ('observaciones_internas_mantenimiento', models.CharField(blank=True, max_length=10000, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_depar')),
                ('ubica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_ubica')),
                ('usuario_solicita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trabajosinternos"."solicitud',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetSolicitudTrabajoInterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='img_pedidos/', verbose_name='Imagen 1')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='img_pedidos/', verbose_name='Imagen 2')),
                ('numtrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camello', to='trabajosInternos.SolicitudTrabajoInterno')),
            ],
            options={
                'db_table': 'trabajosinternos"."detsolicitud',
                'managed': True,
            },
        ),
    ]
