# Generated by Django 3.0.8 on 2022-03-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprobado'), ('', 'Pendiente'), (2, 'Anulada'), (0, 'No Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado_solicitud',
            field=models.BooleanField(blank=True, choices=[('', 'Pendiente'), (0, 'Rechazada'), (1, 'En proceso'), (2, 'Convertida')], null=True),
        ),
    ]
