# Generated by Django 3.0.8 on 2022-03-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0002_auto_20220316_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.CharField(blank=True, choices=[(4, 'Eléctricos'), (6, 'Adecuaciones'), (1, 'Obra Civil'), (5, 'Estructuras Metálicas'), (2, 'Cableado Estructurado'), (3, 'Pintura')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (4, 'Anulada'), (1, 'Pendiente'), (3, 'Rechazada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado_solicitud',
            field=models.BooleanField(blank=True, choices=[(4, 'Convertida'), (2, 'En proceso'), (1, 'Pendiente'), (3, 'Rechazada')], null=True),
        ),
    ]
