# Generated by Django 3.0.8 on 2022-03-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0003_auto_20220316_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (1, 'Pendiente'), (3, 'Rechazada'), (4, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado_solicitud',
            field=models.BooleanField(blank=True, choices=[(4, 'Convertida'), (1, 'Pendiente'), (3, 'Rechazada'), (2, 'En proceso')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(6, 'Adecuaciones'), (4, 'Eléctricos'), (1, 'Obra Civil'), (5, 'Estructuras Metálicas'), (2, 'Cableado Estructurado'), (3, 'Pintura')], null=True),
        ),
    ]
