# Generated by Django 3.0.8 on 2022-03-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0004_auto_20220316_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='aprobado',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada'), (4, 'Anulada'), (2, 'Aprobado'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado_solicitud',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada'), (2, 'En proceso'), (4, 'Convertida'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Pintura'), (2, 'Cableado Estructurado'), (5, 'Estructuras Metálicas'), (6, 'Adecuaciones'), (1, 'Obra Civil'), (4, 'Eléctricos')], null=True),
        ),
    ]
