# Generated by Django 3.0.8 on 2022-03-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0005_auto_20220316_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudtrabajointerno',
            name='aprobado',
        ),
        migrations.RemoveField(
            model_name='solicitudtrabajointerno',
            name='estado_solicitud',
        ),
        migrations.AddField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (3, 'Rechazada'), (2, 'Aprobado'), (4, 'Anulada')], null=True),
        ),
        migrations.AddField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(2, 'En proceso'), (4, 'Convertida'), (1, 'Pendiente'), (3, 'Rechazada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(5, 'Estructuras Metálicas'), (4, 'Eléctricos'), (3, 'Pintura'), (2, 'Cableado Estructurado'), (1, 'Obra Civil'), (6, 'Adecuaciones')], null=True),
        ),
    ]
