# Generated by Django 3.0.8 on 2022-03-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0006_auto_20220317_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajointerno',
            name='fecha_en_proceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (3, 'Rechazada'), (1, 'Pendiente'), (4, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(2, 'En proceso'), (4, 'Convertida'), (3, 'Rechazada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(6, 'Adecuaciones'), (1, 'Obra Civil'), (2, 'Cableado Estructurado'), (5, 'Estructuras Metálicas'), (4, 'Eléctricos'), (3, 'Pintura')], null=True),
        ),
    ]
