# Generated by Django 3.0.8 on 2022-03-28 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajosInternos', '0008_auto_20220322_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajointerno',
            name='asignadoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asignadoa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (4, 'Anulada'), (1, 'Pendiente'), (3, 'Rechazada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(3, 'Anulada'), (4, 'Finalizada'), (1, 'Pendiente'), (2, 'En proceso'), (5, 'Convertida')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(6, 'Adecuaciones'), (4, 'Eléctricos'), (2, 'Cableado Estructurado'), (3, 'Pintura'), (5, 'Estructuras Metálicas'), (1, 'Obra Civil')], null=True),
        ),
    ]
