# Generated by Django 3.0.8 on 2022-03-28 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0009_auto_20220328_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudtrabajointerno',
            name='asignadoa',
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(4, 'Anulada'), (3, 'Rechazada'), (2, 'Aprobado'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(2, 'En proceso'), (5, 'Convertida'), (3, 'Anulada'), (1, 'Pendiente'), (4, 'Finalizada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(4, 'Eléctricos'), (3, 'Pintura'), (1, 'Obra Civil'), (6, 'Adecuaciones'), (5, 'Estructuras Metálicas'), (2, 'Cableado Estructurado')], null=True),
        ),
        migrations.CreateModel(
            name='RecibeEncargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.IntegerField(blank=True, null=True)),
                ('numtrabajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asignados', to='trabajosInternos.SolicitudTrabajoInterno')),
            ],
            options={
                'db_table': 'trabajosinternos"."asignados',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='solicitudtrabajointerno',
            name='asignadoa',
            field=models.ManyToManyField(blank=True, to='trabajosInternos.RecibeEncargo'),
        ),
    ]
