# Generated by Django 3.0.8 on 2022-03-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0010_auto_20220328_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibeencargo',
            name='numtrabajo',
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (3, 'Rechazada'), (2, 'Aprobado'), (4, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(2, 'En proceso'), (3, 'Anulada'), (4, 'Finalizada'), (1, 'Pendiente'), (5, 'Convertida')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Pintura'), (1, 'Obra Civil'), (5, 'Estructuras Metálicas'), (6, 'Adecuaciones'), (4, 'Eléctricos'), (2, 'Cableado Estructurado')], null=True),
        ),
    ]
