# Generated by Django 3.0.8 on 2022-03-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0011_auto_20220329_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudtrabajointerno',
            name='asignadoa',
        ),
        migrations.AddField(
            model_name='recibeencargo',
            name='asignadoa',
            field=models.ManyToManyField(blank=True, to='trabajosInternos.SolicitudTrabajoInterno'),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(5, 'Convertida'), (3, 'Anulada'), (1, 'Pendiente'), (2, 'En proceso'), (4, 'Finalizada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(6, 'Adecuaciones'), (1, 'Obra Civil'), (2, 'Cableado Estructurado'), (4, 'Eléctricos'), (5, 'Estructuras Metálicas'), (3, 'Pintura')], null=True),
        ),
    ]
