# Generated by Django 3.0.8 on 2022-04-01 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajosInternos', '0013_auto_20220401_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibeencargo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (3, 'Rechazada'), (4, 'Anulada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (4, 'Finalizada'), (3, 'Anulada'), (5, 'Convertida'), (2, 'En proceso')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(5, 'Estructuras Metálicas'), (4, 'Eléctricos'), (6, 'Adecuaciones'), (2, 'Cableado Estructurado'), (1, 'Obra Civil'), (3, 'Pintura')], null=True),
        ),
    ]
