# Generated by Django 3.0.8 on 2022-04-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0014_auto_20220401_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajointerno',
            name='fecha_finaliza_rechaza_convierte',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada'), (1, 'Pendiente'), (2, 'Aprobado'), (4, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(3, 'Anulada'), (4, 'Finalizada'), (1, 'Pendiente'), (5, 'Convertida'), (2, 'En proceso')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(6, 'Adecuaciones'), (5, 'Estructuras Metálicas'), (4, 'Eléctricos'), (3, 'Pintura'), (2, 'Cableado Estructurado'), (1, 'Obra Civil')], null=True),
        ),
    ]
