# Generated by Django 3.0.8 on 2022-04-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0015_auto_20220401_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajointerno',
            name='observaciones_rechazo1n',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (4, 'Anulada'), (3, 'Rechazada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(2, 'En proceso'), (5, 'Convertida'), (4, 'Finalizada'), (3, 'Anulada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(4, 'Eléctricos'), (1, 'Obra Civil'), (3, 'Pintura'), (5, 'Estructuras Metálicas'), (2, 'Cableado Estructurado'), (6, 'Adecuaciones')], null=True),
        ),
    ]
