# Generated by Django 3.0.8 on 2022-04-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0016_auto_20220405_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudtrabajointerno',
            old_name='observaciones_retro_mantenimiento',
            new_name='observaciones_devuelve_mantenimiento',
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(4, 'Anulada'), (1, 'Pendiente'), (2, 'Aprobado'), (3, 'Rechazada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(5, 'Convertida'), (4, 'Finalizada'), (1, 'Pendiente'), (3, 'Devuelta'), (2, 'En proceso')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Pintura'), (6, 'Adecuaciones'), (1, 'Obra Civil'), (2, 'Cableado Estructurado'), (4, 'Eléctricos'), (5, 'Estructuras Metálicas')], null=True),
        ),
    ]
