# Generated by Django 3.0.8 on 2022-04-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0017_auto_20220405_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajointerno',
            name='anula',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(4, 'Anulada'), (3, 'Rechazada'), (2, 'Aprobado'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(3, 'Devuelta'), (5, 'Convertida'), (2, 'En proceso'), (1, 'Pendiente'), (4, 'Finalizada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Cableado Estructurado'), (3, 'Pintura'), (6, 'Adecuaciones'), (5, 'Estructuras Metálicas'), (4, 'Eléctricos'), (1, 'Obra Civil')], null=True),
        ),
    ]
