# Generated by Django 3.0.8 on 2022-04-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0018_auto_20220407_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajointerno',
            name='num_req_sia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (4, 'Anulada'), (3, 'Rechazada'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (5, 'Convertida'), (4, 'Finalizada'), (2, 'En proceso'), (3, 'Devuelta')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Obra Civil'), (6, 'Adecuaciones'), (3, 'Pintura'), (2, 'Cableado Estructurado'), (4, 'Eléctricos'), (5, 'Estructuras Metálicas')], null=True),
        ),
    ]
