# Generated by Django 3.0.8 on 2022-04-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0019_auto_20220408_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudtrabajointerno',
            options={'managed': True, 'permissions': (('acceso_trabajos_internos', 'Acceso a Trabajos Internos'), ('autoriza_solicitudes_trabajos_internos', 'Autoriza Solicitudes Trabajos Internos'), ('gestiona_solicitudes_trabajos_internos', 'Gestor de Solicitudes Trabajos Internos'))},
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (4, 'Anulada'), (2, 'Aprobado'), (3, 'Rechazada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (2, 'En proceso'), (3, 'Devuelta'), (4, 'Finalizada'), (5, 'Convertida')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Cableado Estructurado'), (6, 'Adecuaciones'), (5, 'Estructuras Metálicas'), (4, 'Eléctricos'), (1, 'Obra Civil'), (3, 'Pintura')], null=True),
        ),
    ]
