# Generated by Django 3.0.8 on 2022-04-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0020_auto_20220428_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudtrabajointerno',
            options={'managed': True, 'permissions': (('acceso_trabajos_internos', 'Acceso a Trabajos Internos'), ('ingresa_trabajos_internos', 'Ingresa Trabajos Internos'), ('autoriza_solicitudes_trabajos_internos', 'Autoriza Solicitudes Trabajos Internos'), ('gestiona_solicitudes_trabajos_internos', 'Gestor de Solicitudes Trabajos Internos'))},
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(4, 'Anulada'), (2, 'Aprobado'), (1, 'Pendiente'), (3, 'Rechazada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (4, 'Finalizada'), (3, 'Devuelta'), (2, 'En proceso'), (5, 'Convertida')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Cableado Estructurado'), (4, 'Eléctricos'), (3, 'Pintura'), (5, 'Estructuras Metálicas'), (1, 'Obra Civil'), (6, 'Adecuaciones')], null=True),
        ),
    ]
