# Generated by Django 3.0.8 on 2022-05-05 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajosInternos', '0021_auto_20220428_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada'), (2, 'Aprobado'), (1, 'Pendiente'), (4, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Finalizada'), (3, 'Devuelta'), (1, 'Pendiente'), (5, 'Convertida'), (2, 'En proceso')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Cableado Estructurado'), (4, 'Eléctricos'), (6, 'Adecuaciones'), (3, 'Pintura'), (1, 'Obra Civil'), (5, 'Estructuras Metálicas')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='usuario_aprueba1n',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aprueba1n', to=settings.AUTH_USER_MODEL),
        ),
    ]
