# Generated by Django 3.0.8 on 2022-05-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0022_auto_20220505_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (4, 'Anulada'), (3, 'Rechazada'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(5, 'Convertida'), (4, 'Finalizada'), (1, 'Pendiente'), (3, 'Devuelta'), (2, 'En proceso')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(6, 'Adecuaciones'), (1, 'Obra Civil'), (3, 'Pintura'), (4, 'Eléctricos'), (5, 'Estructuras Metálicas'), (2, 'Cableado Estructurado'), (7, 'Mantenimiento Maquinaria')], null=True),
        ),
    ]
