# Generated by Django 3.0.8 on 2022-06-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0024_auto_20220512_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(4, 'Anulada'), (1, 'Pendiente'), (3, 'Rechazada'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(3, 'Devuelta'), (4, 'Finalizada'), (2, 'En proceso'), (5, 'Convertida'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(5, 'Estructuras Metálicas'), (2, 'Cableado Estructurado'), (1, 'Obra Civil'), (7, 'Mantenimiento Maquinaria'), (8, 'Mantenimiento Otros'), (6, 'Adecuaciones'), (3, 'Pintura'), (4, 'Eléctricos')], null=True),
        ),
    ]
