# Generated by Django 3.0.8 on 2022-06-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajosInternos', '0025_auto_20220615_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajointerno',
            name='estado_mant',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (3, 'Devuelta'), (2, 'En proceso'), (5, 'Convertida'), (4, 'Finalizada')], null=True),
        ),
        migrations.AddField(
            model_name='solicitudtrabajointerno',
            name='fecha_en_proceso_mant',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtrabajointerno',
            name='fecha_finaliza_mant',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (3, 'Devuelta'), (2, 'En proceso'), (5, 'Convertida'), (4, 'Finalizada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajointerno',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(4, 'Eléctricos'), (2, 'Cableado Estructurado'), (7, 'Mantenimiento Maquinaria'), (5, 'Estructuras Metálicas'), (3, 'Pintura'), (6, 'Adecuaciones'), (1, 'Obra Civil'), (8, 'Mantenimiento Otros')], null=True),
        ),
    ]
