# Generated by Django 3.0.7 on 2020-10-12 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0015_auto_20201012_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('estado', models.BooleanField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Areas')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'soporte"."asignaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
                ('tipo', models.IntegerField(choices=[(1, 'Soporte')])),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'soporte"."estados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Problemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.IntegerField(default=1)),
                ('tipo', models.IntegerField(choices=[(1, 'Soporte')])),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='soporteIt.Asignaciones')),
            ],
            options={
                'verbose_name': 'Problema',
                'verbose_name_plural': 'Problemas',
                'db_table': 'soporte"."problemas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TicketsIt',
            fields=[
                ('numticket', models.AutoField(primary_key=True, serialize=False)),
                ('solicita_nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('solicita_apellido', models.CharField(blank=True, max_length=250, null=True)),
                ('solicita_codigo', models.IntegerField(blank=True, null=True)),
                ('descripcion_problema', models.CharField(blank=True, max_length=1000, null=True)),
                ('fch_solicita', models.DateTimeField(auto_now_add=True)),
                ('fch_solicita_txt', models.CharField(blank=True, max_length=8, null=True)),
                ('hr_solicita', models.CharField(blank=True, max_length=5, null=True)),
                ('fch_soluciona', models.DateTimeField(blank=True, null=True)),
                ('fch_soluciona_txt', models.CharField(blank=True, max_length=8, null=True)),
                ('hr_soluciona_txt', models.CharField(blank=True, max_length=5, null=True)),
                ('observa_solucion', models.CharField(blank=True, max_length=1000, null=True)),
                ('reasignado', models.BooleanField(blank=True, null=True)),
                ('observa_reasignacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('usuario', models.IntegerField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Areas')),
                ('area_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='soporteIt.Asignaciones')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Departamento')),
                ('estado_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='soporteIt.Estados')),
                ('tipo_problema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='soporteIt.Problemas')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Ubicacion')),
                ('usuario_responsabe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tickets TI',
                'verbose_name_plural': 'Tickets TI',
                'db_table': 'soporte"."ticketsti',
                'managed': True,
            },
        ),
    ]
