# Generated by Django 3.0.7 on 2020-10-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporteIt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketsit',
            options={'managed': True, 'permissions': (('soporte_interno', 'Acceso a Soporte Interno'),), 'verbose_name': 'Tickets TI', 'verbose_name_plural': 'Tickets TI'},
        ),
    ]
