# Generated by Django 3.0.8 on 2021-10-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporteIt', '0002_auto_20201014_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsit',
            name='fch_solicita',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
