# Generated by Django 3.0.8 on 2022-12-06 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soporteIt', '0003_auto_20211015_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsit',
            name='delta_solucion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketsit',
            name='reasignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reasignado', to=settings.AUTH_USER_MODEL),
        ),
    ]
