# Generated by Django 3.0.8 on 2022-12-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventosRaytec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('defect_key', models.CharField(blank=True, max_length=300, null=True)),
                ('pixels', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('way', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('fecha_txt', models.CharField(blank=True, max_length=50, null=True)),
                ('receta', models.CharField(blank=True, max_length=200, null=True)),
                ('linea', models.CharField(blank=True, max_length=5, null=True)),
                ('origen', models.CharField(blank=True, max_length=40, null=True)),
                ('proceso', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('usuini', models.CharField(blank=True, max_length=60, null=True)),
                ('usufin', models.CharField(blank=True, max_length=60, null=True)),
                ('defecto', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_evento', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'public"."eventos_raytec',
                'managed': True,
            },
        ),
    ]
