# Generated by Django 3.0.8 on 2022-12-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventosraytec',
            options={'managed': True, 'permissions': (('reporte_raytec', 'Reporte Diario de Eventos Raytec'),)},
        ),
    ]
