# Generated by Django 3.0.8 on 2023-01-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0003_eventospareceticol3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventospareceticol3',
            old_name='ph',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='eventospareceticol3',
            name='ppms',
        ),
        migrations.AddField(
            model_name='eventospareceticol3',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventospareceticol3',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PPMs', 'PPMS'), ('PH', 'PH')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='ubicacion',
            field=models.IntegerField(blank=True, choices=[('1', 'CUBA'), ('2', 'HIDROCOOLER')], null=True),
        ),
    ]
