# Generated by Django 3.0.8 on 2023-01-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0004_auto_20230127_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='tipo',
            field=models.CharField(blank=True, choices=[('APA', 'APA'), ('PH', 'PH')], max_length=200, null=True),
        ),
    ]
