# Generated by Django 3.0.8 on 2023-01-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0005_auto_20230127_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventospareceticol3',
            old_name='estado',
            new_name='aiStatus',
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='parametro',
            field=models.CharField(blank=True, choices=[('1', 'CORRECTO'), ('2', 'OBSERVACION')], max_length=20, null=True),
        ),
    ]
