# Generated by Django 3.0.8 on 2023-01-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0006_auto_20230127_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventospareceticol3',
            name='time',
        ),
        migrations.AddField(
            model_name='eventospareceticol3',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PH', 'PH'), ('APA', 'APA')], max_length=200, null=True),
        ),
    ]
