# Generated by Django 3.0.8 on 2023-01-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0007_auto_20230131_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventospareceticol3',
            old_name='aiStatus',
            new_name='aiEstado',
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='tipo',
            field=models.CharField(blank=True, choices=[('APA', 'APA'), ('PH', 'PH')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='ubicacion',
            field=models.IntegerField(blank=True, choices=[('2', 'HIDROCOOLER'), ('1', 'CUBA')], null=True),
        ),
    ]
