# Generated by Django 3.0.8 on 2023-01-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0008_auto_20230131_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='aiEstado',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
    ]
