# Generated by Django 3.0.8 on 2023-02-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0010_auto_20230131_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventosraytec',
            options={'managed': True, 'permissions': (('reporte_raytec', 'Reporte Diario de Eventos Raytec'), ('reporte_parecetico_l3', 'Reporte Dosificación APA L3'))},
        ),
    ]
