# Generated by Django 3.0.8 on 2023-05-11 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activos', '0121_auto_20230511_1443'),
        ('procesosAdministrativos', '0017_auto_20230509_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='conteo_disponible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='destino',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='origen',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='transportista',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SolicitudTransporte',
            fields=[
                ('numpedido', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (1, 'Transporte')], null=True)),
                ('area', models.CharField(blank=True, max_length=301, null=True)),
                ('estado1n', models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (3, 'Rechazada'), (2, 'Aprobado'), (4, 'Anulada')], null=True)),
                ('fchsolicita', models.DateTimeField(blank=True, null=True)),
                ('fchaprueba1n', models.DateTimeField(blank=True, null=True)),
                ('fecha_en_proceso', models.DateTimeField(blank=True, null=True)),
                ('fecha_confirma', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=10000, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=10000, null=True)),
                ('estado2n', models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (4, 'Confirmado'), (3, 'Devuelta'), (2, 'En proceso')], null=True)),
                ('confirmacion', models.BooleanField(blank=True, null=True)),
                ('observaciones_rechazo1n', models.CharField(blank=True, max_length=10000, null=True)),
                ('observaciones_rechazo2n', models.CharField(blank=True, max_length=10000, null=True)),
                ('anula', models.BooleanField(blank=True, null=True)),
                ('num_requisicion', models.IntegerField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_depar')),
                ('ubica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_ubica')),
                ('usuario_aprueba1n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aprobador', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procesos"."solicitud_transporte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetSolicitudTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='img_pedidos/', verbose_name='Imagen 1')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='img_pedidos/', verbose_name='Imagen 2')),
                ('numpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera', to='procesosAdministrativos.SolicitudTransporte')),
            ],
            options={
                'db_table': 'procesos"."det_solicitud_transporte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preserva', models.CharField(blank=True, max_length=100, null=True)),
                ('pasajero', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='procesosAdministrativos.Eventos')),
            ],
            options={
                'db_table': 'procesos"."booking',
                'managed': True,
            },
        ),
    ]
