# Generated by Django 3.0.8 on 2023-05-12 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procesosAdministrativos', '0018_auto_20230511_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosclorol2',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PH', 'PH'), ('CI', 'CI')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (4, 'Anulada'), (3, 'Rechazada'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (3, 'Devuelta'), (2, 'En proceso'), (4, 'Confirmado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Transporte'), (2, 'Encomienda')], null=True),
        ),
        migrations.CreateModel(
            name='RecGPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(blank=True, max_length=100000, null=True)),
                ('fecha_pregunta', models.DateTimeField(blank=True, null=True)),
                ('usuario_consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procesos"."rec_gpt',
                'managed': True,
            },
        ),
    ]
