# Generated by Django 3.0.8 on 2023-05-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0019_auto_20230512_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recgpt',
            old_name='fecha_pregunta',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='recgpt',
            old_name='usuario_consulta',
            new_name='pc',
        ),
        migrations.RenameField(
            model_name='recgpt',
            old_name='pregunta',
            new_name='pr',
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='parametro',
            field=models.CharField(blank=True, choices=[('1', 'CORRECTO'), ('2', 'OBSERVACION')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='parametro',
            field=models.CharField(blank=True, choices=[('1', 'CORRECTO'), ('2', 'OBSERVACION')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (1, 'Pendiente'), (3, 'Rechazada'), (4, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (1, 'Pendiente'), (2, 'En proceso'), (3, 'Devuelta')], null=True),
        ),
    ]
