# Generated by Django 3.0.8 on 2023-05-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0020_auto_20230512_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosclorol2',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (3, 'Rechazada'), (2, 'Aprobado'), (4, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (4, 'Confirmado'), (3, 'Devuelta'), (2, 'En proceso')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (1, 'Transporte')], null=True),
        ),
    ]
