# Generated by Django 3.0.8 on 2023-05-15 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0024_auto_20230512_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ruta', models.CharField(blank=True, max_length=50, null=True)),
                ('origen', models.CharField(blank=True, max_length=500, null=True)),
                ('destino', models.CharField(blank=True, max_length=500, null=True)),
                ('tarifa', models.FloatField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Activa'), (2, 'Inactiva'), (3, 'Suspendida')], null=True)),
            ],
            options={
                'db_table': 'procesos"."ruta_transporte',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CI', 'CI'), ('PH', 'PH')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (4, 'Anulada'), (3, 'Rechazada'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (3, 'Devuelta'), (4, 'Confirmado'), (2, 'En proceso')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (1, 'Transporte')], null=True),
        ),
        migrations.AddField(
            model_name='solicitudtransporte',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procesosAdministrativos.RutaTransporte'),
        ),
    ]
