# Generated by Django 3.0.8 on 2023-05-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0167_auto_20230515_1732'),
        ('procesosAdministrativos', '0029_auto_20230515_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='origen',
        ),
        migrations.AddField(
            model_name='eventos',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rutas', to='procesosAdministrativos.RutaTransporte'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chofer', to='proveedores.proveedor'),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (1, 'Pendiente'), (3, 'Rechazada'), (4, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (2, 'En proceso'), (3, 'Devuelta'), (4, 'Confirmado')], null=True),
        ),
    ]
