# Generated by Django 3.0.8 on 2023-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0034_auto_20230529_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Nueva Solicitud Transporte'), (4, 'Vale de Combustible'), (3, 'Encomienda'), (1, 'Booking Ruta Programada')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada'), (2, 'Aprobado'), (1, 'Pendiente'), (5, 'Booked'), (4, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CI', 'CI'), ('PH', 'PH')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada'), (2, 'Aprobado'), (1, 'Pendiente'), (5, 'Booked'), (4, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(2, 'En proceso'), (3, 'Devuelta'), (4, 'Confirmado'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (1, 'Transporte')], null=True),
        ),
    ]
