# Generated by Django 3.0.8 on 2023-08-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0037_auto_20230619_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(4, 'Anulada'), (5, 'Booked'), (1, 'Pendiente'), (2, 'Aprobado'), (3, 'Rechazada')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Encomienda'), (1, 'Booking Ruta Programada'), (4, 'Vale de Combustible'), (2, 'Nueva Solicitud Transporte')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(4, 'Anulada'), (5, 'Booked'), (1, 'Pendiente'), (2, 'Aprobado'), (3, 'Rechazada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (2, 'En proceso'), (1, 'Pendiente'), (3, 'Devuelta')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Vale Combustible'), (1, 'Transporte personas'), (2, 'Encomienda')], null=True),
        ),
    ]
