# Generated by Django 3.0.8 on 2023-08-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0038_auto_20230802_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutatransporte',
            options={'managed': True, 'permissions': (('edicion_rutas_transporte', 'Edicion Rutas Transporte'),)},
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada'), (4, 'Anulada'), (5, 'Booked'), (2, 'Aprobado'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Nueva Solicitud Transporte'), (3, 'Encomienda'), (1, 'Booking Ruta Programada'), (4, 'Vale de Combustible')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('CUBA', 'CUBA'), ('HIDROCOOLER', 'HIDROCOOLER')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PH', 'PH'), ('APA', 'APA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('CUBA', 'CUBA'), ('HIDROCOOLER', 'HIDROCOOLER')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada'), (4, 'Anulada'), (5, 'Booked'), (2, 'Aprobado'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (3, 'Devuelta'), (2, 'En proceso'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (1, 'Transporte personas'), (3, 'Vale Combustible')], null=True),
        ),
    ]
