# Generated by Django 3.0.8 on 2023-08-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0043_auto_20230808_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (3, 'Rechazada'), (2, 'Aprobado'), (4, 'Anulada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Nueva Solicitud Transporte'), (4, 'Vale de Combustible'), (3, 'Encomienda'), (1, 'Booking Ruta Programada')], null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='laruta_ev', to='procesosAdministrativos.RutaTransporte'),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (3, 'Rechazada'), (2, 'Aprobado'), (4, 'Anulada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (3, 'Devuelta'), (2, 'En proceso'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Transporte personas'), (2, 'Encomienda'), (3, 'Vale Combustible')], null=True),
        ),
    ]
