# Generated by Django 3.0.8 on 2023-08-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0044_auto_20230809_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='docs',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='transporte/', verbose_name='Documentos Transpote'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (1, 'Pendiente'), (4, 'Anulada'), (3, 'Rechazada'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Booking Ruta Programada'), (3, 'Encomienda'), (2, 'Nueva Solicitud Transporte'), (4, 'Vale de Combustible')], null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='tipo',
            field=models.CharField(blank=True, choices=[('APA', 'APA'), ('PH', 'PH')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (1, 'Pendiente'), (4, 'Anulada'), (3, 'Rechazada'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (2, 'En proceso'), (1, 'Pendiente'), (3, 'Devuelta')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (3, 'Vale Combustible'), (1, 'Transporte personas')], null=True),
        ),
    ]
