# Generated by Django 3.0.8 on 2023-08-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0045_auto_20230810_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'managed': True, 'permissions': (('calendario_transporte', 'Administracion Transporte'), ('solicitudes_transporte', 'Solicitud Transporte'), ('autorizaciones_transporte', 'Autorizacion Transporte'), ('vales_combustible', 'Admini Vales Combustible'))},
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (3, 'Rechazada'), (4, 'Anulada'), (1, 'Pendiente'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Booking Ruta Programada'), (2, 'Nueva Solicitud Transporte'), (3, 'Encomienda'), (4, 'Vale de Combustible')], null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='transporte/', verbose_name='Documentos Transpote'),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PH', 'PH'), ('APA', 'APA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (3, 'Rechazada'), (4, 'Anulada'), (1, 'Pendiente'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (1, 'Pendiente'), (2, 'En proceso'), (3, 'Devuelta')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Transporte personas'), (3, 'Vale Combustible'), (2, 'Encomienda')], null=True),
        ),
    ]
