# Generated by Django 3.0.8 on 2023-08-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0048_auto_20230823_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosishidar2',
            name='motivo_para',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada'), (2, 'Aprobado'), (5, 'Booked'), (4, 'Anulada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Encomienda'), (1, 'Booking Ruta Programada'), (4, 'Vale de Combustible'), (2, 'Nueva Solicitud Transporte')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PH', 'PH'), ('CI', 'CI')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada'), (2, 'Aprobado'), (5, 'Booked'), (4, 'Anulada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(2, 'En proceso'), (4, 'Confirmado'), (1, 'Pendiente'), (3, 'Devuelta')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (3, 'Vale Combustible'), (1, 'Transporte personas')], null=True),
        ),
    ]
