# Generated by Django 3.0.8 on 2023-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0049_auto_20230825_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosIshidaR1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_remepaque', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('num_reempacadora', models.CharField(blank=True, max_length=5, null=True)),
                ('receta', models.CharField(blank=True, max_length=500, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('usu', models.CharField(blank=True, max_length=60, null=True)),
                ('motivo_para', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'public"."eventos_ishida_r1',
                'permissions': (('reporte_ishida_r1', 'Reporte de Pesos Rempacadora Ishida R1'),),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventosIshidaR3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_remepaque', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('num_reempacadora', models.CharField(blank=True, max_length=5, null=True)),
                ('receta', models.CharField(blank=True, max_length=500, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('usu', models.CharField(blank=True, max_length=60, null=True)),
                ('motivo_para', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'public"."eventos_ishida_r3',
                'permissions': (('reporte_ishida_r3', 'Reporte de Pesos Rempacadora Ishida R3'),),
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (4, 'Anulada'), (2, 'Aprobado'), (3, 'Rechazada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Booking Ruta Programada'), (2, 'Nueva Solicitud Transporte'), (3, 'Encomienda'), (4, 'Vale de Combustible')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CI', 'CI'), ('PH', 'PH')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (4, 'Anulada'), (2, 'Aprobado'), (3, 'Rechazada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (3, 'Devuelta'), (1, 'Pendiente'), (2, 'En proceso')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (1, 'Transporte personas'), (3, 'Vale Combustible')], null=True),
        ),
    ]
