# Generated by Django 3.0.3 on 2023-08-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0051_auto_20230825_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosishidar2',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventosishidar3',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (2, 'Aprobado'), (1, 'Pendiente'), (3, 'Rechazada'), (4, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Booking Ruta Programada'), (4, 'Vale de Combustible'), (2, 'Nueva Solicitud Transporte'), (3, 'Encomienda')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('HIDROCOOLER', 'HIDROCOOLER'), ('CUBA', 'CUBA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('HIDROCOOLER', 'HIDROCOOLER'), ('CUBA', 'CUBA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (2, 'Aprobado'), (1, 'Pendiente'), (3, 'Rechazada'), (4, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (4, 'Confirmado'), (3, 'Devuelta'), (2, 'En proceso')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Vale Combustible'), (1, 'Transporte personas'), (2, 'Encomienda')], null=True),
        ),
    ]
