# Generated by Django 3.0.3 on 2023-08-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0052_auto_20230829_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosishidar1',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (2, 'Aprobado'), (5, 'Booked'), (3, 'Rechazada'), (4, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(4, 'Vale de Combustible'), (3, 'Encomienda'), (2, 'Nueva Solicitud Transporte'), (1, 'Booking Ruta Programada')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('CUBA', 'CUBA'), ('HIDROCOOLER', 'HIDROCOOLER')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventosishidar2',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventosishidar3',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('CUBA', 'CUBA'), ('HIDROCOOLER', 'HIDROCOOLER')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (2, 'Aprobado'), (5, 'Booked'), (3, 'Rechazada'), (4, 'Anulada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(3, 'Devuelta'), (1, 'Pendiente'), (4, 'Confirmado'), (2, 'En proceso')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Vale Combustible'), (2, 'Encomienda'), (1, 'Transporte personas')], null=True),
        ),
    ]
