# Generated by Django 3.0.3 on 2023-08-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0053_auto_20230829_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosishidar1',
            name='speedw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventosishidar2',
            name='speedw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventosishidar3',
            name='speedw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (3, 'Rechazada'), (4, 'Anulada'), (2, 'Aprobado'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PH', 'PH'), ('APA', 'APA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (3, 'Rechazada'), (4, 'Anulada'), (2, 'Aprobado'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(2, 'En proceso'), (3, 'Devuelta'), (4, 'Confirmado'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (3, 'Vale Combustible'), (1, 'Transporte personas')], null=True),
        ),
    ]
