# Generated by Django 3.2.15 on 2023-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0059_auto_20230919_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtransporte',
            name='evento_de_calendario',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(4, 'Anulada'), (3, 'Rechazada'), (1, 'Pendiente'), (2, 'Aprobado'), (5, 'Booked')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Nueva Solicitud Transporte'), (3, 'Encomienda'), (1, 'Booking Ruta Programada'), (4, 'Vale de Combustible')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='parametro',
            field=models.CharField(blank=True, choices=[('1', 'CORRECTO'), ('2', 'OBSERVACION')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('CUBA', 'CUBA'), ('HIDROCOOLER', 'HIDROCOOLER')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='parametro',
            field=models.CharField(blank=True, choices=[('1', 'CORRECTO'), ('2', 'OBSERVACION')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('CUBA', 'CUBA'), ('HIDROCOOLER', 'HIDROCOOLER')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(4, 'Anulada'), (3, 'Rechazada'), (1, 'Pendiente'), (2, 'Aprobado'), (5, 'Booked')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(3, 'Devuelta'), (1, 'Pendiente'), (4, 'Confirmado'), (2, 'En proceso')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Vale Combustible'), (1, 'Transporte personas'), (2, 'Encomienda')], null=True),
        ),
    ]
