# Generated by Django 3.2.15 on 2023-10-03 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0124_auto_20231003_1059'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procesosAdministrativos', '0060_auto_20230919_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (4, 'Anulada'), (5, 'Booked'), (3, 'Rechazada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(4, 'Vale de Combustible'), (3, 'Encomienda'), (2, 'Nueva Solicitud Transporte'), (1, 'Booking Ruta Programada')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CI', 'CI'), ('PH', 'PH')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('HIDROCOOLER', 'HIDROCOOLER'), ('CUBA', 'CUBA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('HIDROCOOLER', 'HIDROCOOLER'), ('CUBA', 'CUBA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (4, 'Anulada'), (5, 'Booked'), (3, 'Rechazada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (2, 'En proceso'), (3, 'Devuelta'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (3, 'Vale Combustible'), (1, 'Transporte personas')], null=True),
        ),
        migrations.CreateModel(
            name='BookingReporte',
            fields=[
                ('numpedido', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (3, 'Vale Combustible'), (1, 'Transporte personas')], null=True)),
                ('area', models.CharField(blank=True, max_length=301, null=True)),
                ('estado1n', models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (4, 'Anulada'), (5, 'Booked'), (3, 'Rechazada'), (1, 'Pendiente')], null=True)),
                ('fchsolicita', models.DateTimeField(blank=True, null=True)),
                ('fchaprueba1n', models.DateTimeField(blank=True, null=True)),
                ('fecha_en_proceso', models.DateTimeField(blank=True, null=True)),
                ('fecha_confirma', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=10000, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=10000, null=True)),
                ('estado2n', models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (2, 'En proceso'), (3, 'Devuelta'), (1, 'Pendiente')], null=True)),
                ('confirmacion', models.BooleanField(blank=True, null=True)),
                ('observaciones_rechazo1n', models.CharField(blank=True, max_length=10000, null=True)),
                ('observaciones_rechazo2n', models.CharField(blank=True, max_length=10000, null=True)),
                ('anula', models.BooleanField(blank=True, null=True)),
                ('num_requisicion', models.IntegerField(blank=True, null=True)),
                ('otra_ruta', models.CharField(blank=True, max_length=2000, null=True)),
                ('pasajero', models.CharField(blank=True, max_length=500, null=True)),
                ('fchevento', models.DateTimeField(blank=True, null=True)),
                ('otros_pasajeros', models.CharField(blank=True, max_length=500, null=True)),
                ('notas_del_gestor', models.CharField(blank=True, max_length=10000, null=True)),
                ('notas_de_confirmacion', models.CharField(blank=True, max_length=10000, null=True)),
                ('retorno', models.BooleanField(blank=True, null=True)),
                ('usu_gestiona_vale', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_gestiona_vale', models.DateTimeField(blank=True, null=True)),
                ('observaciones_vale', models.CharField(blank=True, max_length=10000, null=True)),
                ('num_vale', models.IntegerField(blank=True, null=True)),
                ('valor_vale', models.FloatField(blank=True, null=True)),
                ('estado_vale', models.IntegerField(blank=True, null=True)),
                ('beneficiario_vale', models.CharField(blank=True, max_length=500, null=True)),
                ('evento_de_calendario', models.BooleanField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_depar')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='larutabr', to='procesosAdministrativos.rutatransporte')),
                ('ubica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activos.activo_ubica')),
                ('usuario_aprueba1n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aprobadorbr', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procesos"."booking_reporte',
                'managed': True,
            },
        ),
    ]
