# Generated by Django 3.2.15 on 2023-10-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0062_auto_20231003_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingreporte',
            name='tarifa_real',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingreporte',
            name='transportista',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtransporte',
            name='tarifa_real',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtransporte',
            name='transportista',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (4, 'Anulada'), (3, 'Rechazada'), (1, 'Pendiente'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(4, 'Vale de Combustible'), (1, 'Booking Ruta Programada'), (2, 'Nueva Solicitud Transporte'), (3, 'Encomienda')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (4, 'Anulada'), (3, 'Rechazada'), (1, 'Pendiente'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (1, 'Pendiente'), (2, 'En proceso'), (3, 'Devuelta')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Vale Combustible'), (1, 'Transporte personas'), (2, 'Encomienda')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PH', 'PH'), ('CI', 'CI')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (4, 'Anulada'), (3, 'Rechazada'), (1, 'Pendiente'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (1, 'Pendiente'), (2, 'En proceso'), (3, 'Devuelta')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Vale Combustible'), (1, 'Transporte personas'), (2, 'Encomienda')], null=True),
        ),
    ]
