# Generated by Django 3.2.15 on 2023-10-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0063_auto_20231003_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtransporte',
            name='fecha_facura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtransporte',
            name='num_factura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (3, 'Rechazada'), (5, 'Booked'), (4, 'Anulada'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Encomienda'), (1, 'Booking Ruta Programada'), (2, 'Nueva Solicitud Transporte'), (4, 'Vale de Combustible')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (3, 'Rechazada'), (5, 'Booked'), (4, 'Anulada'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(2, 'En proceso'), (1, 'Pendiente'), (4, 'Confirmado'), (3, 'Devuelta')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Transporte personas'), (2, 'Encomienda'), (3, 'Vale Combustible')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='parametro',
            field=models.CharField(blank=True, choices=[('1', 'CORRECTO'), ('2', 'OBSERVACION')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CI', 'CI'), ('PH', 'PH')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('HIDROCOOLER', 'HIDROCOOLER'), ('CUBA', 'CUBA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='parametro',
            field=models.CharField(blank=True, choices=[('1', 'CORRECTO'), ('2', 'OBSERVACION')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('HIDROCOOLER', 'HIDROCOOLER'), ('CUBA', 'CUBA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (3, 'Rechazada'), (5, 'Booked'), (4, 'Anulada'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(2, 'En proceso'), (1, 'Pendiente'), (4, 'Confirmado'), (3, 'Devuelta')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Transporte personas'), (2, 'Encomienda'), (3, 'Vale Combustible')], null=True),
        ),
    ]
