# Generated by Django 3.2.15 on 2023-10-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0064_auto_20231023_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudtransporte',
            old_name='fecha_facura',
            new_name='fecha_factura',
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (3, 'Rechazada'), (4, 'Anulada'), (1, 'Pendiente'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Booking Ruta Programada'), (3, 'Encomienda'), (4, 'Vale de Combustible'), (2, 'Nueva Solicitud Transporte')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (3, 'Rechazada'), (4, 'Anulada'), (1, 'Pendiente'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (3, 'Devuelta'), (4, 'Confirmado'), (2, 'En proceso')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (1, 'Transporte personas'), (3, 'Vale Combustible')], null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PH', 'PH'), ('APA', 'APA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (3, 'Rechazada'), (4, 'Anulada'), (1, 'Pendiente'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (3, 'Devuelta'), (4, 'Confirmado'), (2, 'En proceso')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (1, 'Transporte personas'), (3, 'Vale Combustible')], null=True),
        ),
    ]
