# Generated by Django 3.2.15 on 2023-10-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0065_auto_20231023_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingreporte',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingreporte',
            name='num_factura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (4, 'Anulada'), (1, 'Pendiente'), (5, 'Booked'), (3, 'Rechazada')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Nueva Solicitud Transporte'), (3, 'Encomienda'), (1, 'Booking Ruta Programada'), (4, 'Vale de Combustible')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (4, 'Anulada'), (1, 'Pendiente'), (5, 'Booked'), (3, 'Rechazada')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (2, 'En proceso'), (3, 'Devuelta'), (4, 'Confirmado')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PH', 'PH'), ('CI', 'CI')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='tipo',
            field=models.CharField(blank=True, choices=[('APA', 'APA'), ('PH', 'PH')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (4, 'Anulada'), (1, 'Pendiente'), (5, 'Booked'), (3, 'Rechazada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (2, 'En proceso'), (3, 'Devuelta'), (4, 'Confirmado')], null=True),
        ),
    ]
