# Generated by Django 3.2.15 on 2023-11-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0066_auto_20231024_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'managed': True, 'permissions': (('calendario_transporte', 'Administracion Transporte'), ('solicitudes_transporte', 'Solicitud Transporte'), ('autorizaciones_transporte', 'Autorizacion Transporte'), ('vales_combustible', 'Admini Vales Combustible'), ('reporte_transporte', 'Acceso a Reporte de Transporte'))},
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(4, 'Anulada'), (1, 'Pendiente'), (3, 'Rechazada'), (2, 'Aprobado'), (5, 'Booked')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(4, 'Vale de Combustible'), (3, 'Encomienda'), (1, 'Booking Ruta Programada'), (2, 'Nueva Solicitud Transporte')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(4, 'Anulada'), (1, 'Pendiente'), (3, 'Rechazada'), (2, 'Aprobado'), (5, 'Booked')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (2, 'En proceso'), (1, 'Pendiente'), (3, 'Devuelta')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Vale Combustible'), (1, 'Transporte personas'), (2, 'Encomienda')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CI', 'CI'), ('PH', 'PH')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PH', 'PH'), ('APA', 'APA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(4, 'Anulada'), (1, 'Pendiente'), (3, 'Rechazada'), (2, 'Aprobado'), (5, 'Booked')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (2, 'En proceso'), (1, 'Pendiente'), (3, 'Devuelta')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Vale Combustible'), (1, 'Transporte personas'), (2, 'Encomienda')], null=True),
        ),
    ]
