# Generated by Django 3.2.15 on 2023-11-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0068_auto_20231121_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (4, 'Anulada'), (5, 'Booked'), (3, 'Rechazada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Booking Ruta Programada'), (3, 'Encomienda'), (2, 'Nueva Solicitud Transporte'), (4, 'Vale de Combustible')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (4, 'Anulada'), (5, 'Booked'), (3, 'Rechazada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (2, 'En proceso'), (3, 'Devuelta'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Transporte personas'), (3, 'Vale Combustible'), (2, 'Encomienda')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PH', 'PH'), ('CI', 'CI')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('HIDROCOOLER', 'HIDROCOOLER'), ('CUBA', 'CUBA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PH', 'PH'), ('APA', 'APA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('HIDROCOOLER', 'HIDROCOOLER'), ('CUBA', 'CUBA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventariosemanal',
            name='unimed',
            field=models.CharField(choices=[('gr', 'Gramos'), ('GAL', 'Galones'), ('ml', 'Mililitros'), ('Kg', 'Kilogramos'), ('LT', 'Litros')], max_length=3),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(2, 'Aprobado'), (4, 'Anulada'), (5, 'Booked'), (3, 'Rechazada'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (2, 'En proceso'), (3, 'Devuelta'), (1, 'Pendiente')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Transporte personas'), (3, 'Vale Combustible'), (2, 'Encomienda')], null=True),
        ),
    ]
