# Generated by Django 3.2.15 on 2023-11-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0069_auto_20231121_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioConsolidado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('unimed', models.CharField(choices=[('ml', 'Mililitros'), ('LT', 'Litros'), ('GAL', 'Galones'), ('Kg', 'Kilogramos'), ('gr', 'Gramos')], max_length=3)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'procesos"."inventario_consolidado_agri',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='inventariosemanal',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='inventariosemanal',
            name='semana',
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada'), (4, 'Anulada'), (5, 'Booked'), (1, 'Pendiente'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Encomienda'), (1, 'Booking Ruta Programada'), (4, 'Vale de Combustible'), (2, 'Nueva Solicitud Transporte')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada'), (4, 'Anulada'), (5, 'Booked'), (1, 'Pendiente'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(3, 'Devuelta'), (1, 'Pendiente'), (2, 'En proceso'), (4, 'Confirmado')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (1, 'Transporte personas'), (3, 'Vale Combustible')], null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='parametro',
            field=models.CharField(blank=True, choices=[('1', 'CORRECTO'), ('2', 'OBSERVACION')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CI', 'CI'), ('PH', 'PH')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='parametro',
            field=models.CharField(blank=True, choices=[('1', 'CORRECTO'), ('2', 'OBSERVACION')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventariosemanal',
            name='unimed',
            field=models.CharField(choices=[('ml', 'Mililitros'), ('LT', 'Litros'), ('GAL', 'Galones'), ('Kg', 'Kilogramos'), ('gr', 'Gramos')], max_length=3),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(3, 'Rechazada'), (4, 'Anulada'), (5, 'Booked'), (1, 'Pendiente'), (2, 'Aprobado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(3, 'Devuelta'), (1, 'Pendiente'), (2, 'En proceso'), (4, 'Confirmado')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(2, 'Encomienda'), (1, 'Transporte personas'), (3, 'Vale Combustible')], null=True),
        ),
    ]
