# Generated by Django 3.2.15 on 2023-11-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesosAdministrativos', '0071_auto_20231122_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='egresos',
            name='usuario_registra',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (1, 'Pendiente'), (4, 'Anulada'), (2, 'Aprobado'), (3, 'Rechazada')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Booking Ruta Programada'), (3, 'Encomienda'), (4, 'Vale de Combustible'), (2, 'Nueva Solicitud Transporte')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (1, 'Pendiente'), (4, 'Anulada'), (2, 'Aprobado'), (3, 'Rechazada')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (2, 'En proceso'), (1, 'Pendiente'), (3, 'Devuelta')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingreporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Vale Combustible'), (1, 'Transporte personas'), (2, 'Encomienda')], null=True),
        ),
        migrations.AlterField(
            model_name='egresos',
            name='proyecto',
            field=models.CharField(choices=[('AV', 'La Avelina'), ('LM', 'La Merced'), ('AC', 'Agua Clara'), ('KO', 'Kosher'), ('ML', 'Los Molles')], max_length=3),
        ),
        migrations.AlterField(
            model_name='egresos',
            name='unimed',
            field=models.CharField(blank=True, choices=[('Kg', 'Kilogramos'), ('GAL', 'Galón'), ('gr', 'Gramos'), ('LT', 'Litros'), ('ml', 'Mililitros')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='eventosclorol2',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventospareceticol3',
            name='parametro',
            field=models.CharField(blank=True, choices=[('2', 'OBSERVACION'), ('1', 'CORRECTO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventarioconsolidado',
            name='unimed',
            field=models.CharField(choices=[('Kg', 'Kilogramos'), ('GAL', 'Galones'), ('gr', 'Gramos'), ('LT', 'Litros'), ('ml', 'Mililitros')], max_length=3),
        ),
        migrations.AlterField(
            model_name='inventariosemanal',
            name='unimed',
            field=models.CharField(choices=[('Kg', 'Kilogramos'), ('GAL', 'Galones'), ('gr', 'Gramos'), ('LT', 'Litros'), ('ml', 'Mililitros')], max_length=3),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado1n',
            field=models.IntegerField(blank=True, choices=[(5, 'Booked'), (1, 'Pendiente'), (4, 'Anulada'), (2, 'Aprobado'), (3, 'Rechazada')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='estado2n',
            field=models.IntegerField(blank=True, choices=[(4, 'Confirmado'), (2, 'En proceso'), (1, 'Pendiente'), (3, 'Devuelta')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(3, 'Vale Combustible'), (1, 'Transporte personas'), (2, 'Encomienda')], null=True),
        ),
    ]
